### ISSUE TITLE
What are these borders all around, the window and any panel ?

### ISSUE THREAD

**Issue by yanjankaf** [flxzt/rnote#1019]
**Describe the bug**  
There is a huge border around all the panels, and windows, if i full screen it goes away, but then it remians on other panels like the - hamburger menu, and the setting wrench icon ( Image is given in screenshot section)

**To Reproduce**  
Just open the `rnote` in the version same as mine

**Expected behavior**  
the border should not be there i guess

**Console Output**  
not applicable here - i'm using windows

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/61355855/2070b319-634e-4de4-adbf-f4a772f81387)
![image](https://github.com/flxzt/rnote/assets/61355855/dd4ae09c-d0fa-4afa-b541-55dad63aed17)

**Desktop (please complete the following information):**  
 - OS: Windows 10 22H2
 - App Version: latest release on the date of the making this bug, just downloded 
 - Installation Source: from exeutable, provided in release
 - Desktop Environment: [e.g. Gnome 45.2]
 - Display Server: [e.g. X11 or Wayland]
 - Input Source: [e.g. Mouse and Keyboard, On-Screen-Tablet, External Graphics Tablet, ...]

**Additional context**  
I got Nothing more

**Comment by Doublonmousse** [comment]
Seems similar to #842

**Comment by yanjankaf** [comment]
so i guess its wise to close it here, no point discussing it here - its all upto GTk guys to deal with it.
