### ISSUE TITLE
regression: document settings should not get synced between tabs

### ISSUE THREAD

**Issue by Doublonmousse** [flxzt/rnote#1021]
PR #1006 moved the document layout settings from the canvas menu to the settings pane.

This changes the behavior of layouts in large ways, that to me, feels like regressions.

- It is **not** possible to open at the same time two documents having two different document layouts at the same time in the same window. If I have a fixed size file and a semi-infinite file, the document layout is changed upon loading the first file and is applied to the second opened file in the second tab. Hence if I open first the fixed size file, the second file will open as a fixed size document, not displaying more than 1 page in the horizontal direction. If I do that in the reverse order, the fixed size file will be displayed as a semi infinite file instead. This is also confusing as the displayed file may not respect the actual document layout saved in the file.
- It is not possible to change the document layout of the current tab without affecting all of the other tabs.

Up till now, I've used rnote tabs to usually open two documents of different layouts, generally one of fixed size (my final document) and another one in one of the infinite layout for drafting on a much larger surface at the same time.
This is not possible anymore after this change as the change did not just relocate settings, but reduced the flexibility offered before.

- Version : main post PR #1006 
- Os : Mac os Sonoma
- source : compiled from main

**Comment by silvasch** [comment]
I was the original author of that PR (although @flxzt finished it for me). This is not the intended behaviour, the logic should have stayed the same.

I thought I was aware of this and implemented it the correct way, but it's possible that I (or @flxzt when making some edits) missed something.

**Comment by flxzt** [comment]
Thanks for reporting this! Luckily there hasn't been a release with this bug. This got probably introduced by f966b41 . It also affects other document settings (background patterns, ..) so nothing to do with your change @silvasch
