### ISSUE TITLE
Autosave without changes floods Nextcloud file versions

### ISSUE THREAD

**Issue by EverardNisse** [flxzt/rnote#1025]
**Describe the bug**  
Rnote autosave without changes to file triggers a sync and floods the logs and file versions of the Nextcloud client / server.  
Notably autosave is done even when the file has not been changed and Rnote is out of focus (meaning no view movement either)

**To Reproduce**  
1. Use Nextcloud client to sync a folder
2. Open a new rnote document
3. Enable Autosave
4. Open Nextcloud client notifications from the taskbar (pictured below)

**Expected behavior**  
Autosave detects that no changes have been made so it doesn't trigger the save which then triggers Nextcloud.

**Console Output**  
N/A Cannot run Flatpak on machine in question

**Screenshots**  
![rnote-nextcloud-sync](https://github.com/flxzt/rnote/assets/77442297/64c518fe-8c8f-44f5-b64c-edde6fa5389d)

**Desktop (please complete the following information):**  
 - OS: Arch
 - App Version: Rnote v0.9.4
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: KDE 5.27
 - Display Server: Wayland
 - Input Source: Touch laptop

**Additional context**  
N/A

**Comment by Doublonmousse** [comment]
Right.
For now the autosave also only applies to the opened tab of each window, I think it makes sense to autosave all unsaved changes from all tabs (and don't save anything that doesn't have any unsaved things).

It does not save anything if the file was not first saved to disk (relating this to #945).

I think I have a first working implementation for the first point, although there's still some more work (on catching unwraps and the like)
