### ISSUE TITLE
Add import option to improve PDF annotation use-case

### ISSUE THREAD

**Issue by MMachado05** [flxzt/rnote#1027]
**Is your feature request related to a problem? Please describe.**  
I was looking at RNote as a way to take notes for some of my university classes (annotating slide decks, handouts, etc.), but I noticed that importing PDFs into the software "played with" the PDF page layout.

For example, here's a screenshot from Okular showing a slide deck in a psychology class I'm taking:
![image](https://github.com/flxzt/rnote/assets/111894108/12f4d98f-75b4-4dae-81e1-d01b010b5616)

Then, I import that PDF into RNote, which, I'll say, is a bit unintuitive with the current import options that show up (I'm not sure what the options mean):
![image](https://github.com/flxzt/rnote/assets/111894108/636e0194-5708-48aa-95fe-ea1585d7d183)

Already, this is *not* what I expect when I import a PDF into an annotation tool. Ideally, all the pages would just show up ready to be focused on and annotating. The continuous option seems to help:
![image](https://github.com/flxzt/rnote/assets/111894108/b4511d24-0bf3-4380-9aa8-3778de7cfdaf)

but still, it moreso "opens" a file to be annotated on the current RNote file, rather than creating a new area to annotate a specific PDF file, which is what my current use case is.

Then, trying to *export* this file with whatever annotations I might have will result in a PDF largely unusable, when compared to the design and purposes of the original PDF. Either I can export  the pages of the document I've manually selected (which is infeasible with PDFs like the 100-odd page slide decks some professors use), which looks like this:
![image](https://github.com/flxzt/rnote/assets/111894108/2e406924-ffea-4785-bd4f-53a23a56afe2)

Or I can export the entire document, which breaks the pages based on how the import function worked:
![image](https://github.com/flxzt/rnote/assets/111894108/2c60607e-8e87-4c9e-b4a6-ba8c91e8dee2)

Or I can export the individual document's pages, which seemingly does the same thing here:
![image](https://github.com/flxzt/rnote/assets/111894108/cc741c51-8112-4edb-b762-d67f751f12ab)

None of which, unfortunately, give me the easy export-back-to-original-format behavior that I want.

**Describe the solution you'd like**  
Ideally, when importing a PDF, perhaps an option to open the PDF separately (rather than adding it to the current workspace) could be presented, and the workspace *is* that PDF, and nothing more. That way, exporting it back into a PDF will retain all of the original aspects of the PDF, while adding all of the annotations I might have created during my not-taking.

**Describe alternatives you've considered**  
Perhaps something else could be a more fleshed-out way to select only the pages of the PDF I've imported in the current workspace, and a better recognition of those pages' layout. Honestly, as long as there's an easy way to import a PDF, annotate it, and export it in a way that makes it look largely the same save my new annotations, I think that'll work.

**Additional context**  
Again, this is all for the primary use case of downloading PDF handouts from instructors to annotate them with notes, where the structure should be largely unchanged, and it can be used to look back on for exam review (notes with personal context)

**Comment by MariusAlbrecht** [comment]
some opinions from another user:
1. in my understanding rnote is _not_ a pdf annotation tool, its a note-taking app which _always_ operates on its own canvas. Like similar tools (ie oneNote) imports will inherently result in a loss of data (text for example) because they're only added ontop of to the existing canvas
2. you import your pdf into an existing rnote document. This has existing Page and Document format settings in place. If you want every one of your pdf pages to 1:1 cover a rnote page then you just have to configure your rnote document to do that
3. if you do that then the export will work pretty well. The imported and exported pages have a 1:1 mapping. The only thing that's lost is any sort of invisible structure the pdf had (most importantly, text) which is because the pdf is being converted to an image when importing and then converted back when exporting

**Comment by flxzt** [comment]
I do see the benefit of an pdf import option that adjusts the document format to the size of the pdf, aligns it to the pages and sets the page layout to fixed size.

**Comment by MMachado05** [comment]
> 1. in my understanding rnote is _not_ a pdf annotation tool, its a note-taking app which _always_ operates on its own canvas. Like similar tools (ie oneNote) imports will inherently result in a loss of data (text for example) because they're only added ontop of to the existing canvas

I was not aware of this! I was under the impression that, on top of being a note-taking tool, it also was intended to have PDF annotation functionalities. That being said, as mentioned by @flxzt, I think supporting this use case would greatly improve the user experience of the app.

> 2. you import your pdf into an existing rnote document. This has existing Page and Document format settings in place. If you want every one of your pdf pages to 1:1 cover a rnote page then you just have to configure your rnote document to do that

I'll have to look into that. A lot of the RNote UI doesn't feel super intuitive to me (could very well be a skill issue), so it'll take some effort, but that's effort I'm certainly willing to expend if it means I can take better class notes!

> 3. if you do that then the export will work pretty well. The imported and exported pages have a 1:1 mapping. The only thing that's lost is any sort of invisible structure the pdf had (most importantly, text) which is because the pdf is being converted to an image when importing and then converted back when exporting

This seems pretty promising, though yes, the internal data of how the PDF is structured being lost would be unfortunate. Also, how seamless would this document setup be for the case where each document is anywhere between 100-150 pages long? If there's some way I can configure RNote to automatically detect the PDF page structure, that's ideal, but otherwise, my original issue request stands.

This being said, thank you for pointing me in the direction of alternatives! I'll have to explore Rnote's other functionalities and see what else it can do for me.

**Comment by MariusAlbrecht** [comment]
seamless in what way?
Without the proposed new feature you'd maybe have to readjust page sizing.
Longer documents might also take considerable time to load (though I've also had ~150 page docs load almost instantly) #1024

also: #153
