### ISSUE TITLE
Background grid cells or rectangle drawn with ctrl hold isn't sqaure

### ISSUE THREAD

**Issue by RocketRide9** [flxzt/rnote#1028]
**Describe the bug**  
Background grid cells or rectangle drawn with ctrl hold isn't square

**To Reproduce**  
1. Start drawing a rectangle with left and right edges matching grid lines (see screenshot) while holding ctrl key.
2. Try align bottom and right edges with grid lines
3. See that it isn't possible, which means either drawn square isn't a square or grid cells aren't square (maybe both)

**Expected behavior**  
Rectangle drawn with ctrl and grid cells are being square

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/70429241/8826c77e-b53f-45e2-99a0-525dad8f0bb8)

**Desktop (please complete the following information):**  
 - OS: Fedora 39
 - App Version: Rnote v0.9.4
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 45.3
 - Display Server: Wayland
 - Input Source:

**Comment by flxzt** [comment]
what are your grid size settings? You can adjust the width and height of the grid yourself, maybe that's the reason. The drawn rectangle while holding shift should be square.

**Comment by flxzt** [comment]
no worries.
