### ISSUE TITLE
winget not update

### ISSUE THREAD

**Issue by Docfips** [flxzt/rnote#1037]
As the title says, using the ```winget```  on Windows is still the 0.9.4 version. screenshot is attached.
<img width="747" alt="Screenshot 2024-03-02 095250" src="https://github.com/flxzt/rnote/assets/65743899/413c0296-47ee-4d21-9b7d-6ab62e9372ea">

**Comment by flxzt** [comment]
Have some patience. The project maintainers/developers are all volunteers doing this in their free time and the winget maintainer might just not have had the time to update it.
