### ISSUE TITLE
Support to change binds

### ISSUE THREAD

**Issue by ArialCCAA** [flxzt/rnote#1038]
I am new to the application and quite like it. Was looking for an alternative to xournal++, because I got very frustrated with the lack of text wrapping and not being able to adjust the alignment of text. With Rnote this is really good. 
However, one issue I am having is that the keybinds not being something I can change is something that's causing some trouble. I am brazilian and use an american keyboard, and the only way to get a "?" is to do alt w, which brings the shortcuts screen.

**Comment by flxzt** [comment]
Thanks! There is already an opened issue requesting customizable keyboard shortcuts (#590) so I'll close as duplicate
