### ISSUE TITLE
Brush size sliders

### ISSUE THREAD

**Issue by gloopsies** [flxzt/rnote#104]
There should be some kind of a slider for selecting a brush size instead of just buttons to adjust it. Maybe it doesn't have to be a visible slider but how Adobe does it: sliding with mouse over a number increases/decreases the number

**Comment by flxzt** [comment]
This is a very easy feature to implement. Do you want to submit a PR for it?

**Comment by VodnikAngus** [comment]
I am finishing my last exam tonight and wanted to start playing with Rust and gtk4 so it should be a fun experience but since it will be my first time playing with this I don't promise anything

**Comment by flxzt** [comment]
Okay! As I am always saying, let me know if I can help out. Its just that there are lots of feature requests and not so many contributors. ;)
