### ISSUE TITLE
Image pasting resizes page to its size

### ISSUE THREAD

**Issue by arturopitu** [flxzt/rnote#1040]
**Describe the bug**  
Since the latest release (0.10.0), when pasting an image, the size of the page resizes to the width and height of the image. 

**To Reproduce**  
1. Copy an image, make a screenshot, etc. 
2. Paste

**Desktop (please complete the following information):**  
 - OS: [Debian 12]
 - App Version: [Rnote v0.10.0]
 - Installation Source: [Flatpak]
 - Desktop Environment: [e.g. Gnome 43.9]
 - Display Server: [wayland]

**Comment by flxzt** [comment]
Oh. Bitmap and Vector image import use the `adjust-document` settings from the pdf import dialog by accident.
