### ISSUE TITLE
Exporting some pages

### ISSUE THREAD

**Issue by PaveTranquil** [flxzt/rnote#1042]
Sometimes I need to export as PDF only some pages from my writings. Recently I use some small app to do it every time, but before I export a whole file from Rnote — I get too heavy file and it takes a long time when a writing has a lot of pages. So I'd be happy if it could be possible to export only selected pages just inside Rnote.

I think, it is the great solution to make text field and parse ranges and only pages from it as when you print file/web page, just like `3-4, 6, 8`. I show you an example when I print a page in my web browser (translate to English for you).
![image](https://github.com/flxzt/rnote/assets/22418658/c8f7f2a3-2956-41ff-9b04-aef26a02c47e)

Sorry in advance if the same issue has already created. I searched, but possibly I passed.

**Comment by flxzt** [comment]
Hi, thanks for the report. I agree that it should be a text field like users know it from print dialogs. You missed the open issue #400 in your search, I'll close as duplicate
