### ISSUE TITLE
Add settings for "Vertical space" tool in "Infinite" document layout

### ISSUE THREAD

**Issue by anefil** [flxzt/rnote#1048]
When document layout is set to "Infinite" or "Semi infinite", the tool should have options to work only on one vertical line of pages.

**Is your feature request related to a problem? Please describe.**  
I have a document with every homework assignment written in one column. I would like to use the tool for editing one vertical line of pages only.

**Describe the solution you'd like**  
Add tool-specific settings, like on the brushes or on the eraser.

**Describe alternatives you've considered**  
Using box selection provides difficulties, as I need to zoom out and accurately  select the pages. It is unpleasant

![image](https://github.com/flxzt/rnote/assets/95078518/f35033a8-b79e-464c-8509-92e4001f2448)

**Comment by Doublonmousse** [comment]
Fixed by #1116
