### ISSUE TITLE
Insert a new page between pages

### ISSUE THREAD

**Issue by mistune** [flxzt/rnote#1054]
**Is your feature request related to a problem? Please describe.**  
I would like to insert a new page between two pages.

**Describe the solution you'd like**  
Probably a button where I am able to insert a new page between the current page and the next page. 

**Describe alternatives you've considered**  
I do not see any alternatives within the app.

**Comment by flxzt** [comment]
It is possible to do this by:

Moving the content with the "vertical-space" tool.

It is more flexible than adding a page, but it might not be clear initially that this can be done

**Comment by mistune** [comment]
Tried it and it seems to do what I need. Thanks.

**Comment by whjum** [comment]
A side note to this issue for future reference: the "insert vertical space" is under the bottom toolbar - setting - insert-vertical-space.

**Comment by MathisP75** [comment]
Using the vertical space tool does not allow to create a page the exact same size as the others, so when you export to PDF, all the pages are shifted down.

**Comment by rick804** [comment]
I'm running into the same issue, but specifically when using Rnote for annotating homework PDFs.

The vertical-space tool works for creating space, but it doesn't seem to behave like an actual blank page when exporting the document back to PDF. I would really like the ability to insert a blank page between two existing PDF pages while preserving the original page dimensions.

Would this still be considered out of scope now that the vertical-space workaround has been found, or would a true "insert page" feature be something you'd consider?
