### ISSUE TITLE
Add the ability to move toolbars to different screen edges

### ISSUE THREAD

**Issue by RayJW** [flxzt/rnote#1059]
**Please submit only one feature request in one issue!**  
I think it would be great if the different toolbars can be movable. 

**Is your feature request related to a problem? Please describe.**  
The specific use case is moving the tool selection to the right instead of the bottom. The reason being that palm rejection is not always perfect, especially when working towards the end of the screen. Instead of trying to improve this complex mechanism in the underlying library, I think it would be much easier to give the user the option to change things around while also providing more customizability.

**Describe the solution you'd like**  
Just adding an option to move some of the bars around to different edges would be enough, I think. In a perfect world they would be freely movable, but I don't think that's necessary, and it also makes things much more complex in terms of responsiveness of the UI etc.

**Describe alternatives you've considered**  
Improve palm rejection which I think would be much more complex and might only improve the situation for some users.

**Comment by mahdihasan2006** [comment]
I think this is going be enough.

https://github.com/flxzt/rnote/assets/121625152/2429a9af-464f-4e03-9312-966f599570e1

**Additional considerations**

1. Moving multiple toolbars to one side would be good.
2. Long press in the focus mode button will show additional options to hide each toolbars separately

**Comment by RayJW** [comment]
That is exactly the kinda idea I had!

> Moving multiple toolbars to one side would be good.

I considered that as well, but I think this might cause issues in terms of minimum width and height required to properly display stuff, although having both the tool selection and colours at the top would be my preferred way as well.

**Comment by mahdihasan2006** [comment]
I also thought about the problem. This might be a solution.

https://github.com/flxzt/rnote/assets/121625152/18c138e0-9db8-419b-85d5-3bfac4fdc2fa

**Comment by flxzt** [comment]
There is a Gtk-based library that could enabled this - the one used by Gnome Builder

**Comment by flxzt** [comment]
let's discuss it further in #367
