### ISSUE TITLE
Higlighter option

### ISSUE THREAD

**Issue by gloopsies** [flxzt/rnote#106]
There should be a dedicated highlighter option that keeps the same opacity no matter how fast or slow you move your pen/mouse. Currently using translucent brush leaves weird circles that can be very close or very far from each other making line opacity very inconsistent and ugly.

![image](https://user-images.githubusercontent.com/5102074/152994318-bcdd8717-6045-4653-aa2a-b3e0055e2485.png)

**Comment by EDLLT** [comment]
This should be reopened
