### ISSUE TITLE
Copy-Paste selection export

### ISSUE THREAD

**Issue by Settordici** [flxzt/rnote#1069]
Now when I select something I've written, I can copy and paste it in another program as a png. The problem is that I cannot choose in any way the quality of this png and so it's very pixelated. Even when I change the DPI in the settings everything stays the same. What would be perfect is a way to decide the resolution of this copy/paste feature or even better, make it a svg instead of a png.

**Is your feature request related to a problem? Please describe.**  
When I copy a selection and I paste in in another program, the result is a low quality png.

**Describe the solution you'd like**  
A new setting to change the resolution of the pasted png or even better, make it a svg.

**Describe alternatives you've considered**  
I can use the export feature already present in rnote to export a selection at max quality, but this takes significately longer.

**Additional context**  
This is the difference between pasting and exporting as a svg. Done in logseq.
Also, it's not the program I'm pasting in the issue, because when I paste from Xournal++ the quality is high.
![image](https://github.com/flxzt/rnote/assets/63635493/d866ff0a-7e83-44f3-b94d-9ce69fa95653)

**Comment by flxzt** [comment]
The resolution is determined by the size on the canvas. However, Rnote already also supports copy-to-clipboard as Svg by default. Target apps like Inkscape that are able to paste Svg's work fine, so you'd need to poke the developers for whatever app you're pasting into for support.

**Comment by Settordici** [comment]
Is there any way to increase the resolution? Maybe just in terms of settings, because when I paste from another app I can use an higher resolution png so my problem would be fixed without the need of adding svg support. Either way, thank you for the quick answer, I'll close the issue soon.
