### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by arturopitu** [flxzt/rnote#1078]
**Describe the bug**  
Translations are missing since last update, 0.10.2, defaults to english, or at least spanish isn't showing.

**Desktop (please complete the following information):**  
 - OS: Debian 12
 - App Version: Rnote v0.10.2
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 43.9
 - Display Server: Wayland

**Comment by Doublonmousse** [comment]
Can you show the output of the `locale` command ? 
Seems like the translation defaults to english if `LC_ALL` is not set currently, not sure why exactly at the moment though.

**Comment by arturopitu** [comment]
```
$ locale
LANG=es_ES.UTF-8
LANGUAGE=
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=

```
Sure enough, LC_ALL isn't set, though i don't know if it needs to be set.

**Comment by oscfdezdz** [comment]
What does the output of running `flatpak config` show? If languages are not configured, you can run `flatpak config --set languages 'en;es'` and then `flatpak update`. You should add `--user` in both `flatpak config` commands if you have it installed as such.
