### ISSUE TITLE
Eraser behaviour is inconsistent with undo

### ISSUE THREAD

**Issue by categulario** [flxzt/rnote#109]
**Describe the bug**
I tried to undo an erase, and instead it erased some more shapes.

**To Reproduce**
1. Draw 5 shapes
2. Use the eraser to erase two of them
3. Ctrl+z
4. See that more shapes are gone instead of appear again

**Expected behavior**
The shapes (all) that I erased are back, because I "undoed" an erase operation

**Console Output**
Nothing relevant really

**Screenshots**

https://user-images.githubusercontent.com/790756/153225706-0c3d7ede-182c-4dc9-be3f-3e057f5b205e.mp4

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version latest update
 - Installation source Flatpak
 - Desktop Environment Gnome 41.3

**Additional context**
I happen to be writing a very similar application, also in rust, also with gtk. I might borrow some of your code :P

**Comment by flxzt** [comment]
its already a known issue, the undo / redo system needs to be revisited. (see #23)  
Why not contribute, if its very similar? :)

**Comment by categulario** [comment]
You are right about the export problem. My solution is to limit the size of the exported image to something reasonable, say 8K or whatever. In real life drawings don't really get that big and if they do they are useless as raster images anyways even if file size is not a concern. That's why I stayed with the ideal of big canvas and big zoom (as default) that allows a lot of freedom while taking the notes.

The thing about the size of the pen does make a difference from the user perspective, in a way that might be not very intuitive if switched to as a config. And it only makes sense if zooming is a common task (easy to perform). What I do is making + and - shortcuts to zooming and they zoom by a factor of 2. You click twice and you already can write side-notes next to words of the previous zoom level.

Yeah, XML sucks in a lot of ways, but hey! it's a standard (SVG) and you get file previewing for free and even embedding drawings in a website.

So, what I'm saying is that while I wouldn't abandon my own project to work on yours I do think we can learn a lot from each other and share some ideas and probably save ourselves some time. For instance, you might want to take a look at my [undo implementation](https://gitlab.com/categulario/pizarra/-/blob/master/src/app.rs#L118-120) and I definitely have a lot to learn about gtk[4] from your code.

Btw, something that I think had a huge impact in my code quality was splitting the app's internals from the gtk impl. That way I can test almost every behavior in [the crate](https://crates.io/crates/pizarra) and just have some [gtk code](https://gitlab.com/categulario/pizarra-gtk) as bridge. (Sorry (not really) about the spanish readmes :wink: )

**Comment by flxzt** [comment]
> was splitting the app's internals from the gtk impl

I tried to do that a little bit with the sheet struct. Its not fully separated from GTK, mainly because of the rendering. I can see some things I can adopt from pizarra, thanks!

> I do think we can learn a lot from each other and share some ideas and probably save ourselves some time  

Yeah definitely, I think the potential for collaboration is big! I guess I just see so many similar apps by single devs and think, what could be done by joined efforts.

**Comment by categulario** [comment]
That's true. The hard thing about joined efforts is coordination and agreement.

What other similar projects do you know? (I'm making a list) Here's what I've got so far:

* [OpenBoard](https://openboard.ch/index.en.html)
* [Xournal (++)](https://xournalpp.github.io/)
* [Lorien](https://github.com/mbrlabs/Lorien)
* [MrWriter](http://unruhschuh.github.io/MrWriter/)
* [Rnote](https://github.com/flxzt/rnote/issues/109)
* [Write](http://www.styluslabs.com/download/)
* [Pizarra](https://pizarra.categulario.tk)

Do you want to move this conversation somewhere else? Do you use telegram?

**Comment by flxzt** [comment]
Open source projects or in general?

I made a matrix room for Rnote [https://matrix.to/#/#rnote:matrix.org](https://matrix.to/#/#rnote:matrix.org)

**Comment by categulario** [comment]
Open source
