### ISSUE TITLE
 change doc-save-symbolic to floppy-disk like icon

### ISSUE THREAD

**Issue by MariusAlbrecht** [flxzt/rnote#1090]
**Is your feature request related to a problem? Please describe.**  
The current icon for the "Save document" dialog is one that's almost universally used for a "download" action and _not_ a "save to disk" action. This is confusing

**Describe the solution you'd like**  
use a floppy-disk like icon which is usually used for "save to disk" actions

**Comment by flxzt** [comment]
see #428 - my reasoning hasn't change since then

**Comment by MariusAlbrecht** [comment]
thats absolutely my bad for not checking existing issues properly, sorry!
Perfectly understandable reasoning.
