### ISSUE TITLE
Color Palette Not Showing Colors

### ISSUE THREAD

**Issue by Mash-em** [flxzt/rnote#1098]
**Describe the bug**  
Color Palette Not Showing colors after changing theme to system theme

**To Reproduce**  
1. Change Gtk4 theme to Dracula

**Expected behavior**  
Normal Color Palette Tray with all Colors

**Screenshots**  
![swappy-20240514_215922](https://github.com/flxzt/rnote/assets/169830207/f3a4184b-7c84-486e-8690-67635545cc64)

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 - App Version: Rnote v0.10.2
 - Installation Source: Archlinux Community Repo

**Comment by flxzt** [comment]
Custom  theme's are not supported, I'd suggest switching back to the default `Adwaita` theme at least for Rnote. It's impossible to anticipate the changes made to the CSS stylesheet so it's not fixable by the app.

**Comment by HynDuf** [comment]
> Custom theme's are not supported, I'd suggest switching back to the default `Adwaita` theme at least for Rnote. It's impossible to anticipate the changes made to the CSS stylesheet so it's not fixable by the app.

Excuse me, it felt weird to me when the program is implemented to support GTK4 but only support `Adwaita`. Why not just enforce `Adwaita` color scheme to the program itself?
