### ISSUE TITLE
Reduce User input Effort for "Reset Zoom to 100%" (e. g. via Keyboard shortcut or Graphics Tablet / Pen Buttons)

### ISSUE THREAD

**Issue by fredsilon** [flxzt/rnote#1099]
A solution is requested to be able to easily switch back to a reference zoom level (100%) with less input friction/effort compared to the current possibilities.

**Is your feature request related to a problem? Please describe.**  
At the moment it takes some "effort" to reset the zoom to 100% via two clicks.

**Describe the solution you'd like**  
Add keyboard shortcut for "Reset Zoom to 100%":
For example: "Ctrl + 0" (Same shortcut as it is available with Firefox, Chromium ... however maybe it's not logical to have "Change tool" on Ctrl 1 ... 6, but a different shortcut category on Ctrl + 0)

**Describe alternatives you've considered**  
Even quicker to access would be any Button of a Graphics Tablet / Pen ... optionally plus making use of a modifier Key (Shift, Ctrl, Alt, etc.) of a keyboard:
e. g. "Shift on Keyboard" + "Button <DEFINED by USER> of a Graphics Tablet / Pen"

**Comment by flxzt** [comment]
let's track additional pen shortcuts in #865
