### ISSUE TITLE
Rnote crash, Segmentation fault(Core dumped)

### ISSUE THREAD

**Issue by lVentus** [flxzt/rnote#1103]
**Describe the bug**  
Crash after some operation with stylus pen. Especialy when using selector or creating a new tab or try to move with fingers
And sometimes , pen draw become rectangle selector.

**To Reproduce**  
just draw with stylus or click some menu button with pen

**Expected behavior**  
normally work

**Console Output**  
```
Segmentation fault (core dumped)

```

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: nixos 23.11
 - App Version: 0.10.2
 - Installation Source: nixpkgs
 - Desktop Environment: hyprland
 - Display Server: Wayland
 - Input Source: Surface pro 8

**Additional context**  

I used GSK_RENDERER=gl
But it doesn't work
it seems has no issue with gtk things.
only when I use my pen, it will crash

https://github.com/flxzt/rnote/assets/35456565/d4c2cc6f-d73a-4d77-bdf4-1666f9927d4a

**Comment by PietHelzel** [comment]
Maybe similar to #810 ? Similar problem, also on Hyprland.

**Comment by HydroH** [comment]
I'm experiencing the same problem on GNOME with wayland, on a Surface Laptop Studio.
Maybe a surface pen driver problem?

**Comment by lVentus** [comment]
> I'm experiencing the same problem on GNOME with wayland, on a Surface Laptop Studio. Maybe a surface pen driver problem?

I think it may be a stylus driver problem
