### ISSUE TITLE
MacOS app download links return a 404

### ISSUE THREAD

**Issue by patrinos** [flxzt/rnote#1106]
I tried to download the app for MacOS, x86 from https://gitlab.com/dehesselle/rnote_macos/-/releases but all download links return a 404. E.g.  https://gitlab.com/api/v4/projects/44053427/packages/generic/rnote_macos/0.10.2%2B161/Rnote-0.10.2+161_x86_64.dmg

** Steps to reproduce the behavior: **
1. Go to '[...](https://gitlab.com/dehesselle/rnote_macos/-/releases)'
2. Click on '[Rnote-0.10.2+161_x86_64.dmg](https://gitlab.com/api/v4/projects/44053427/packages/generic/rnote_macos/0.10.2%2B161/Rnote-0.10.2+161_x86_64.dmg)'
3. Link returns a 404

**Expected behavior**  
A MacOS dmg file

**Desktop:**  
 - OS: [MacOS 13.6.7 (22G720)]

**Comment by dehesselle** [comment]
Something happened on GitLab's site which broke lots of my release across all my projects. I'll have to create a new release.
In the meantime, you can access the downloads via the package registry: https://gitlab.com/dehesselle/rnote_macos/-/packages/24327832

**Comment by patrinos** [comment]
Thank you very much for your quick response. 
I confirm that this link works.

**Comment by flxzt** [comment]
lets keep this open until the links are actually fixed

**Comment by dehesselle** [comment]
I have confirmation from GitLab that it's a regression caused by a recent change on their end. I expect that the functionality will be restored. I'll update here once I have more info.

**Comment by patrinos** [comment]
Of course, my bad.

**Comment by dehesselle** [comment]
Issue was fixed by GitLab.
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/154248

**Comment by patrinos** [comment]
I checked a couple of download links and they worked. Closing ticket.
