### ISSUE TITLE
Small dots that appear on the screen and cannot be erased

### ISSUE THREAD

**Issue by jfab20** [flxzt/rnote#1108]
While drawing/writing, some dots randomly appear on the screen and cannot be erased

![image](https://github.com/flxzt/rnote/assets/81712003/d455dd6b-6c7e-4f2f-ab71-6a1e77e67c03)

I can select the dots and when I enlarge them I get this: 

![image](https://github.com/flxzt/rnote/assets/81712003/cf6cd1c5-83c6-4f92-b592-b3186ef52068)

The only way to delete them is to select them and press the delete button on my computer (even when they are large).  I cannot reliably reproduce how to create this dots but they appear randomly while I'm writing and it gets annoying. 

**Expected behavior**  
Write normally without random dots appearing on the screen.

I find this hard to reproduce on command but this bug is extremely common, I don't know what triggers it
![image](https://github.com/flxzt/rnote/assets/81712003/736a7f20-b1aa-4e16-9f0b-2909bc1d1f3a)

**Desktop (please complete the following information):**  
 - OS: arch 6.9.2-1
 - App Version: Rnote v0.10.2-1
 - Installation Source: Arch linux community repo
 - Desktop Environment: Hyprland
 - Display Server: Wayland
 - Input Source: External graphics tablet

**Comment by Doublonmousse** [comment]
Maybe it's related to #414 or #889 ?

**Comment by flxzt** [comment]
Can you share the rnote file that contains these non-erasable dots? You can remove all other data on it if it is sensitive to you.

**Comment by jfab20** [comment]
Sure. 
[test.zip](https://github.com/user-attachments/files/15741648/test.zip)

**Comment by flxzt** [comment]
Looks like single element strokes were not generating hitboxes that are queried by the eraser. They do have bounds, that's why they can be selected.

The remaining issue is: why are there random single element strokes appearing for you? It doesn't read like that was done intentionally by you

**Comment by RayJW** [comment]
> The remaining issue is: why are there random single element strokes appearing for you? It doesn't read like that was done intentionally by you

Not OP, but I can say that definitely happens to me as well occasionally. I'm not sure, but my gut feeling says it usually happens when just tapping the screen with the pen, on accident most of the time. Say I was selecting something and then either the selection goes away before I tap the screen or there's immediately a second tap for some reason. And no, so far I never intended to create these single element strokes.

**Comment by flxzt** [comment]
Probably happening because of the immediate return of the selector/eraser tools instead of needing another up->down cycle. I think #414 is related

**Comment by flxzt** [comment]
The event stream log when this occurs would be very helpful. You can capture it through `RUST_LOG=rnote=trace` (but be warned, it's very verbose)

**Comment by jfab20** [comment]
@flxzt Hey, was this fixed by some update? I have rnote 0.11.0-1 and I cannot longer reproduce the bug. I think I will close the issue now. Thank you very much!
