### ISSUE TITLE
License on Flathub listing is wrong.

### ISSUE THREAD

**Issue by cameronbosch** [flxzt/rnote#1112]
**Describe the bug**  
The license for Rnote is GPLv3 or later, not GPLv3 only. 

**To Reproduce**  
1. Go to [the Flathub listing for Rnote](https://flathub.org/apps/com.github.flxzt.rnote).
3. Scroll down to the license area.'
4. The license is wrong (GPLv3 only).

**Expected behavior**  
The license should be corrected to GPLv3 or later.

**Screenshots**  
![Rnote is licensed under the GPLv3 or later screenshot.](https://github.com/flxzt/rnote/assets/72839795/ba424652-f707-4469-8a0a-f61ccb80712d)

I just reposted this on the Flathub repo too.

**Comment by flxzt** [comment]
You're right, the license was specified as `GPL-3.0` in the appstream XML file by mistake.
