### ISSUE TITLE
Imported PDFs displayed as pink boxes

### ISSUE THREAD

**Issue by snakedye** [flxzt/rnote#1121]
**Describe the bug**  

PDFs appear as red boxes when imported.

**To Reproduce**  

1. Import a PDF
![image](https://github.com/flxzt/rnote/assets/49378990/1c421a95-643a-49b6-bfd4-56908b2b7daf)
2. Click import
3. The PDF is red
![image](https://github.com/flxzt/rnote/assets/49378990/8047ebdc-64bd-44be-a7b2-531cc86b2bdc)

**Expected behavior**  
The PDF appears as is. Not as a red box.

**Console Output**  

```
Gsk-Message: 10:21:50.608: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display

Gsk-Message: 10:21:50.608: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display

Gsk-Message: 10:21:50.956: Failed to realize renderer of type 'GskVulkanRenderer' for surface 'GdkWaylandToplevel': Could not create a Vulkan instance: The requested version of Vulkan is not supported by the driver or is otherwise incompatible for implementation-specific reasons. (VK_ERROR_INCOMPATIBLE_DRIVER)

Gsk-Message: 10:21:56.548: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display

Gsk-Message: 10:21:56.548: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display

Gsk-Message: 10:21:56.853: Failed to realize renderer of type 'GskVulkanRenderer' for surface 'GdkWaylandToplevel': Could not create a Vulkan instance: The requested version of Vulkan is not supported by the driver or is otherwise incompatible for implementation-specific reasons. (VK_ERROR_INCOMPATIBLE_DRIVER)
```

**Desktop (please complete the following information):**  
# System Details Report
---

## Report details
- **Date generated:**                              2024-06-15 10:22:54

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. ZenBook UX462DA
- **Memory:**                                      12.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 3700U with Radeon™ Vega Mobile Gfx × 8
- **Graphics:**                                    AMD Radeon™ Vega 10 Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            UX462DA.307
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.11-300.fc40.x86_64

**Additional context**

**Comment by flxzt** [comment]
I suspect this is yet another issue related to the new 'ngl' renderer of Gtk. Try the old 'gl' renderer by setting env var `GSK_RENDERER=gl'

**Comment by flxzt** [comment]
Actually, this seems to be the same issue as #963 .

**Comment by snakedye** [comment]
For some reason this morning it started working.

**Comment by astro-ray** [comment]
I had a similar issue but after updating my drivers, the problem was fixed.

**Comment by flxzt** [comment]
Since this is likely a driver issue and it seemingly stopped happening I'll close as resolved.
