### ISSUE TITLE
broken rendering with Windows 10 Education N

### ISSUE THREAD

**Issue by xkmanlordx** [flxzt/rnote#1125]
Version 0.10.2 App won't open, well I guess strictly speaking it is opening, somehow, under Windows 10.
![rip](https://github.com/flxzt/rnote/assets/99927704/aedebb5f-6f22-44ab-a5c1-c8fc7bd87ea0)

See image attached, works fine on Windows 10 Home and Windows 11.

System:
Intel(R) Core(TM) M-5Y71 CPU @ 1.20GHz   1.30 GHz
RAM	8,00 GB
64-Bit-OS, x64-Prozessor

Edition	Windows 10 Education N
Version	22H2
systembuild	19045.4529
Windows Feature Experience Pack 1000.19058.1000.0

**Comment by Doublonmousse** [comment]
Somewhat similar to https://github.com/flxzt/rnote/discussions/1105#discussioncomment-9729024.

Can you 
- check if 0.10.1 works
- maybe add information on the gpu and check if updating gpu drivers solve this issue

Did you test the different os edition on the same pc with the same gpu drivers ?

Chances are this is a gpu-related issue from gtk, and that may be fixed upon next release (from updating the gtk version to 4.14)

**Comment by xkmanlordx** [comment]
0.10.1 works.

My bad, the other Windows versions were on different systems. On this laptop I am dual booting macOS Big Sur where Rnote-0.10.2+161_x86_64.dmg works fine.

The graphic card is: Intel HD Graphics 5300 1536 MB

**Comment by flxzt** [comment]
the just released Rnote v0.11.0 uses gtk4.14 in it's windows build which includes changes in it's renderer. can you check if it still is an issue?

**Comment by xkmanlordx** [comment]
v0.11.0 is working fine, no issues . :) many thanks and nice work!
