### ISSUE TITLE
[hyprland] Crash after using brush with Surface Pen on Linux

### ISSUE THREAD

**Issue by mitgitumgekippt** [flxzt/rnote#1126]
**Describe the bug**  
After using the brush, the program crashes after some seconds. This happens only after using the brush and not with any other tool. I can use the brush and the lines are displayed on screen. It happens with any file, no matter whether it is a new one or an already stored.
This only happens when using my surface pen. When I use the brush with the mouse or with my finger, the program runs normally without crashing.

**To Reproduce**  
1. Open rnote
2. Use the brush with the surface pen
3. Crash

**Expected behavior**  
No Crash

**Console Output**  
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote`
and post the output. -> Not applicable, because I installed it from the AUR
When starting rnote with the terminal, I get following error: Job 1, 'rnote' terminated by signal SIGSEGV (Address boundary error)

**Screenshots**  
If applicable, add screenshots to help explain your problem. -> Not applicable.

**Desktop (please complete the following information):**  
 - OS: Arch Linux x86_64 (6.9.3-arch1-2-surface)
 - App Version: Rnote v0.10.2 
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: Hyprland 0.41.1-1
 - Display Server: Wayland
 - Input Source: On-Screen-Tablet

**Additional context**  
I am using a Surface Pro 7, with the current linux-surface kernel (6.9.3.arch1-2) and the corresponding pen.

**Comment by flxzt** [comment]
Can you run it with `RUST_LOG=rnote=debug rnote` and post the log? That does the same as the `--env` flag for the flatpak

**Comment by kwevin** [comment]
Hi, same setup, same problem, here's the log (ran with `RUST_BACKTRACE=1 RUST_LOG=rnote=debug rnote`).
[rnote.log](https://github.com/user-attachments/files/15942555/rnote.log)
It crashes with segmentation fault, and it seems to happen after drawing with the stylus then using any touch input.

**Comment by kwevin** [comment]
Hello again, downgrading `hyprland` from v0.41.1 to v0.40.0 seems to resolve the issue.

**Comment by FedX-sudo** [comment]
Hi, I have experienced this issue as well on my StarLabs Starlite MKV. I have it set up using NixOS Unstable and Hyprland. The application works fine if I use touch or a stylus, but once I switch, it crashes.

I believe this issue may be stemming from a GTK Hyprland interaction as I have observed the behavior on multiple GTK programs (RNote, Xournal++, Librewolf, and Pavucontrol), but not observed the behavior on any other kind of GUI backed (UnCiv, Krita, OpenSCAD, Kitty, and Blender). In my debugging, it may be stemming from a cursor issue, but I have been unable to confirm that. 


Related: https://github.com/hyprwm/Hyprland/issues/6312

**Comment by mrWinston** [comment]
X-Posting from https://github.com/hyprwm/Hyprland/issues/6312#issuecomment-2206066839 : 

Forcing rnote to run in xwayland makes the crashing go away (at least for me):
```
env -u WAYLAND_DISPLAY flatpak run com.github.flxzt.rnote
```

**Comment by mrWinston** [comment]
Fyi, Hyprland has now a fix for this particular problem: https://github.com/hyprwm/Hyprland/pull/6761

I believe, this ticket can now be closed.

**Comment by LSeelig** [comment]
I am using Phosh but might be experiencing this.

**Comment by flxzt** [comment]
looks like it. I'll close, hyprland users should update to a version that includes this fix
