### ISSUE TITLE
prompt for confirmation when removing folders

### ISSUE THREAD

**Issue by ishusain** [flxzt/rnote#1136]
**Describe the bug**  
I deleted the 'Documents' directory from the Default Workspace, corresponding to '~/Documents' linux directory.

The directory was permanently deleted, and not even a user dialog warning about this was issued.

The deleted directory wasn't moved to the Trash bin, it was permanently deleted.

I tried recovering it with the Linux tool 'testdisk' without success.

**To Reproduce**  
1. Go to the Workspace
2. Delete a directory

**Expected behavior**  

The deleted directory should have been moved to the Trash bin, or at least warn me that it was going to be permanently deleted.

**Console Output**  

I can't provide the output because I turned off the computer to try to recover the deleted data with 'testdisk' Linux utility. I'm afraid that turning it on again will overwrite the unallocated disk sectors that were originally occupied by the deleted data.

**Desktop**  
 - OS: Kubuntu 22.04
 - App Version: Rnote v0.10.2
 - Installation Source: Flatpak
 - Desktop Environment: KDE Plasma 5.24 
 - Display Server: Wayland
 - Input Source: Mouse and Keyboard, External Graphics Tablet

**Comment by ishusain** [comment]
So after using 'r-linux' data recovery tool, I could track the deleted files and find them in '~/.local/share/Trash/files/'. Just moving them to 'home/' solved the problem.

Anyway, I insist that RNote should have a pop-up dialog warning the user about this.

**Comment by flxzt** [comment]
Yes, agreed. At least when trashing folders that are not empty. It's too easy to accidentally do that currently

**Comment by RayJW** [comment]
I'll have a go at this if that's fine with everyone :) Can't promise a time frame though, I'll have to learn to deal with GTK first.
