### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#114]
The current icon doesn't quite fit the HIG, would you be interested in help with a new one?

Here's a first idea I had, but I'd be happy to try something else:

![image](https://user-images.githubusercontent.com/1908896/154107356-ec3381f2-7db9-4f5d-a43b-a417f939c0c4.png)

**Comment by bertob** [comment]
Ping? Happy to try some alternatives if you don't like the direction above :)

**Comment by flxzt** [comment]
Thanks for the offer, and sorry for not responding at first. I was pretty concentrated on fixing and refactoring rnotes internals.

Do you have more ideas?
A thought from me, maybe the icon would not even need to have a pen? Having some prominent nicely shaped bezier curves could also give the hint as a handwriting drawing app?

My own poor first attempts:

![2022-04-24_19-17-41_selection](https://user-images.githubusercontent.com/19841886/164988402-64caab8d-7da7-4f7a-94c5-37331de72367.svg)


and some other icons from I liked the style while browsing the software center, maybe to give a direction

![2022-04-24_19-10-07_selection](https://user-images.githubusercontent.com/19841886/164988080-0df25785-85e5-42a1-b982-126864fab5bd.svg)


What are your thoughts?

**Comment by bertob** [comment]
Here's an attempt at doing something in the direction you suggested:

![image](https://user-images.githubusercontent.com/1908896/165367148-bc448619-a5f3-4607-946b-15fda5ce8d73.png)

**Comment by flxzt** [comment]
Thanks, I personally like this a lot! I think this is the right direction.
Is the "R" good as a shape or should there be something different like some indicated handwriting and curves like in your first proposal? I don't really have a opinion on that, the R was only the first idea.

I know the steel blue I have currently chosen is not really a good color against dark backgrounds, but maybe we could play around with those tones and do a lighter / more contrast variant of it for the book cover?

And thank you so much for the work, it is very appreciated!

**Comment by bertob** [comment]
> Is the "R" good as a shape 

I think with the current name it's pretty good, also because the way it's drawn indicates handwriting. That said, the current name isn't that great, so maybe we don't want to connect the identity to that, so it's easier to change later. If you're interested in brainstorming some potential alternative names more in line with the [naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html), I'd be happy to help :)

Here's an attempt at a steel blue cover, but I think the red felt much more interesting and visually balanced:

![image](https://user-images.githubusercontent.com/1908896/167961383-a2a0aabb-2796-4b96-aa1b-719de8704ead.png)

**Comment by flxzt** [comment]
Good points. I agree that we maybe should leave the option to change the name later. Let's go with the red, and what you think looks best for the rest. :)

**Comment by bertob** [comment]
Another try:

![image](https://user-images.githubusercontent.com/1908896/168270019-6b16dec8-81af-450e-9be6-138628f697cb.png)

**Comment by flxzt** [comment]
I totally missed how great spiro splines can look! I could not help it but playing around with it myself. (while going back to the blue-grey color). I think this could be the convergence of the previous ideas?
![Vorschau](https://user-images.githubusercontent.com/19841886/170061342-448b2088-a6c4-48c3-9fff-e32c70e8eea7.png)

**Comment by bertob** [comment]
The dark cover doesn't work, the outer edges of the icon need to be light-ish, so they don't blend in on dark colors (light on light is fine because of shadows, but that doesn't work for dark).

As for the spiro, the bottom part looks fine but the top feels a bit lost. If that was fixed I think it could work.

Also, I don't think the horizontal red line works, I'd drop it or maybe try a different color.

**Comment by flxzt** [comment]
hmm. I am aware, but I had hoped you'd approve (since I moved the binder color gradient so that the bright color is on the left, and the bottom border color is also relatively bright.) All I can say that it does not look all that bad on my screen with the contrast.

e.g. here (obfuscate arguably is worse contrast-wise)
![grafik](https://user-images.githubusercontent.com/19841886/170136256-bd6b8814-5da8-41d1-a90b-116f02371788.png)


Next iteration, with your other suggestions and thicker bottom border:

![Vorschau](https://user-images.githubusercontent.com/19841886/170135070-0e78122d-a53c-4840-b2b1-1a780362e588.png)

**Comment by bertob** [comment]
Hmm, it's still a bit dark, but I guess it's fine. The spiro works for me :+1: 

Now we just need a nice symbolic. Could try just the spiro shape maybe?

**Comment by flxzt** [comment]
🥳 I am relieved. Yes absolutely, if that is possible within the few pixels I could imagine that it'll look great

**Comment by bertob** [comment]
Maybe it could be a slightly simplified version of the spiro, e.g. one less curve?

**Comment by flxzt** [comment]
sure :) my only concern on first thought with it that it could start looking like a question mark

**Comment by flxzt** [comment]
the spiro could probably just be flipped to avoid this, probably makes more sense for most right handed writers anyways

**Comment by bertob** [comment]
Could be worth trying, yeah.

**Comment by flxzt** [comment]
I couldn't get the app icon preview to take the symbolic, so here is it in the symbolic preview app: 
![grafik](https://user-images.githubusercontent.com/19841886/170268455-841826b2-e233-4b5d-a1fc-4d56a85d64ac.png)
And the flipped version:
![Vorschau](https://user-images.githubusercontent.com/19841886/170268562-a95b87e5-c993-4ee3-9ef8-0d2c1b27692a.png)

**Comment by bertob** [comment]
> I couldn't get the app icon preview to take the symbolic

That's odd, how are you drawing it? I'd recommend starting from scratch with the template from app icon preview, and doing both of the icons on the same canvas.

The icons look good though :+1:

**Comment by flxzt** [comment]
Just edited the post, not sure which of both options is better for the symbolic.

> That's odd, how are you drawing it? I'd recommend starting from scratch with the template from app icon preview, and doing both of the icons on the same canvas.  

I tried that, but it just doesn't show the symbolic :/

**Comment by bertob** [comment]
I prefer the second one, looks more dynamic.

> I tried that, but it just doesn't show the symbolic :/

Hmm, does the file name end in `.Source`?

**Comment by flxzt** [comment]
no, but I can't get it to work either way. Probably doing something wrong inside Inkscape..  
Anyways, I'll merge this new icon and the second symbolic.
Thanks again for your ideas, input and feedback and the previous work that can be utilized here. I think the end result is very pleasing!
