### ISSUE TITLE
Pasted image should automatically be sized to image width instead of protruding into unprintable area

### ISSUE THREAD

**Issue by gaznu** [flxzt/rnote#1145]
- Use-Case: Taking a screenshot of an exercise from a pdf, pasting it to rnote to solve using a pen. Because rnote has better pen support.

- Problem: Screenshot pasted is too big, so for every exercise I have to manually resize the image in multiple steps. This makes it bothersome.

- Solution: width (and height) of an imported image should automatically be resized to page-width/-height. I see no advantage if it protrudes into the unprintable, black area

In any case, thank you for this stable, pen-focused program.

**Comment by Doublonmousse** [comment]
The feature has already been added to main but not released yet. (See #1004 and #974)

It will be there in the next release.
