### ISSUE TITLE
black edges on thinkpad T14p

### ISSUE THREAD

**Issue by zhoucying** [flxzt/rnote#1197]
<img width="893" alt="Snipaste_2024-09-01_17-53-09" src="https://github.com/user-attachments/assets/d10a0216-cb57-459b-8de7-43431b1a14cd">

版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎8/‎26
操作系统版本	22631.4112
体验	Windows Feature Experience Pack 1000.22700.1034.0

[显示]
DirectX 版本：	12.0 
GPU 处理器：		NVIDIA GeForce RTX 3050 4GB Laptop GPU
驱动程序版本：			560.94
驱动器类型：			DCH
Direct3D 功能级别：		12_1
CUDA 核心：		2560 
Max-Q  技术		是
动态增强			是
WhisperMode		否
高级 Optimus		否
显卡最大功率			50 W
核心时钟：			1365 MHz 
内存数据速率：			14.00 Gbps
内存接口：			64-位 
内存带宽：			112.02 GB/秒
全部可用的图形内存：		20308MB
专用视频内存：			4096 MB GDDR6
系统视频内存：			0MB
共享系统内存：			16212MB
视频 BIOS 版本：		94.07.87.00.4D
IRQ：			Not used
总线：			PCI Express x4
设备 ID：			10DE 25AB 50D417AA
部件编号：			4728 0010

[组件]

nvui.dll		8.17.15.6094		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.15.6094		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.15.6094		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.15.6094		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.15.6094		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvLicensingS.dll		6.14.15.6094		NVIDIA Licensing Server
nvViTvSR.dll		32.0.15.6094		NVIDIA Video Server
nvViTvS.dll		32.0.15.6094		NVIDIA Video Server
nvDispSR.dll		32.0.15.6094		NVIDIA Display Server
nvDispS.dll		32.0.15.6094		NVIDIA Display Server
nvDevToolSR.dll		32.0.15.6094		NVIDIA Licensing Server
nvDevToolS.dll		32.0.15.6094		NVIDIA 3D Settings Server
nvWSSR.dll		32.0.15.6094		NVIDIA Workstation Server
nvWSS.dll		32.0.15.6094		NVIDIA Workstation Server
PhysX		09.23.1019		NVIDIA PhysX
NVCUDA64.DLL		32.0.15.6094		NVIDIA CUDA 12.6.65 driver
nvGameSR.dll		32.0.15.6094		NVIDIA 3D Settings Server
nvGameS.dll		32.0.15.6094		NVIDIA 3D Settings Server

**Comment by Doublonmousse** [comment]
Duplicate of #842, let's discuss further in there
