### ISSUE TITLE
Selecting item and Moving Not Smooth/Precise Like Before

### ISSUE THREAD

**Issue by mbeps** [flxzt/rnote#1214]
**Describe the bug**  
Before, when selecting an item (like strokes) with the selection tool and then dragging it to move it would be smooth and precise. Currently, doing the same would not allow me to drop an item at an exam location but in a defined area or block. It feels like there is a grid and you can only drop stuff inside this grid and not precisely where you want it. This happens with both mouse and pen. 

**To Reproduce**  
1. Write something random with the pen 
2. Toggle 'Selector' and select the whole item you just created
3. Drag the item that you just selected 
4. See item jumping from grid to grid and not being able to place it in a precise place

**Expected behavior**  
Items that are being dragged with the selector should be able to placed anywhere at any precise location. 

**Console Output**  
```
maruf@maruf-pc:/~/ $ flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote
2024-09-11T10:29:37.802638Z DEBUG rnote: .. tracing subscriber initialized.
maruf@maruf-pc:/~/ $ 
```

**Screenshots**  

https://github.com/user-attachments/assets/333011b4-bc0c-4db7-90a2-77c7091a8698

**Desktop (please complete the following information):**  
 - OS: Fedora 40 Workstation 
 - App Version: 0.11.0
 - Installation Source: Flathub
 - Desktop Environment: Gnome 46
 - Display Server: Wayland
 - Input Source: Mouse and Pen (Dell Active Pen Wakom?)

**Additional context**  
Started happening since a couple of days ago so very recent. I noticed it on Monday.

**Comment by Doublonmousse** [comment]
Do you have `snap to grid` enabled ?

**Comment by mbeps** [comment]
I cannot see this option in the settings. Is it supposed to be somewhere else?

**Comment by Doublonmousse** [comment]
![image](https://github.com/user-attachments/assets/5f1a2d67-6744-4cb9-a18f-a98f0660bb95)
I'm talking about this option

**Comment by mbeps** [comment]
Thanks I never even seen that option before I will close this issue then it seems to have resolved it
