### ISSUE TITLE
Unable to select text using stylus

### ISSUE THREAD

**Issue by lokman2k5** [flxzt/rnote#1222]
**Describe the bug**  
Using the typewriter, trying to select text with stylus immediately undoes the selection when you lift the stylus away from the screen. It works completely fine with mouse.

.

**Screenshots**  

https://github.com/user-attachments/assets/96fac41a-0fbc-4db9-a403-f7f471fae21e

**Desktop (please complete the following information):**  
 I think you already know those lol but here it goes:
 - OS: Fedora 40
 - App Version: 0.11.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 46
 - Display Server: Wayland
 - Input Source: Onscreen tablet

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
