### ISSUE TITLE
Add an option to make the imported PDF replace the canvas

### ISSUE THREAD

**Issue by lokman2k5** [flxzt/rnote#1224]
**Please submit only one feature request in one issue!**  
Add an option when importing PDF files, to replace the canvas so that when using different tools like the selection tool, it shouldn't be selected instead of text or annotations

**Is your feature request related to a problem? Please describe.**  
Yes, see #1225

**Comment by Doublonmousse** [comment]
Also related #153

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by flxzt** [comment]
The `adjust document` option is meant to address this use case.

The remaining issue would be the sensitivity of the pages which is a different issue/topic. Please open a new issue for that.
