### ISSUE TITLE
Selection tool selects the PDF instead of annotations

### ISSUE THREAD

**Issue by lokman2k5** [flxzt/rnote#1225]
**Describe the bug**  
These are kind of many different bugs, I cannot predict their behavior because it is really strange. When importing a PDF, it is drawn on top of the canvas and that means it can be selected like anything else like an image, when trying to select some annotations on top of it (using the intersecting path tool) it selects the entire pdf page, sometimes the rectangle tool works for selecting only the annotations, but it sometimes moves the pdf page instead of selecting anything and you should go back to the draw tool and then back to the rectangle tool for it to go back to normal... It is really buggy and strange so I linked a recording below. I made a feature request that may solve this issue #1224 

https://github.com/user-attachments/assets/6c22a9ff-005b-4cc9-b9c6-72cf643ab9fa

As you can see the path tool does not even select the annotation but only the pdf page, only the rectangle works but the rectangle is buggy as well

**Comment by Doublonmousse** [comment]
The fourth selection tool selects element that intersect with the drawn path (and does not select what would be inside of the drawn shape).

So circling around an annotation won't select it, as it does not intersect. What you want is the first tool in the list (select element inside of the drawn shape)

**Comment by lokman2k5** [comment]
oh yeah right. i used to use a lot of annotation tools before rnote and some had a selection tool that circles around an object to select it. Is the rest of the behavior normal though?

**Comment by Doublonmousse** [comment]
Yes, selection for all tools (except the fourth one) only works if the element is fully inside.

There is no partial selection mode for now #155

**Comment by Doublonmousse** [comment]
There's not really a layer system or separation of selection between pdf elements and annotations (selects whatever is there regardless of type)

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Kneemund** [comment]
As Doublonmousse already explained, everything shown in the video is intended behavior. Feel free to open another issue if you have suggestions regarding the UX.
