### ISSUE TITLE
Visuals: Save button feels off

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#123]
Hi, 

I think visually the `Save` button feels off and it would be better looking to bring it vertically in line with the buttons below, see

![rnote](https://user-images.githubusercontent.com/36572014/155096442-b0112ab7-5967-4bd7-99e9-212536dcb916.png)

**Comment by flxzt** [comment]
https://github.com/flxzt/rnote/issues/90#issuecomment-1030713459

**Comment by Zuechti** [comment]
I would say even the fact that the save-button has a download-icon is really weird. (and the placement as well)

I would suggest the established design of many gnome apps, E.g. Gedit:

![image](https://user-images.githubusercontent.com/21462214/164486951-ae82c672-26ed-4c49-9231-67d7d707df57.png)

I love having a tool for notetaking in GTK4, but it would be even better if it fits the conventions seen in other GNOME apps
