### ISSUE TITLE
Proportional shapes

### ISSUE THREAD

**Issue by VodnikAngus** [flxzt/rnote#124]
Holding control should allow creation of circles instead of ellipses and squares instead of rectangles

**Comment by sei0o** [comment]
Hi, I'd like to work on this issue. Maybe `SelectionModifier` (`rnote-ui/src/selectionmodifier/mod.rs`) is the relevant one?

**Comment by flxzt** [comment]
Ok great! I think we make it a field in the `Shaper` struct, which handles the pen input. We could modify the shapes configuration popover to expose the setting as a toggle or a selectable list (meaning here:
![Bildschirmfoto vom 2022-03-23 08-39-17](https://user-images.githubusercontent.com/19841886/159647728-a9b484c8-40e1-40c1-a2ea-ccdb35475ed0.png) )


And maybe allow for some common aspect ratios, like `1:1, 3:2, golden ratio, etc`?

**Comment by sei0o** [comment]
So how do users switch whether to make their new shapes proportional or not? Some ideas:

- Another toggle in that popover
- Holding Ctrl or Shift while they drag to create squares and circles. Inkscape adopts this interface.

**Comment by flxzt** [comment]
I think both. Stylus / touch users would want a toggle for a permanent switch, mouse / keyboard users would want to hold down Ctrl. I think this would need a new variant in the `ShortcutKey` enum and maybe modifications to the `PenBehaviour` trait to be able to handle the key

**Comment by sei0o** [comment]
Makes sense. Thanks for the pointers!

**Comment by sei0o** [comment]
Just some progress (1:1):                 
![image](https://user-images.githubusercontent.com/5410901/160423012-65e91a2d-7a34-4a07-af80-1a22a5cb668a.png)
                                                                                                                                                                                                                                                                                                                                                                                                                                      
It's going to take a bit longer while I try to wrap my head around `ShortcutKey`.

**Comment by flxzt** [comment]
I hope I didn't ruin your progress completely with the latest commits (the splitting into rnote-compose, refactor of the pens and how they handle input events). I do believe how things are handled now should make it easier to implement it, however. If you want, you could also make a draft PR.
