### ISSUE TITLE
.svg <svg> tag nesting incompatibilities

### ISSUE THREAD

**Issue by acrilique** [flxzt/rnote#1252]
I want to use .svg files exported by rnote in a Qt6 GUI app that I'm developing. The fact that the exported .svg file has 2 nested \<svg\> elements makes QtSvgRenderer skip the inner \<svg\> element. Qt logs the following:
```
qt.svg: Skipping a nested svg element, because SVG Document must not contain nested svg elements in Svg Tiny 1.2
```
This can be worked around by editing the .svg file by hand and changing the inner \<svg\> tag to just \<g\>. However, this does not seem like a friendly way of doing it. 

It would be great to have a button or switch on the Export menu that allowed to export without \<svg\> nesting. You could also display a warning like "This .svg file might not be compatible with all svg parsers. Choose the option X to disable nesting."

Another solution would be to disable nesting by default, but I don't really know if there's some benefit in it being enabled so I'll leave that to the developers opinion.

Thanks for making/mantaining such a cool app!

**Comment by Doublonmousse** [comment]
Seing ` Svg Tiny 1.2` in the error message, I think you're trying to open a SVG 1 or 2 file with a Svg Tiny 1.2 svg parser (smaller subset of the SVG standard).

Chances are we're targeting SVG 1 or 2 but not Svg Tiny 1.2.

**Comment by acrilique** [comment]
It's weird because I'm using the latest Qt6 version available and, according to [this documentation](https://doc.qt.io/qt-6/qtsvg.html#Option-enum) their SvgRenderer does support more features than just Svg Tiny 1.2... Maybe it's just that nesting is still not supported overall in Qt6 and they should make that more clear in their error message (i.e. not saying it's just because it doesn't comply with Svg Tiny 1.2). 
Anyway, thanks for the answer, I'll probably bring this up as an issue to Qt.
