### ISSUE TITLE
Implement an "inferred shape" pen, or "smart pen"

### ISSUE THREAD

**Issue by MMachado05** [flxzt/rnote#1254]
## Is your feature request related to a problem? Please describe  
I find myself wanting to create a variety of shapes as I'm writing notes. Perhaps I want to circle a piece of text, or draw some lines to separate ideas, or create arrows between various points. Having to go between my normal brush tool to the shape tool, and then to select the specific shape I have in mind, can introduce a lot of friction in my workflow.

## Describe the solution you'd like
A new type of brush, perhaps called a "smart brush" or something similar, could be implemented such that it changes the shape of the stroke created based on what the user "likely" wanted the brush shape to look like, potentially alleviating the need to switch between the Shape and Brush tool options. That, or it could be a setting toggled from one of the other brushes, like "simple" or "modeled."

The reason I mention that last point is that I think the "inference" step, which replaces the created stroke with a new shape, should be undoable in the case that the user disagrees (or simply *didn't want*) what is created. For example, say I draw a mildly curved line and the pen infers a straight one; I would want to be able to undo that inference and return the stroke to the intended shape. However, I would want it to look the way it would according to the stroke preset I've selected (simple, modeled, curved).

Here are some screenshots of what I think this could look like in practice, with the three primary functions implemented:

### Square inference
![image](https://github.com/user-attachments/assets/0c497394-42cd-4e4a-8354-db32c95d897a)

### Ellipsis inference
![image](https://github.com/user-attachments/assets/fb3c5c81-a82d-450f-babe-1ecc0f89a6a9)

### Arrow inference
![image](https://github.com/user-attachments/assets/a1fe925d-c828-41d5-b3e6-f7e6e932c1b5)

**Describe alternatives you've considered**  
The current multiple-tool option *works*, and in a pinch, going analog and just drawing some imperfect shapes and lines is fine.

**Additional context**  
This is inspired by a similar functionality I saw in a professor's note-taking program, which he uses to annotate during lectures. It seemed very useful in terms of leaving the workflow uninterrupted.

**Comment by RayJW** [comment]
This is likely another duplicate of #384 and #120.

**Comment by MMachado05** [comment]
Yipes, it is certainly a duplicate of #120! I must've missed it in my search. Closing now!
