### ISSUE TITLE
Color picking not selecting correctly

### ISSUE THREAD

**Issue by francescospangaro** [flxzt/rnote#1255]
Having selected the last color on the color picker popup, if we try to select the third to last one both are selected.

1. Select the last color
2. Select the third to last color
3. Now both are selected

Expected behavior:
The third to last color is the only one selected after having selected it last.

Video description:

https://github.com/user-attachments/assets/fa9a24f4-d507-406a-bdb5-6fe692c53bb1

Setup:
 - OS: Linux Mint 22 Cinnamon version 6.2.9 - kernel 6.8.0-45-generic
 - App Version: Rnote v0.11.0
 - Installation Source: Flatpak
 - Display Server: X11
 - Input Source: Wacom one medium

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Kneemund** [comment]
Wow, you found the *exact and single* combination of selecting and deselecting colors that triggers this bug :D
