### ISSUE TITLE
Palm rejection

### ISSUE THREAD

**Issue by maxanthem** [flxzt/rnote#1256]
**Context**
I am using Rnote on a Surface like tablet (Windows 11).

**Related problem**
As soon as I start to write and the tip leaves the surface of the tablet, some crazy behavior can happen (resizing the windows, scrolling, ...). I highly suspect the palm rejection to be faulty. As a left handed person, this can also mess with the pen menu (which I would love to be able to put on the right, by the way, but that could be for another feature request)

**Request**
Would there be a way to implement a palm rejection feature: as soon as the pen is close to the screen and as long as the pen is close to the screen (not necessarily touching), +some delay time -> the touchscreen should be ignored.

**Alternative**
Adding a button to toggle touchscreen, maybe?

Thanks in advance, that'd be great for me to use this amazing app on my other computer tablet!

**Comment by astro-ray** [comment]
> As a left handed person, this can also mess with the pen menu (which I would love to be able to put on the right, by the way, but that could be for another feature request)

Just so you know, the pen menu can be moved from left to right.
![Screenshot from 2024-10-18 09-59-39](https://github.com/user-attachments/assets/b01194d3-0b71-4283-9fa6-132f1f28defd)
![image](https://github.com/user-attachments/assets/3774d0d5-556f-4233-84f5-3f218a605d78)

This menu is where you change it (assuming this is what you are asking),
![Screenshot from 2024-10-18 10-06-13](https://github.com/user-attachments/assets/44ad831c-f0d8-4fef-81d8-51ab27abe204)

**Comment by maxanthem** [comment]
Savior! Thanks a lot for the example (nice physics) and explanation! I wasn't familiar with this icon :)

I have the overall impression that Rnote has been developed with Wacom users in mind? Computer tablets are less of a thing in the open source community, I feel (and for good reasons, I guess). I actually have a Galaxy Book 10.6 (about 8 years old, same format as Surface Go, with intel m3 core) and my dream would be to install a Linux distro on it :)

I also have a Wacom in my office and for this Rnote is great! But I still struggle to take notes on it: I'm way slower than with pen & paper or tablet.

**Comment by Doublonmousse** [comment]
On windows 11, there's a toggle in the pen settings 'Ignore touch input when I’m using my pen'.

Check if it's toggled on and if not, maybe it would fix it

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by maxanthem** [comment]
Thank you for your help: much appreciated, I will try, this sounds promising!

**Comment by maxanthem** [comment]
I tested this option, it works great! Thank you very much! It seems that other apps like OneNote can bypass this parameter and apply it anyway. But good to know it is possible to implement it on the whole system

**Comment by maxanthem** [comment]
I tested this option, it works great! Thank you very much! It seems that other apps like OneNote can bypass this parameter and apply it anyway. But good to know it is possible to implement it on the whole system
