### ISSUE TITLE
File browser is stuck at non existent path after deleting the last used working directory

### ISSUE THREAD

**Issue by kq98** [flxzt/rnote#1259]
When the working directory Rnote was last used in is deleted, the Rnote file browser will be stuck on the old, now no longer existing path unable to navigate to a different folder.

A workaround is to recreate the folder structure that was present when Rnote was terminated.

**To Reproduce**  
1. Create some folder 
2. Navigate into that folder in Rnote
3. Quit Rnote
4. Remove the folder
5. Start Rnote again

**Expected behavior**  
Rnote should detect that the last working directory no longer exists and default to some other location, perhaps the users home directory.

**Desktop (please complete the following information):**  
 - OS: Fedora 40 Silverblue
 - App Version: Rnote v0.11.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 46
 - Display Server: Wayland

**Comment by flxzt** [comment]
The app should walk back up until it finds an existing directory, agreed.

**Comment by flxzt** [comment]
Note that you can always pick a different workspace directory in the edit workspace window.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by flxzt** [comment]
should be fixed.
