### ISSUE TITLE
Transparent toolbox background

### ISSUE THREAD

**Issue by tonitch** [flxzt/rnote#1264]
**Describe the bug**  

I have this problem specifically on my desktop and not on my laptop I assume this is something related to my qt  or gtk config but I don't really know how to solve it.

Basically, the background of all toolbox is transparent. this makes it hard to select tools when the thing I'm working on is the same color 

**Expected behaviour**  
Either a theme bypass that would force a default theme or a high contrast or a button to put back the toolbox background

**Screenshots**  
![2024-10-25-111000_1920x1080_scrot](https://github.com/user-attachments/assets/6db58d78-9ae1-4443-ad75-78b02e3c88b3)

**Desktop :**  
 - OS: Archlinux
 - App Version: 0.11.0
 - Installation Source: Archlinux User Repo
 - Desktop Environment: bspwm
 - Display Server: X11
 - Input Source: Mouse and Keyboard, On-Screen-Tablet, External Graphics Tablet (a bit of all but certainly irrelevant)

**Additional context**  
This is not happening on my laptop

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by flxzt** [comment]
this looks like a theming issue so it's likely that using the default adwaita theme (unsetting `GTK_THEME`) will fix the issue.

**Comment by KaKi87** [comment]
Hi,

> (unsetting `GTK_THEME`) will fix the issue.

How to do that ?

Thanks

**Comment by tonitch** [comment]
you can either type `unset GTK_THEME` before running `rnote` in your terminal

or you can `GTK_THEME='' rnote` in one command

**Comment by KaKi87** [comment]
How to do this with the Flatpak version ?

Thanks
