### ISSUE TITLE
Implement Ctrl+Y to redo.

### ISSUE THREAD

**Issue by MubinMuhammad** [flxzt/rnote#1265]
Today, most programs support Ctrl+Y to redo the thing you did. It makes it easier to redo instead of pressing the arrows. Because most of the time the cursor is on the board and a keyboard shortcut would help.

Thanks.

**Comment by MubinMuhammad** [comment]
Thanks, but normal apps are different than Rnote. So preferably, Ctrl+Y should also be an option.

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by RayJW** [comment]
> Thanks, but normal apps are different than Rnote. So preferably, Ctrl+Y should also be an option.

I think normal apps is the wrong word here. There are a lot of apps that use `Ctrl + Shift + Z` for redo, especially in the creative space. Either way, this should probably be closed as a duplicate of #590.

**Comment by flxzt** [comment]
yes, I agree.
