### ISSUE TITLE
Add Dynamic Stroke Thickness

### ISSUE THREAD

**Issue by mahdi4260-1** [flxzt/rnote#1275]
**Description**

This feature would allow the stroke thickness to adjust based on the zoom level, ensuring that the strokes maintain a consistent appearance relative to the display.

**Benefits**

-  Users can zoom in and out without losing the visual consistency of their strokes, making it easier to work on detailed sections of their notes or drawings.

-  This could be particularly beneficial for users who frequently switch between different zoom levels while working.

**Comment by flxzt** [comment]
I am not sure if this is in line with how we want documents to work. Ultimately the thickness should be an absolute value, otherwise it would be very hard to create consistent looking handwriting.
Closing as not planned.
