### ISSUE TITLE
CLI for rendering .rnote files to images

### ISSUE THREAD

**Issue by petoknm** [flxzt/rnote#1295]
I like using rnote for drawings but I use markdown files for the rest of my note taking. In order to improve this workflow, I would like to be able to convert/render .rnote files into images without using the GUI.

Workflow example:
 - write markdown notes (in vscode, with preview)
 - need to draw something, open rnote, draw, save as .rnote file
 - run script to automatically render rnotes into images
   - planning to use GNU Make for this which would automatically check for input/output timestamps to only rerender .rnote files that need to be rerendered. (have a newer timestamp than the associated output image) (just trying to say here that the CLI does not have to be super high performance or anything)
   - this script could be easily hooked up to my editor (vscode) to make this super easy to invoke whenever I want to, or automatically in some fashion (watching for file changes in .rnote files)
 - embed new image into markdown and have it displayed in the preview together with the rest of my markdown notes

Example proposal:

```sh
> rnote render --help
Usage:
  rnote render [OPTION...]

Render Options:
  -i, --input=INPUT    Input file to render (.rnote)
  -o, --output=OUTPUT  Output file (.svg) # png export would be nice but as a separate feature
  --shrink-to-content  Render the smallest image that fits all the content
```

Alternatives considered:
 - I tried to unzip the content of an .rnote file an it contains nicely structured JSON but I am not aware of any application that could consume this either directly or through some extra modifications, so that would be more involved, but still possible. I think this would still be a nice feature for rnote in general, currently the CLI is a bit too simple :)

I am probably going to start working on adding this feature myself, but I wanted to approach you first to check if this contribution would be welcome upstream.

**Comment by petoknm** [comment]
Ok, looking at the code, it seems like we already have a CLI its just not being packaged by my distro (Manjaro/AUR).
I will create a new build recipe that includes the CLI.

**Comment by petoknm** [comment]
I think my usecase is covered by:
```sh
> rnote-cli export selection -o out.svg all example.rnote
```

**Comment by mahdi4260-1** [comment]
> I think my usecase is covered by:
> 
> ```shell
> > rnote-cli export selection -o out.svg all example.rnote
> ```

@petoknm How did you run that command? Where did you find `rnote-cli`?

**Comment by Kneemund** [comment]
Are you using the `rnote-git` PKGBUILD from the AUR? The `rnote` package in the `extra` Arch repository includes the CLI.

**Comment by petoknm** [comment]
This is how I modified the rnote-git PKGBUILD: https://gitlab.com/petoknm/rnote-git/-/commit/984890df8d6853e68a41341f07a1e2de64e36483

The bit relevant for this discussion is:
```patch
- arch-meson "${pkgname%-git}" build
+ arch-meson -D cli=true "${pkgname%-git}" build
```
