### ISSUE TITLE
Respect CWD when saving a file

### ISSUE THREAD

**Issue by petoknm** [flxzt/rnote#1296]
When using rnote from the cmdline, I expect that the default save path will be the current working directory (CWD) but currently that is not the case.

1. Open terminal, change to some directory and run `rnote`
2. Click "Save Document" button
3. Observe the save dialog's directory that you are presented with

Expected result: The save dialog was opened at the CWD

Actual result: The save dialog was opened at $HOME

 - OS: Manjaro
 - App Version: 7f3ff8aafcaf3137bec9993329667e5e9fbf4c4e
 - Installation Source: AUR
 - Desktop Environment: Gnome 46
 - Display Server: Wayland
 - Input Source: Mouse and Keyboard, External Graphics Tablet

I applied a patch to my local rnote build that can "fix" this but it interferes with some existing functionality so a proper fix is needed. The expression `appwindow.sidebar().workspacebrowser().dir_list_dir()` evaluated to the Some variant so I could not just add `.unwrap_or()`.

my patch:
```patch
diff --git a/crates/rnote-ui/src/dialogs/export.rs b/crates/rnote-ui/src/dialogs/export.rs
index ab938b3e..41f7ae1d 100644
--- a/crates/rnote-ui/src/dialogs/export.rs
+++ b/crates/rnote-ui/src/dialogs/export.rs
@@ -49,9 +49,7 @@ pub(crate) async fn dialog_save_doc_as(appwindow: &RnAppWindow, canvas: &RnCanva
     if let Some(output_file) = canvas.output_file() {
         filedialog.set_initial_file(Some(&output_file));
     } else {
-        if let Some(current_workspace_dir) = appwindow.sidebar().workspacebrowser().dir_list_dir() {
-            filedialog.set_initial_folder(Some(&gio::File::for_path(current_workspace_dir)));
-        }
+        filedialog.set_initial_folder(Some(&gio::File::for_path(glib::current_dir())));
 
         let file_name = canvas.doc_title_display() + ".rnote";
         filedialog.set_initial_name(Some(&file_name));
```

**Comment by Kneemund** [comment]
This is expected behavior and part of the workspace feature/intended workflow. I don't think that this should/will be changed. The best we could do is adding an option to disable this behavior.

**Comment by Doublonmousse** [comment]
I think #797 would be the way to fix this correctly.

**Comment by flxzt** [comment]
Yeah I'd say this is not planned.
