### ISSUE TITLE
Feature Request: Toggle for Automatic Hiding of Colour Picker

### ISSUE THREAD

**Issue by tunjan** [flxzt/rnote#1298]
**Problem Description**

I've noticed that the constantly visible color brush picker can sometimes clutter the whiteboard interface. For those who prefer a minimalist workspace, this persistent element can be distracting when not actively in use.

**Proposed Solution**

To address this, I propose introducing a toggle in the settings menu to enable or disable automatic hiding of the color brush picker. When enabled, the picker would remain hidden by default and appear only when the user hovers over its designated area. This dynamic visibility would optimize screen space while ensuring quick access when needed.

**Additional Context**

This toggle would provide more granular control over the interface, catering to users who prioritize a clean workspace as well as those who require constant access to drawing tools.

**Comment by astro-ray** [comment]
Just asking, but for a minimalistic look, can't you just use the focus mode?

**Comment by tunjan** [comment]
> Just asking, but for a minimalistic look, can't you just use the focus mode?

Thank you @astro-ray , I had not realised this button existed. How foolish of me.
