### ISSUE TITLE
tooltips sometimes render incorrectly

### ISSUE THREAD

**Issue by MythicByte** [flxzt/rnote#1302]
When hover over a button the text icon explaning it, has the wrong size. Some Times it works right sometimes comes something funny.

![image](https://github.com/user-attachments/assets/41e01b7d-ad0e-4e7b-845b-74b27817b68b)

[Screencast From 2024-11-20 14-36-31.webm](https://github.com/user-attachments/assets/552198bb-6a08-47d1-a29d-27c28ff5446c)

**Expected behavior**  
the text in a normal format

flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote
2024-11-20T13:33:23.429085Z DEBUG rnote: .. tracing subscriber initialized.

Fedora Linux 41 (Workstation Edition) (up to date)  
Rnote 0.11.0 
my monitor has the correct ratio 1920 *  1080

**Comment by JanDeDinoMan** [comment]
This is https://gitlab.gnome.org/GNOME/gtk/-/issues/5832. This is fixed by GTK 4.16 as it switches to Vulkan by default

**Comment by MythicByte** [comment]
@JanDeDinoMan It looks like it's fixed and should be in the next version. Thanks for bringing this up!

**Comment by Doublonmousse** [comment]
Well, since #1061 we are forcing the use of the old `gl` renderer. 

We may reconsider this on gtk 4.16, but only if #1061 is fixed on the vulkan renderer.
