### ISSUE TITLE
Pasted content always appears in the top-left corner instead of at the cursor position

### ISSUE THREAD

**Issue by tunjan** [flxzt/rnote#1304]
When pasting content (such as an image, text, or other elements) into the whiteboard, the pasted item consistently appears in the top-left corner of the document page. This behaviour can be unintuitive and disrupts the workflow, as users must manually reposition the content after pasting.

It would be more user-friendly for pasted content to appear at the location of the cursor, which aligns with user expectations in many other applications.

**Comment by flxzt** [comment]
Which method of pasting content are you referring to? with keyboard `ctrl-v` ?

**Comment by tunjan** [comment]
> Which method of pasting content are you referring to? with keyboard `ctrl-v` ?

Yes

**Comment by FroznAnna** [comment]
yess i also get this. Is there meant to be another method of pasting since I cant seem to right click int he document
