### ISSUE TITLE
Stylus Button: Click vs Hover

### ISSUE THREAD

**Issue by Leon0402** [flxzt/rnote#132]
Some tools that can be configured via button click are activated by hovering and some by additional clicking. 

The normal mode (not using button shortcuts) is always the same: It's always the same cursor and the tool will only do something if you actually click 

With button shortcut it's different: 
- Brush Style: Cursor is smaller, draws on click (drawing seems to be the same size though still)
- Shaper Style: Cursor is smaller, draws on hover 
- Eraser Style: Cursor smaller & Eraser symbol appears, erases on click
- Selector Style: Cursor smaller, selects on click 
- Tools Style: Cursor smaller & tool symbol appears, works on click

This means:
- In General the cursor is always smaller
- Shaper draws on hover, which is completly weird 
- Eraser & Tools initally show the symbol on pressing the button, which normally only appears on clicking. I think I would in general like if the symbols would always appear on hover to give better guides (and also follow the pen hover obviously). But as it is now it's not useful and inconsistent

**Comment by flxzt** [comment]
This should be fixed too. All button presses can now be done already while hovering, without actually starting the pen. The cursor  inconsistency should also be fixed, so that is is only small when the pen is actually pressed, and change back to the large on pen release.
