### ISSUE TITLE
Support config file.

### ISSUE THREAD

**Issue by xcccdjsn** [flxzt/rnote#1338]
# os

nixos

# desc

I have to configure something like pen size, tool for pen button, pen color etc every time I reuse it.

Is there any way to solve it?

**Comment by flxzt** [comment]
Please use the bug report or feature request templates. I can't tell what you're requesting.

**Comment by xcccdjsn** [comment]
> Please use the bug report or feature request template. I can't tell what you're requesting.

I'm sorry, I resubmitted an issue.
