### ISSUE TITLE
mirror the behaviour of the "Eraser" mode of styluses to the "Pen" mode

### ISSUE THREAD

**Issue by senntore** [flxzt/rnote#136]
**Please submit only one feature request in one issue!**

**Is your feature request related to a problem? Please describe.**
I prefer using eraser side of my wacom pen as brush when not putting delicate marks & also to save on the cost of  buying new nibs. But rnote allows to only use it as an eraser, rather than tools of our choice.

**Describe the solution you'd like**
I like how Krita handles it, we should be able to select whichever tool we prefer with both side & the tools should be switched automatically when switching the side of the pen. 

**Describe alternatives you've considered**
Mentioned above

**Additional context**

**Comment by flxzt** [comment]
Did you upgrade to v0.4.0? It added reconfigurable button actions in the settings side panel.

**Comment by senntore** [comment]
Yeah I missed that, tested it just now & the implementation is quite different as it doesn't allow freely selecting other tools(like you can do with mouse/pen) or even just switching between eraser and brush tool, for doing that we've to open side menu. But yeah my issue is gone, at-least somewhat, so closing this.
Thanks for the quick reply!

**Comment by flxzt** [comment]
Oh, are you referring to the pen selector overlay tool from krita?
Or that the pen page is changed as soon as a button/ the eraser side is pressed ? Because this tweak in behaviour is already in master, and will be in the next release

**Comment by senntore** [comment]
No, I meant being able to freely select & use different tool with the eraser side(just from the toolbar).
Right now in 0.4, we can **set** eraser side as brush( & other tools like shapes) from side panel. If we were to now select eraser or other tools from toolbar above, it will not switch to that other tool like it does with mouse/brush side of pen.
I think this happens because eraser side is implemented here like the primary & secondary buttons of the pen instead of brush side of the pen(I'm not sure it's the right word).
In other apps like Krita & MyPaint, the eraser side defaults to eraser tool but is same as the brush side of the pen. You can do all of the same stuffs with both sides of the pen.
Sorry if it's confusing.

**Comment by flxzt** [comment]
Ohh, I think I understand you now. Because the eraser side is mapped to a button on my pen and having never used any other, I thought it should behave like one. Let me see if I can make a improvement to it.

**Comment by flxzt** [comment]
should be fixed with v0.5.2, please let me know how it works for you.

**Comment by senntore** [comment]
Yes it works. Thanks for working on this!
