### ISSUE TITLE
Can't open old rnote saves

### ISSUE THREAD

**Issue by Mr-EmPee** [flxzt/rnote#137]
Heya, I'm unable to open some saves of the previous version with rnote.
When I try to open any of these two files, it opens a new document.

Attachments:
 - [File 1](https://mega.nz/file/hocwiTQa#XyrcXoYgv5UDF01KYNgDsTUYwKz4_dImElb49P5wgFs)
 - [File 2](https://mega.nz/file/d0tUiIIB#n0KqnRSNB0kB7GJTKpzdGk4lYKMNM-mRZAQ8grIs9LM)

P.S. If I try to save and open a new file, it works fine.

**Comment by Mr-EmPee** [comment]
I've just seen that the 4.0 update breaks file formats

**Comment by flxzt** [comment]
sorry about that. I'll try to stabilize the file format soon.

**Comment by Mr-EmPee** [comment]
Not a problem, you are doing already a great job 👍🏼
