### ISSUE TITLE
[Improvement] More shortcuts

### ISSUE THREAD

**Issue by Domant3lis** [flxzt/rnote#14]
Currently, `ctrl+z` (Undo) and `ctrl+shift+z` (Redo) are missing, having them would be a huge usability improvement.

Also, it's standard for GNOME applications (and some non-GNOME applications) to quit when pressing `ctrl+q` (close all open instances). `ctrl+w` is also used for closing tabs or if only one tab is open then closing active window.

`ctrl+q` example:
![q](https://user-images.githubusercontent.com/49041398/138419751-a22ed53c-dcfb-44c6-abc6-3ebab2b16996.gif)

`ctrl+w` example:
![w](https://user-images.githubusercontent.com/49041398/138419725-22c2c81d-4fed-4096-93e0-f02245408a65.gif)

**Comment by flxzt** [comment]
is implemented in v0.1.6 (<ctrl> + w is closing the active window, as Rnote does not have tabs currently).
