### ISSUE TITLE
[Crash] Crash on rotation / writing

### ISSUE THREAD

**Issue by Doomsdayrs** [flxzt/rnote#141]
This will cause RNote to crash no matter what I try.

I can't get any logs. It just dies.

[2022-03-28_11-31-58_sheet.rnote.txt](https://github.com/flxzt/rnote/files/8364413/2022-03-28_11-31-58_sheet.rnote.txt)

**Comment by flxzt** [comment]
When you try to rotate everything? Can you be a little more specific?

**Comment by Doomsdayrs** [comment]
It seems to not occur anymore.

But I do have frequent issues with the application crashing out of nowhere when I am writing on the screen.

**Comment by Doomsdayrs** [comment]
[Screencast from 04-28-2022 01:44:38 PM.webm.txt](https://github.com/flxzt/rnote/files/8585185/Screencast.from.04-28-2022.01.44.38.PM.webm.txt)

**Comment by flxzt** [comment]
can you run with `RUST_LOG=debug flatpak run com.github.flxzt.rnote` and paste the log here?

**Comment by Doomsdayrs** [comment]
> can you run with `RUST_LOG=debug flatpak run com.github.flxzt.rnote` and paste the log here?

Nothing outputs

**Comment by Doomsdayrs** [comment]
> can you run with `RUST_LOG=debug flatpak run com.github.flxzt.rnote` and paste the log here?

I compiled it myself and here is a video since I can't redirect the output
[Screencast from 04-28-2022 02:59:14 PM.webm.txt](https://github.com/flxzt/rnote/files/8585611/Screencast.from.04-28-2022.02.59.14.PM.webm.txt)

**Comment by flxzt** [comment]
Hm, a segfault should never happen. Is this still happening with v0.5.1? (the internals regarding rendering and selections in the newest version changed quite a bit )

**Comment by flxzt** [comment]
I would love to fix this, but I can't really replicate on the newest version ( v0.5.4-beta2 on flathub)
