### ISSUE TITLE
Automatic dark mode does not work

### ISSUE THREAD

**Issue by WhyNotHugo** [flxzt/rnote#144]
**Describe the bug**

When automatic dark mode is enabled, rnote does not change modes when a mode-change happens.

It _does_ respect the change if closed and opened again.

**To Reproduce**

I'm using darkman to handle dark mode. It implements the XDG desktop portal API for dark/light mode preference, and the portal picks this up:

```
‣ Type=signal  Endian=l  Flags=0  Version=1 Cookie=5  Timestamp="Wed 2022-04-06 10:14:50.200037 UTC"
  Sender=:1.115  Path=/org/freedesktop/portal/desktop  Interface=org.freedesktop.portal.Settings  Member=SettingChanged
  UniqueName=:1.115
  MESSAGE "ssv" {
          STRING "org.freedesktop.appearance";
          STRING "color-scheme";
          VARIANT "u" {
                  UINT32 1;
          };
  };
```

Other GTK applications seem to pick this up fine (e.g.: Firefox). Querying the mode via the D-Bus API returns the correct value.

**Expected behavior**

Dark mode transitions should happen immediately.

**Console Output**

No output with  `flatpak run com.github.flxzt.rnote` nor `flatpak run --verbose com.github.flxzt.rnote`

**Screenshots**

Nothing special, render always in the same mode it rendered at startup.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **ArchLinux**
 - Version [e.g. 22] **0.4.0**
 - Installation source [e.g. Flatpak, Archlinux Community Repo, ... ] **Flatpak**
 - Desktop Environment [e.g. Gnome 41.2] **swaywm** (wayland compositor)

**Additional context**

**Comment by flxzt** [comment]
That is odd, on fedora 36 with Gnome the color theme switches instantly, also in an Elementary OS 6.1 VM.

**Comment by WhyNotHugo** [comment]
What mechanism are you relying on to detect the current mode?  Is this via the `org.freedesktop.appearance color-scheme` setting expose by the xdg-desktop-portal?

This is the API that was basically define by the GNOME and Elementary teams.

Relevant:
- https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
- https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Settings

**Comment by WhyNotHugo** [comment]
Do you have any hints on how to debug his better? I'm noticing that other GTK applications (e.g.: Fractal) switch modes immediately.

**Comment by flxzt** [comment]
The property to look out for is `color-scheme` in the style-manager of the appwindow. see here:
![Bildschirmfoto vom 2022-04-15 19-39-20](https://user-images.githubusercontent.com/19841886/163603056-f8d4d422-67a8-46c0-b81e-ee54f57f8e3a.png)


Another user had some great hints for a similar issue, see #122.

I wish I could help here, but I tested it in a manjaro VM as well, both with release and dev builds, and can't replicate it :/

**Comment by WhyNotHugo** [comment]
Useful info on that issue. Inspecting the output of `flatpak run --command=dbus-monitor com.github.flxzt.rnote --session`, helped me figure out that when toggling the dark mode preference, the signal was **not** triggering inside the flatpak sandbox.

This eventually helped me figure out that the way the signal was being emitted was not 100% correct, but the issue was in `darkman` itself, not `rnote`. Many other applications worked... by coincidence.

Sorry for the noise and helps for the pointers!

**Comment by flxzt** [comment]
No worries, glad I could help!
