### ISSUE TITLE
Conflicts on saves with two open documents.

### ISSUE THREAD

**Issue by CodedOre** [flxzt/rnote#145]
**Describe the bug**
When you have two documents open in two windows, the save action will save one document to both paths, no matter where you attempt to save.

**To Reproduce**
1. Open two existing documents in two windows.
2. Make some change to the documents.
3. Click `Save` in the three-dot menu on both documents
4. Close both documents
5. Open both again

**Current behaviour**
Both documents have the same content.

**Expected behavior**
Both documents should contain the changes made to their respective files.

**Enviroment**
 - OS: Fedora Silverblue 35
 - Version: 0.4.0
 - Installation source: Flatpak
 - Desktop Environment: Gnome 41.5

**Comment by flxzt** [comment]
should be fixed, thanks for reporting!
