### ISSUE TITLE
Tags shouldn't be changed

### ISSUE THREAD

**Issue by dotlambda** [flxzt/rnote#156]
For distributions it's a huge issue if the commit a tag points to is changed. It would be better to have published e.g. 0.5.1 instead of 0.5.0-hotfix-1.

**Comment by flxzt** [comment]
I didn't even realize Rnote is packaged for distributions. I am creating new tags for the hotfixes though. Or are you saying I should just stick to SemVer without the suffix even for hotfixes to always have an incrementing version number?

**Comment by dotlambda** [comment]
> I didn't even realize Rnote is packaged for distributions.

It's currently packaged in the AUR, for Arch Linux ARM, and in Nixpkgs: https://repology.org/project/rnote/versions

> I am creating new tags for the hotfixes though.

Oh true. Never mind then. It's only the release that is being changed :+1:

**Comment by flxzt** [comment]
to be fair, I did that in the past, but soon realized that it is bad practice. Anyways, thanks for packaging the app. :)

**Comment by dotlambda** [comment]
Maybe semver would actually be better so distributions agree on what version their package is on: https://repology.org/project/rnote/versions

**Comment by flxzt** [comment]
okay, will do.
