### ISSUE TITLE
Map one of the stylus buttons to Middle Mouse Button. 

### ISSUE THREAD

**Issue by 1ncend1ary** [flxzt/rnote#157]
**Is your feature request related to a problem? Please describe.**

I am using a Wacom Tablet and Rnote flathub, 0.4.0-1, and there are two buttons on my stylus. In my desktop environment I have them both mapped to Middle Mouse Button for easy scrolling of canvas. However, Rnote overrides these settings and I can't scroll the canvas anymore.

**Describe the solution you'd like**
I'd like there to be an option (in the drop-down menu from the screenshot) to map the stylus buttons to Middle Mouse Button. 
![image](https://user-images.githubusercontent.com/45948348/167120025-8d1c255a-543a-4614-b552-bba4c9ce3a79.png)

**Describe alternatives you've considered**
One alternative would be to completely stop Rnote from overriding said stylus button. I also think that I've seen a similar issue here, but don't consider this one a duplicate, because you wanted to implement a whole remapping system, and I only want one button.

**Additional context**
I would consider moving the canvas around using a stylus button a sensible default.

**Comment by flxzt** [comment]
You could set your button shortcut to the tools page, where there is a tool to move the canvas around.

**Comment by 1ncend1ary** [comment]
I only see 2 tools: 
![image](https://user-images.githubusercontent.com/45948348/167138179-0b512b35-83e1-42e7-b66b-620de1b647f6.png)

Does one of them move the canvas around or is the 3rd tool removed because it's broken atm?

**Comment by 1ncend1ary** [comment]
Oh, I now see [2aa5cbc](https://github.com/flxzt/rnote/commit/2aa5cbc6bc13d4cc3c6597d575a5a12f54cb77a8)

**Comment by flxzt** [comment]
Check out the latest (v0.5.0) flatpak package, this should have the move tool, which is fixed

**Comment by 1ncend1ary** [comment]
Thank you! The tool now works and my issue is resolved!

Also thank you for the great work!
