### ISSUE TITLE
Enhancement: Support for smaller screen sizes

### ISSUE THREAD

**Issue by giannissc** [flxzt/rnote#16]
I have tried the app on my laptop (15") and the app doesn't fit the screen. Maximise doesn't seem to work and I can resize the height of the application either. The application is fine when I connect my screen (25")

**Comment by giannissc** [comment]
Maybe there are some minimum window dimensions that are not honored by my laptop?

**Comment by flxzt** [comment]
I measured the minimum size: 929x959px so everything above that (+ vertical space for taskbars) should be fine. I think I'll use this issue to track support for smaller screen sizes.

**Comment by giannissc** [comment]
I found that a temporary solution to my problem was to lower the screen resolution from 3200×1800 to 1920×1080

**Comment by flxzt** [comment]
okay, I assume you had the scaling factor set to 200%?  
![image](https://user-images.githubusercontent.com/19841886/143464497-66f56bf5-d27b-4710-b173-6220efe2bb5b.png)
 You could also set that to a lower value to avoid changing the screen resolution.

**Comment by user82622** [comment]
**Surface Go window to High**
Would really love to use Rnote on the Surface Go, but on a normal scaling factor ( 1800 x 1200 at 170%) the window is to high to fit on the screen, i don't see any reason why it the minimum height on 100% scaling has to be 929px. As far as i understand you don't have to put a lot of effort into a GTK4 app to adapt properly, for example the workspace/settings sidebar is already perfectly responsive if the width is on 929px it is sliding over the drawing area if it is big enough it displays right next to it and you don't have to collapse it to draw. 

But thanks a lot for your efforts of making a modern journal++ alternative :)

![1800x1200](https://user-images.githubusercontent.com/88026138/144726443-46903948-08aa-4ab6-97da-307f1d8e6f9a.png)

**Comment by maymage** [comment]
For inspiration here is what gnome-weather does 

![Kooha-01-22-2022-10-51-35](https://user-images.githubusercontent.com/36572014/150633719-2c61ff9f-36ac-4196-a27a-4c307b3177f9.gif)

That would probably mean 

* moving the shape selection pane in the header bar to a bottom bar
* inverting the ordering of the elements in the side panel

**Comment by flxzt** [comment]
Look at #54 for the implemented improvements. Closing this in favor for it, lets have the discussion there!
