### ISSUE TITLE
Make page boundary less disturbing

### ISSUE THREAD

**Issue by msvana** [flxzt/rnote#161]
I really like the _Infinite expand mode_ feature as I often draw complex diagrams and even use Rnote as a virtual whiteboard for online teaching. But the dark red page boundary can be quite disturbing in such scenarios. Would it be possible to either make the page boundary less noticable or add the option to change the color to the _Settings_ panel?

**Comment by flxzt** [comment]
Good idea! Made them a little thinner, and the color is now customizable.
