### ISSUE TITLE
Moving "offset the camera by draging" to the front

### ISSUE THREAD

**Issue by tonilxm** [flxzt/rnote#165]
### Discussed in https://github.com/flxzt/rnote/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **tonilxm** May  7, 2022</sup>
I am figma user that use figjam feature a lot. But i recently try rnote as alternative.
Most oftenly i use "hand tool" to drag my canvas around and i find that having 2 click just to pan is just "too much work".
My suggestion is that to move the dragging tool to the front - same level as brush tool or to have option to bind it as keyboard shortcut.
Simply say the more bindings the better.

 </div>

**Comment by flxzt** [comment]
I think it is resolved. The tools sidebar page remembers the last used tool so the "dragging" tool should only be one click away most of the time.
