### ISSUE TITLE
[GTK] filechooser dialog: Keyboard focus automatically moves from the filename entry to the file list widget when typing a letter

### ISSUE THREAD

**Issue by jfab-123** [flxzt/rnote#173]
**Describe the bug**
The file manger bugs and I can't type the name of the file I want to save.  This is best described in this video: 

https://user-images.githubusercontent.com/81712003/168639960-7bf12c58-f29c-432a-9fd0-952969db367e.mp4

**To Reproduce**
1. Create a file
2. Save the file
3. Try to type a name for it in the file manager gui
4. Fail

** Console Output **
I ran ```rnote``` in the terminal and I got this when trying to save the file: 

```
(rnote:491413): Gtk-CRITICAL **: 11:18:25.897: Could not init tracker3 search engine: 
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Tracker3.Miner.Files was not provided by any 
.service files

(rnote:491413): Tracker-CRITICAL **: 11:18:26.746: tracker_sparql_connection_close: assertion 
'TRACKER_IS_SPARQL_CONNECTION (connection)' failed
```

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Version: Kernel: Linux 5.17.7-arch1-1
 - Installation source: Arch Community repo
 - Desktop Environment: No desktop environment. Bspwm as window manager.

**Comment by flxzt** [comment]
This is most likely a GTK bug, I would suggest you open a bug report on their [gitlab](https://gitlab.gnome.org/GNOME/gtk/-/issues). The affected widget is the `FileChooserNative`

**Comment by jfab-123** [comment]
@flxzt Why does this only happen in rnote? There are other applications with a file manager that don't present this bug. 

Thanks for the suggestion nonetheless, I will post a bug report over there!

**Comment by flxzt** [comment]
Xournal++ still uses GTK3, there are several types of dialogs app devs can use to open a dialog for opening and save files. The fact that you are using arch could mean that there is a bug in the arch GTK version. Some apps run with Xwayland, other natively with wayland. All could introduce this kind of bug. And since Rnote is using flatpak portals to use a `native` filechooser dialog and is not doing anything special (or anything at all) there with the keyboard focus makes it most likely that this is a GTK bug.

**Comment by flxzt** [comment]
Also please try out the flatpak version. If there is a bug with that, I am most likely able to reproduce it on my machine as well, thanks to flatpak runtimes and a isolated app environment

**Comment by jfab-123** [comment]
I really don't now much about flatpak so hopefully this is correct. 

Uninstalled rnote from pacman, installed flatpak and then I did ``` flatpak install rnote ``` . 

When I run the application with``` flatpak run com.github.flxzt.rnote``` the problem persists, so that didn't really help.

**Comment by flxzt** [comment]
This issue sounds pretty similar: https://gitlab.gnome.org/GNOME/gtk/-/issues/326

**Comment by jfab-123** [comment]
@flxzt This issue is no longer present in the current version of rnote, at least in Arch linux.
