### ISSUE TITLE
Feature request: Add shortcuts for the various tools

### ISSUE THREAD

**Issue by giannissc** [flxzt/rnote#18]
Using a drawing tablet (e.g. wacom) I often don´t have a keyboard next to me so I have to leave the pen and grab the mouse to change tools. My drawing tablet has configurable buttons that I can assign to keyboard keys and shortcuts. You could create a shortcut system with default shortcuts (e.g. F1 for pen, F2 for bursh, etc.) to assign tablet buttons to. It would also be nice if users could modify it to their liking. I know I have openned quite a few issues for you.. I am willing to help, but I haven´t used gtk-rs before. If you are willing to help me with any question that arrive while learning it I might be able to implement some of them :)

**Comment by flxzt** [comment]
I think thats a good idea! And I am actually glad for opened issues, because that means people actually use the app. I am not an expect on either Gtk or Rust either, but please don't hesitate to ask. I think in the issues or, if it is more general in the [discussions](https://github.com/flxzt/rnote/discussions) page would be a good place.

**Comment by giannissc** [comment]
The app is great and it is already showing great promise. I like the simple nature of it and how uncluttered the UI is. I know that xournalpp is feature rich but the workflow is a bit cluttered and ugly. It is probably more useful for more usecases but rnote is better in what it does, handwritten notes!!

**Comment by maymage** [comment]
Hi, 

I am not sure, if you can subsume the pen-buttons problem as a shortcut enhancment. Let me explain, please.

Scenario `Writing`
----------------------------

You're in the `pen state`, that is just writing. The two most likely actions, you'll want to perform, are
* `eraser state`
* `select+move state`

Since your pen has typically 2 buttons, you'll assign these two actions to these two buttons

Scenario `Lines`
-------------------------

You're in the `line-drawing state`. The two most likely actions, you'll want to perform, now are
* _return_ to the `pen state`
* toogle between drawing just a line or an arrow

So, you'll assign now different actions to the two buttons. 

----

Generally, unless you're in the `pen state`, for which the two buttons, as explained above, should be `erase` and `select+move`, 
one of the two buttons should always lead back to the `pen state`, which is clearly the ground state for a note taking app. 

So, I am not sure, whether `state dependent` shortcuts are compatible with what you'd normally expect, say `Ctrl+L -> Line`...

**Comment by flxzt** [comment]
I thought about adding the feature in this way: There could be multiple "action pads" in the settings, separated for the different pen types (lets say 2 each). Additionally there could be linked buttons where one could assign a keyboard shortcut / stylus button to the pads. The different actions could be dragged in from the buttons were the original actions are activated (e.g. delete selection, change pen, etc.).  
And for additional quick access / for users who only navigate with the mouse, the two pads would also appear in the headerbar.

**Comment by maymage** [comment]
I remember a similar shortcut issue for the (defunct) gnome-extension "draw on your screen", where I had made some default shortcut suggestions. Maybe that's helpful for design considerations. 

https://codeberg.org/som/DrawOnYourScreen/issues/44

**Comment by flxzt** [comment]
An initial implementation landed in v0.4.0, for now it is limited to changing the pens, and is independent to the current pen state. I still want to implement pen state dependent "action pads" though, at some other time.

**Comment by flxzt** [comment]
mentioned in #193, there should probably be support reconfiguring the middle mouse button, and adding navigation controls as actions ( the most requested feature related to shortcuts )

**Comment by flxzt** [comment]
I added "Ctrl + 1..6" keyboard shortcuts to the pens in the previous release (0.5.8), but I am not sure if this is sufficient for tablet users or if they need remappable keys from within the application. I would appreciate feedback for this

**Comment by giannissc** [comment]
I am a casual user of a drawing tablet so I might not be best person to provide feedback. Nonetheless, here it is:
Having fixed shortcuts is welcome for me since I don't use the tablet with a great deal of apps but maybe for other users who use their drawing tablet with multiple apps that have different shortcut it can complicate things. They would need to go to system setting and reconfigure the tablet setting everytime. 

A better alternative will be to have reconfigurable shortcut combos so that  users can adapt rnotes shortcut to equivalent in other apps.

An even better solution would have been to use the [PadController API](https://docs.gtk.org/gtk3/class.PadController.html) directly to read button presses and assign them from within the app. But I understand it can be cumbersome. Let's hope that [this](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1861) gets addressed soon

**Comment by giannissc** [comment]
There some really cheap ones these days if you would like to have a first hand experience with it. Otherwise just ping me about testing out new features. Happy to help!

**Comment by som-num** [comment]
Hi I was using the app for a while now and I am loving it compared to others. However I have this issue when using a drawing tablet Veikk vk640 
![image](https://user-images.githubusercontent.com/78010819/211241269-3f4df764-4982-4eb3-b649-98d8219134b8.png)
as you can see in the picture it has a button for alternating between pen/eraser mode however it doesn't work when using the app is there a way to fix this? Thank you

**Comment by flxzt** [comment]
@giannissc If your offer still stands, I created the `drawing-pad-shortcuts` branch that has an initial WIP implementation for testing. ( [https://github.com/flxzt/rnote/tree/drawing-pad-shortcuts](https://github.com/flxzt/rnote/tree/drawing-pad-shortcuts) ). 

For now pad buttons 0-2 are hardcoded to switch to the eraser temporarily. I'll expose some settings in the UI if I know it works.

I also added some logs when pad strips 0-1 and rings 0-1 are pressed. I am a bit confused about how that works, I would have expected they would emit some analog value but Gtk only is able to activate an action when they are are pressed (?). So I would appreciate if you could tell me when exactly that happens. If it doesn't make sense to hook up shortcuts to this I'd just leave them unmapped.

**Comment by flxzt** [comment]
@som-num The "eraser" mode on some styli is not directly mapped to the eraser in Rnote, you can choose it freely. Try holding the button down, hover over the canvas and then select the eraser while holding it. When you release it, the tool should swithc back and then remember it when you press it again.

**Comment by giannissc** [comment]
> @giannissc If your offer still stands, I created the `drawing-pad-shortcuts` branch that has an initial WIP implementation for testing. ( https://github.com/flxzt/rnote/tree/drawing-pad-shortcuts ).
> 
> For now buttons 0-3 have actions attached to them, strips and rings are currently not mapped.
> 
> I added some settings in the UI, for now they always reset to the action: "switch to the Eraser temporarily" on startup but it should work to modify the action while the program is running.

Well I meant what I said!  I will have a look on Friday! @flxzt

**Comment by flxzt** [comment]
Alright, I merged this feature now and published a new release that includes it (v0.5.15), because *I think* it should work. It probably was too much to ask to test by building a unmerged branch, so no worries!

**Comment by giannissc** [comment]
The weekend got a little easier than I would like. I have built rnote in the past and it was quite straightforward!
I have just given it a try and everything works perfect! I think it is safe to say that you can close the issue now :slightly_smiling_face:

**Comment by giannissc** [comment]
I recently got a tablet so I am no longer using my graphics tablet and hence rnote as much as I would like but everytime I give it another spin I leaps and bounds ahead from where I remembered. I can confidently say that is the best handwriting app for linux and on par with the best handwriting app on windows and android (at least for my needs :yum:) Great job!
