### ISSUE TITLE
Camera jumps/resets when pinching multiple times quickly

### ISSUE THREAD

**Issue by timeopochin** [flxzt/rnote#187]
**Describe the bug**
When pinching on a touchscreen multiple times quickly, the camera resets as if the different pinches were the same one.

**To Reproduce**
1. Draw a shape to see the camera movements
2. Pinch multiple times without pausing between the pinches

**Expected behavior**
Each pinch is treated separate, the camera doesn't jump around

**Console Output**
Not installed with `flatpak` so I don’t no how to show console output, running `rnote` from terminal shows nothing.

**Screenshots**
[Video of the behaviour](https://youtu.be/0M3B785ym7M)

**Desktop (please complete the following information):**
 - OS: Artixlinux (Kernel 5.17.9-zen1-1-zen)
 - Version: 0.5.3
 - Installation source: Archlinux Community Repo
 - Desktop Environment: sway version 1.7 (no x-wayland)

**Additional context**
This behavior is only observed on rnote, I can pinch in rapid succession with other software such as Firefox with expected behavior.

**Comment by flxzt** [comment]
It took a while, but it should now be fixed.

**Comment by timeopochin** [comment]
Thank you for fixing it ! It now works as expected :)
