### ISSUE TITLE
Remove trashed strokes when saving to file / as action

### ISSUE THREAD

**Issue by N3xed** [flxzt/rnote#188]
**Is your feature request related to a problem? Please describe.**

When deleting strokes or images, the strokes are not actually deleted in the file. 
For example, importing a 60-page PDF and then deleting 50 pages still stores the whole PDF.

**Describe the solution you'd like**
Either remove the deleted items in the saved file or have a button like `Delete history`/`Clear history`.

This especially matters when trying to trim down 50-page PDF notes to smaller sections, and when the history is very large (I like to doodle when I'm bored and then delete the doodle).

**Comment by flxzt** [comment]
is fixed, trashed strokes are now removed from the save
