### ISSUE TITLE
Bug: rnote hangs when trying to open a previously saved note file

### ISSUE THREAD

**Issue by giannissc** [flxzt/rnote#20]

**Comment by flxzt** [comment]
Could you elaborate a bit? Is the UI not responding at all, or the canvas not writeable anymore? If it is possible please create a save file where the issue is reproducable. Thanks!

**Comment by giannissc** [comment]
Really any file you save and then try to open completely freezes the whole application. Is this an issue with the one you have installed on your computer? I have installed mine as a flatpak

**Comment by giannissc** [comment]
I am happy to provide any error log you just need to tell me how to do it!

**Comment by flxzt** [comment]
Sounds pretty bad. Run in the cli with `RUST_LOG=rnote=trace G_MESSAGES_DEBUG=all flatpak run com.github.flxzt.rnote` and post the output when you are saving and loading the file and upload the saved file

**Comment by giannissc** [comment]
I actually run the app today and the open dialog worked just fine!!
I don't know what happened the other day maybe it was my PC that was causing the issue and when I restarted it it fixed itself

I will close for now and if it resurfaces I will reopen!
