### ISSUE TITLE
[GTK4 bug] zoom the canvas with pinch gesture on the touchpad only works occasionally

### ISSUE THREAD

**Issue by daudix-UFO** [flxzt/rnote#205]
Zoom a page using pinch gesture on trackpad, this can be done with libinput, for example, Eye of GNOME or inkscape does same thing, note that is only working on Wayland

**Comment by daudix-UFO** [comment]
Closing

**Comment by flxzt** [comment]
Sorry, I did not mean to ignore this. It is just that your description is difficult to understand and (still) low-effort and I genuinely could not make sense of the first issue you opened. I do believe the issue itself, if I understand it correctly is worth fixing.

**Comment by daudix-UFO** [comment]
No no no, It's my problem, your app have pinch-to-zoom, but for some reason, it work strange (2/10 times), the same thing happens in other libadwaita apps, in my case, GNOME Calendar (Nightly), but in same time works perfectly in inkscape, firefox, Eye of GNOME and e.t.c

_Here will be trackpad/screen recording_

**Comment by daudix-UFO** [comment]
No no no, It's my problem, your app have pinch-to-zoom, but for some reason, it work strange (2/10 times), the same thing happens in other libadwaita apps, in my case, GNOME Calendar (Nightly), but in same time works perfectly in inkscape, firefox, Eye of GNOME and e.t.c

📎 [DEMO](https://drive.google.com/file/d/16tw1rjzkvM7Pm2MaPOqxn7SiTwu7dPx-/view?usp=sharing)

**Comment by flxzt** [comment]
@daudix-UFO thanks for the video, that is super useful. Since this also happens in calendar and after searching in the gtk4 bugtracker it sounds like [this issue possibly](https://gitlab.gnome.org/GNOME/gtk/-/issues/5003) ?

**Comment by daudix-UFO** [comment]
Yes, this is it! Will make more short video and put it in this issue.

**Comment by daudix-UFO** [comment]
Fixed in latest version of GTK4 Demo, issue already closed on GitLab https://gitlab.gnome.org/GNOME/gtk/-/issues/5003, Now as far as I know we need to wait update of SDKs and test it.

**Comment by daudix-UFO** [comment]
The issue is fixed now, thank you!
