### ISSUE TITLE
failure to load .xopp files with certain background types

### ISSUE THREAD

**Issue by Sivecano** [flxzt/rnote#211]
**Describe the bug**
rnote failes to load xournal++ files with certain background styles

**To Reproduce**
1. Save a Xournal++ file with one of the following background styles: "Staves", "Dotted", "Isometric Dotted", "Isometric Graph"
2. try to open the file in rnote 
3. get error "opening .xopp file failed"

**Expected behavior**
rnote loads my file

**Console Output**

```
 ERROR rnote::appwindow::appwindowactions > Opening .xopp file failed.
 ERROR rnote::appwindow                   > load_in_xopp_bytes() failed in load_in_file() with Err Err while parsing `style` attribute of XoppBackground with node id NodeId(12), is not a valid value
```

**Desktop (please complete the following information):**
 - OS:  Linux
 - Version: 5.18.7
 - Installation source: archlinux user repository
 - Desktop Environment i3wm

**Additional context**
since rnote does not seem to be using the background style value anyway, this should be an easy fix.

**Comment by flxzt** [comment]
Thanks for the good bug report. Loading background styles is now fallible, defaulting to plain if it fails. As you said the style is currently ignored anyways, but this might change in the future.
