### ISSUE TITLE
Binary for Windows

### ISSUE THREAD

**Issue by BobH-Official** [flxzt/rnote#219]
A friend of mine, who is not a geek and using Windows, wants a Windows version of the app.
Does this app works on Windows?
Do you plan to support Windows?
or How can I build exe for Windows?

**Comment by flxzt** [comment]
There are instructions to [build manually](https://github.com/flxzt/rnote/blob/main/misc/building/rnote-windows-build.md) on windows. It works, but is probably too complicated to do for a non-technical user. Progress on creating an installer is being tracked in issue #46 .
