### ISSUE TITLE
Suggestion for Chinese translations

### ISSUE THREAD

**Issue by BobH-Official** [flxzt/rnote#220]
I found that the completion of `Simplified Chinese`translation is way higher than the `Traditional Chinese` ( 90+% vs 70+%).
As `Simplified Chinese` and `Traditional Chinese` are the **SAME** language but in two different **WRITING FONTS**, I suggest that we just keep the Simplified Chinese active, and use the converter tool OpenCC([https://github.com/BYVoid/OpenCC](https://github.com/BYVoid/OpenCC)) to automatically generate the Traditional version of Chinese.
In this way, translators no longer need to maintain two **SAME** languages, and their work should be easier.

**Comment by flxzt** [comment]
This is a good idea. Unfortunately weblate treats simplified and traditional as seperate languages, I don't think it is possible to convert them automatically there. Either a Github Action could be set up, or it could be done manually. Is it possible to convert .po files with `opencc`?. If yes, you could download the simplified chinese file from weblate, convert it and create a PR with the updated traditional chinese file. Would you be willing to do that?

**Comment by BobH-Official** [comment]
It is possible to do it with `opencc`. Because now it is mid-night here in China, I will probably do it tomorrow.
But before converting, I would like to know what does the term [`perm.`](https://hosted.weblate.org/translate/rnote/repo/zh_Hans/?checksum=edee9ee7aff9e450&sort_by=-priority,position) actually means. I found it confusing, and cannot translate it.

**Comment by flxzt** [comment]
No worries, there is no rush. :)
Ah that one probably needs a replacement by an icon or something. It is the abbreviation for permanent, it is the prefix of a checkbox.
![Bildschirmfoto vom 2022-07-17 18-37-27](https://user-images.githubusercontent.com/19841886/179413200-e6ce4dfb-67b9-4850-b21c-5b990d698dc7.png)

**Comment by BobH-Official** [comment]
OK, I will leave it as is. And that makes the Han_s to be 100% complete (for now).

**Comment by BobH-Official** [comment]
I have updated Chinese Traditional manually.
I used the config file `openCC\share\opencc\s2twp.json`.

**Comment by flxzt** [comment]
Thanks! Can you provide the exact command for conversion? I believe it should be possible to automate it.

**Comment by BobH-Official** [comment]
Yes, it can be done automatically. You can use openCC as either a `bin` or a `lib`. There are API for nodejs, python, cpp and etc. 
The question now is that what is the trigger of the automatic program (when should it run) and where should we put the converted version(on weblate or GitHub).

**Comment by BobH-Official** [comment]
My suggestion is that 
1. Delete the TC on weblate(we will not manually manage TC anymore)
2. Use GitHub Action to run automatically after PR merge
3. Just put the converted TC file in the repo's directory.
