### ISSUE TITLE
Annotate the desktop

### ISSUE THREAD

**Issue by Eelviny** [flxzt/rnote#223]
I wish I had the time and knowledge to contribute this myself, but instead I'll have to leave it as an enhancement request.

**Is your feature request related to a problem? Please describe.**
I give virtual classrooms online, and I'm looking for a simple solution in GNOME to replace OpenBoard. One of the "killer features" OpenBoard has is the ability to draw directly on the screen, so that I can quickly mark up what I'm doing during live demos of some service I'm teaching.

**Describe the solution you'd like**
I'd love to have a new mode in Rnote that allows me to draw directly on my desktop, 

I imagine it to be a floating version of the current toolbars overlaid on top of my desktop, where I can draw on the screen. I can then either discard my annotations, or take a "screenshot" of the screen + annotations and bring that into my Rnote document.

Being able interact normally with a normal mouse cursor mode like OpenBoard while in this mode would be nice but is extra.

**Describe alternatives you've considered**
I've tried just taking a screenshot and bringing it into Rnote to achieve a slightly less seamless but similar result, but Rnote doesn't seem to do pasting of images on the clipboard. My use case for Rnote is to quickly mark up and then discard my annotations, and this is not practical to do during the middle of a class.

**Comment by Eelviny** [comment]
Just spotted that pasting from the clipboard is coming soon! :smile: That's one more workaround at least.

**Comment by flxzt** [comment]
This can only be implemented by a gnome extension / it is out-of-scope for Rnote.
