### ISSUE TITLE
add windows file extensions in meson_post_install.py in case it's compiling for windows.

### ISSUE THREAD

**Issue by Kreijstal** [flxzt/rnote#226]
**Please submit only one feature request in one issue!**

Basically when running the python script from meson, it attempts to run some executables that can't be found because it executes them without the file extension, 

**Describe the solution you'd like**
add a check to see if it's running on windows, and conditionally add the extension.

**Describe alternatives you've considered**
I guess you could also detect to see if you're on windows and use some other python script like meson_post_install.windows.py conditionally.

**Comment by Kreijstal** [comment]
I would also like to add that DATA_DIR is hardcoded instead of using meson's datadir because the user could have always changed the value of datadir it's not necesarily in /usr/local/share...

**Comment by flxzt** [comment]
should be fixed with #235
