### ISSUE TITLE
Export to PDF inconsistent

### ISSUE THREAD

**Issue by Dennisman219** [flxzt/rnote#244]
**Describe the bug**
When exporting to PDF, the PDF is inconsistent with the document in RNote.
For example, when using lines as document background, the lines will be in a different position compared to when opened in RNote.
Also, in Rnote, you can draw inside the shadow space beside the document. This then shows up on a new page when exported to PDF.

**To Reproduce**
1. Open new document in RNote
2. Select lines as document background
3. Draw lines over the background lines
4. Draw in the shadow past the format border
5. Use Export -> Export document as PDF
6. Open PDF
7. Observe inconsistencies (drawn lines no longer over background lines, drawn lines outside document included in exported document)

**Expected behavior**
For the document background to be consistent when exported, and for any marks outside the document format to be excluded when exporting

**Screenshots**
https://snipboard.io/g3NpBY.jpg (Document in RNote)
https://snipboard.io/0SKtFN.jpg (Exported document)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 36
 - Installation source Flatpak
 - Desktop Environment GNOME 42.4

**Comment by flxzt** [comment]
The issue was actually not the export, but the rendering itself. The background pattern tiles were rendered slightly too large (2px).
