### ISSUE TITLE
Option to disable scrollbar

### ISSUE THREAD

**Issue by jonas-w** [flxzt/rnote#246]
**Is your feature request related to a problem? Please describe.**

I have a 2-in-1 laptop with a stylus. When i draw at the edge of the screen my hand often moves the scroll bar. Otherwise everything is fluent and my hand doesn't move the page very jumpy. Except when it comes to the scroll bar. As i never use the scrollbar it would be more convenient for me to have an option to remove it. And it is very annoying to lift my hand to write at the edges.

**Describe the solution you'd like**
A toggle for enabling/disabling the scrollbar.

**Describe alternatives you've considered**
Disable the scrollbar while the pen is touching/near the screen

**Additional context**
/

**Comment by JiveyGuy** [comment]
I use a Surface Note and Rnote is amazing compared to Scrivano, xournal /++, but this is a major issue. I am sent to some far away region while using my stylus because the scroll bar is randomly hit.

**Comment by flxzt** [comment]
There is now an option to hide the scrollbars permanently. It will land in the next release.

**Comment by jonas-w** [comment]
Works as intended thank you!

**Comment by jonas-w** [comment]
@flxzt do you already know when this will be shipped in a release?

**Comment by flxzt** [comment]
In a few days :)
