### ISSUE TITLE
Ability to resize or change cursor properties

### ISSUE THREAD

**Issue by siemato** [flxzt/rnote#247]
I am using Rnote primarily without a stylus, using typewriter and form drawing features. I am having issues seeing the cursor dot. On a 14inch 4k screen, it's barely visible and I lose track of it all the time. It would help a lot, if I were able to resize the cursor dot, or use the arrow everywhere optionally.

**Comment by flxzt** [comment]
Good suggestion, thanks.
Tweaking the size and properties of the icon itself is difficult, but there is now a cursor picker for picking the regular cursor and the cursor while drawing. Right now there are only three sizes of the "dot" cursor, but any SVG with size 64x64 can be used. So if someone feels creative and wants to have a custom cursor, post it here and I can include it (as long as it it is not anything too silly).

**Comment by siemato** [comment]
i guess, the endgame would be to auto-size it as a brush size indicator, but dot-large is a perfect size for taking notes for me, so I am totally fine with how it is now. It's a major improvement in usability. Thanks a lot for the effort and change.

**Comment by flxzt** [comment]
Not sure if auto-size is even advantagious for a note-taking app like Rnote. In professional drawing programs like Krita it definitely is useful, but I can imagine that it gets annoying when writing longer texts.

**Comment by siemato** [comment]
you're welcome  :> The advantage would indeed be limited and priority being very low. that's why I considered this closed. it's the 90% approach, with the last 10% taking 90% of the time.
