### ISSUE TITLE
Exported PDF file contains an extra blank page

### ISSUE THREAD

**Issue by kirusfg** [flxzt/rnote#250]
**Describe the bug**
An exported PDF file contains a blank page in the middle of the canvas despite the canvas not having it (at least as perceived in Rnote itself).

**To Reproduce**
1. Get this `.rnote` file from [notes.zip](https://github.com/flxzt/rnote/files/9594415/notes.zip)
2. Open and extract it to PDF
3. Observe a resulting PDF file with a blank page in it

**Expected behavior**
A PDF file looking exactly as it looks in the rnote app.

**Screenshots**
Below are the screenshots depicting this behavior. In the PDF file, there is a blank page between pages 4 and 5 of the `.rnote` document. In Rnote itself the page does not exist.

PDF file:
![2022-09-18-222029_1122x581_scrot](https://user-images.githubusercontent.com/32136879/190917865-304fa957-df61-404d-9e38-61a5731ee811.png)

Rnote:
![2022-09-18-223116_942x455_scrot](https://user-images.githubusercontent.com/32136879/190917868-3e11072f-6ac9-4f86-922d-806d5384d925.png)

**Desktop:**
 - OS: Artix Linux
 - Version: 0.5.4
 - Installation source: Archlinux Community Repo
 - Desktop Environment: None (i3 with GTK4 installed)

**Comment by flxzt** [comment]
My first guess would be that a stroke is too close to the border on the previous page. It could be that the bounding box of that stroke is beyond the page border, so Rnote thinks that something is written on the side.
Obviously this should not happen when in "continuous vertical" mode because there the page is always hidden but a quick fix would be to avoid writing too close to the page border.

**Comment by kirusfg** [comment]
I have confirmed using the visual debugging mode that this was the case, although it did not come to mind at first that bounding box going outside of the canvas **horizontally** could result in that. 

Perhaps, there should be an option when extracting fixed length canvases to ignore what goes outside from the left or from the right.
