### ISSUE TITLE
Changes to "Quit Application" dialog

### ISSUE THREAD

**Issue by PJansky** [flxzt/rnote#252]
I would like to propose two modifications to the "Quit Application" dialog.
1. Rnote now uses buttons in following order: Cancel/Save/Discard. As far as I can tell, Rnote is the only application with this button order. The Gnome HIG calls for the left most button being the cancel, therefore I would suggest swapping the "save" and "discard" buttons and keeping the cancel button to the left. Doing so would also follow the button order as seen in newer Gnome applications like Gnome Text Editor and Gnome Builder.
2. As it stands, the buttons in Rnote are quite verbose. Gnome Text Editor and Gnome Builder use simple "Cancel", "Discard" and "Save" labels, while Rnote uses "Cancel", "Quit" and "Save current document as". While the buttons in effect do the same thing, the labels Rnote uses are somewhat unconventional and quite long. Therefor I would propose using the "Cancel", "Discard" and "Save" labels instead. Xournal++ uses the same labels btw, but uses a different button order.

Current Rnote "Quit Application" dialog
![Rnote](https://user-images.githubusercontent.com/46072333/191739073-2eb45ac2-8d6c-418c-a78e-e84e5b97f988.png)

Gnome Text Editor  "Save Changes?" dialog
![Gnome_Text_Editor](https://user-images.githubusercontent.com/46072333/191739193-e341a57a-f3ce-4c35-9a3a-a05c2f69b41d.png)

**Comment by Heiseneberg-maybe** [comment]
I'm not a developer but I could change this with weblate and then you would just need to accept the weblate merge request
Is this ok for you @flxzt ?

**Comment by flxzt** [comment]
@Heiseneberg-maybe no, please don't try to do that. It is not possible to do that change in weblate. I'll fix it in the code.
