### ISSUE TITLE
New shape: Arrow

### ISSUE THREAD

**Issue by robem** [flxzt/rnote#253]
**Please submit only one feature request in one issue!**

Add an _arrow shape_ to the shape builder

**Is your feature request related to a problem? Please describe.**

I frequently draw simple diagrams with rectangles, circles, and arrows in my notes.
Eventually, I would like to select those tools with shortcuts, so that I can quickly draw them without leaving my train of thought too much.

**Describe the solution you'd like**

Add an arrow option to this menu:
![image](https://user-images.githubusercontent.com/669201/192030011-e1135cb5-2fd3-4804-ba15-1988b8758849.png)

**Describe alternatives you've considered**

1. Looking at issue #47 - making an arrow by modifying the beginning/end of a line. I'm not a fan of this because it will take too many steps to draw an arrow and then switch back to a line. I would like to draw an arrow just like a rectangle.
2. Draw an arrow by hand. Well, I'm not an artist, but I could get a good-looking arrow with a couple of tries, save it as an SVG in my workspace and import it whenever I need one. This solution works, but is a bit cumbersome / takes too much time.

**Comment by TornaxO7** [comment]
@flxzt do you think that this is hard to do?

**Comment by TornaxO7** [comment]
ok, then I'll pick this issue
