### ISSUE TITLE
Add option to make format borders more subtle

### ISSUE THREAD

**Issue by diminDDL** [flxzt/rnote#256]
**Is your feature request related to a problem? Please describe.**
The current option to show format borders is great, but they are anything but subtle and are quite distracting.

**Describe the solution you'd like**
Adding an option that would display a grey dotted line for the border or something less noticeable than the current red line.

**Describe alternatives you've considered**
Perhaps just changing the color would be a good compromise too.

**Additional context**
An example of that might look like:
![rnote](https://user-images.githubusercontent.com/25513498/192102077-d22269ca-8603-40c5-91c8-c055cc5c3ae1.png)

**Comment by flxzt** [comment]
It is already possible to change the format border color. Look in the "General" category in the settings.
