### ISSUE TITLE
Thumbnail should show `Name_of_document - Rnote`, not `rnote`

### ISSUE THREAD

**Issue by ovari** [flxzt/rnote#259]
1. Open Rnote
2. Hover above Rnote application in the Panel
3. `rnote` shows instead of `Name_of_document - Rnote` as displayed in the image below:
![kép](https://user-images.githubusercontent.com/17465872/192127179-4b57469c-5f34-4db4-8231-e9b83f4282e0.png)

Linux Mint 21 Cinnamon

**Comment by Heiseneberg-maybe** [comment]
I would add that an even better behaviour would be to display "Name_of_document - Rnote" like Gnome Text Editor and xXournal++ do
