### ISSUE TITLE
English incorrectly showing when Hungarian is set

### ISSUE THREAD

**Issue by ovari** [flxzt/rnote#260]
English incorrectly showing when Hungarian is set in the operating system.

![kép](https://user-images.githubusercontent.com/17465872/192127288-d5a489f8-a02d-440c-871b-e2ec74203f0c.png)

Thank you

Linux Mint 21 Cinnamon

**Comment by flxzt** [comment]
The app did not have a release after the hungarian translation was added. I will release a new version soon.
