### ISSUE TITLE
Half infinite document layout

### ISSUE THREAD

**Issue by D0V4HKIIN** [flxzt/rnote#263]
**Describe the solution you'd like**
A mix of the infinite and the continuous vertical document layout where there is a border to the top and the left but not on the right nor the bottom.

**Comment by ktotam1** [comment]
this app would be way more useable with this feature imo

**Comment by flxzt** [comment]
not opposed to adding this but what is the downside of the infinite layout in comparison to this?

**Comment by D0V4HKIIN** [comment]
I use the continuous vertical layout and sometimes what i write is a bit longer than the width of the page which is annoying because then i have to split the formula/sentence in 2 lines. I guess infinite would allow me to fix that but it's kind of annoying to use because i have to be more precise when scrolling up and down to look at older notes.

**Comment by D0V4HKIIN** [comment]
I feel like my explanation's really bad, but the idea is the ssme as a text editor. You don't need it nor do you want to be able to scroll to the left or over the top of the file

**Comment by flxzt** [comment]
No, makes sense! I'll review the PR soon
