### ISSUE TITLE
Paste (clipboard contents) button

### ISSUE THREAD

**Issue by Heiseneberg-maybe** [flxzt/rnote#265]
**Is your feature request related to a problem? Please describe.**
When using the app with a 2in1 the only way to paste an image is to revert the laptop in an actual laptop and use Ctrl+V

**Describe the solution you'd like**
It would be helpful to have a paste button, maybe in the tools section or as a standalone mode.

**Describe alternatives you've considered**
I would use the drag and drop but nautilus doesn't really allow that, neither with the fingers or with the stylus. 

Another useful feature, related to this one, would be to have a button that opens the file picker dialog. 
Altough I think that this features should be independent from each other.

**Additional context**
I understand that this would be fixed if nautilus worked correctly but I would add that it's way faster and easier to have a button to paste the contents of the clipboard than to open a file manager and drag and dropping an image.

**Comment by flxzt** [comment]
I like the idea of a paste (and a copy to) clipboard button.

But not sure what you mean by a button that opens the file picker, because that already exists as the "Import file" dialog?

**Comment by Heiseneberg-maybe** [comment]
I noticed only now that "Import file" can import images too, I thought it could just open .rnote .xopp and .pdf files. 

With that "a button that opens the file "  I was thinking about something like Xournal++ has: a button (with an image as an icon) that when clicked  let's you decide where to put an image and then lets you pick only images from the file picker. 
Nonetheless that feature is there I just didn't notice it.

Thank you very much for your work on this app.
