### ISSUE TITLE
[Question] Install in custom path

### ISSUE THREAD

**Issue by TornaxO7** [flxzt/rnote#272]
Hello! I'd like to know how I can set the destination install-place in [BUILDING.md](https://github.com/flxzt/rnote/blob/main/BUILDING.md#install-1) because I don't want to execute that `meson install (...)` command with sudo everytime I want to test it.

**Comment by flxzt** [comment]
you can set the `--prefix=` path to any directory you want (e.g. `.\_mesoninstall` ) Then you don't need root permissions to install, but then the app won't integrate into the system. The binary should still work however.

**Comment by TornaxO7** [comment]
ooh, ok, thank you for the information!
