### ISSUE TITLE
Scrolling with touchpad isn't possible after activating the permanent hide scrollbars setting

### ISSUE THREAD

**Issue by Heiseneberg-maybe** [flxzt/rnote#274]
**Describe the bug**
When activating the permanent hide scrollbars setting it is not anymore possible to scroll with the touchpad(neither vertically neither horizontally). 
It is however possible to scroll with a stylus via scrolling on the side of the page   

**Desktop (please complete the following information):**
 - OS: [Fedora]
 - Version [36]
 - Installation source [Flatpak]
 - Desktop Environment [42.4]

**Comment by flxzt** [comment]
Oh no. Thanks for reporting, the feature was not tested enough.
