### ISSUE TITLE
Export svg/png/pdf/... with same file base name

### ISSUE THREAD

**Issue by pglira** [flxzt/rnote#284]
Thank you so much for sharing this awesome application.

This is a request for a minor improvement. When exporting a file, e.g. to pdf, it would be better IMO to use the same file base name instead of the current timestamp.

E.g.:
```
filename = my-sketch.rnote
new_default_pdf_export_filename = my-sketch.pdf
(current_default_export_filename = 2022-10-06_06-45-34_doc.pdf)
```

**Comment by flxzt** [comment]
That's a good idea, thanks!

**Comment by pglira** [comment]
Thank you, that's awesome!
