### ISSUE TITLE
[Refactoring Suggestion] Split up workspacebrowser

### ISSUE THREAD

**Issue by TornaxO7** [flxzt/rnote#292]
Currently the amount of attributes gets bigger and bigger as you can see [in my PR](https://github.com/TornaxO7/rnote/blob/basic_file_context_64/rnote-ui/src/workspacebrowser/mod.rs#L31-L62). I'm wondering if it's possible to split the attributes up, like wrapping some attributes into new structs to reduce the amount of total attributes in the `WorkspaceBrowser` struct. What do you think about this @flxzt ?

**Comment by flxzt** [comment]
I don't know, I don't think its an issue to be honest. I usually try to start splitting files up when they have more than 1000 to 1500 LOC .
