### ISSUE TITLE
Pdf export as command line option

### ISSUE THREAD

**Issue by bgfxc4** [flxzt/rnote#296]
**Is your feature request related to a problem? Please describe.**
I have a lot of single rnote files, one for every lesson in school and I have to convert them all to pdfs and merge them together and I would like to automate that, because there are far more than 100 files

**Describe the solution you'd like**
A command line option like --to-pdf [PATH], which, if specified, would start rnote without GUI and just export the opened rnote file to PATH as pdf file (ex: rnote --to-pdf dest.pdf source.rnote would create dest.pdf from source.rnote)

**Describe alternatives you've considered**
I could do it by hand and with the gui or automate it with python, automating the key and mouse inputs

**Comment by flxzt** [comment]
I'll see if I can create a small cli tool with the desired feature, as a separate executable by reusing the `rnote-engine` subcrate without the UI.

**Comment by flxzt** [comment]
Hey, I created a small cli interface. It is available in the [cli branch](https://github.com/flxzt/rnote/tree/cli) and can be built either with meson by enabling the `-Dcli=true` option or directly with cargo:

`cargo build --release -p rnote-cli`

The binary will then be built into `target/release/rnote-cli`. It'll output a help screen for the usage when you run it without any args or with `--help`.

Right now the tool is very rudimentary, I just wanted to get it out there to give you the ability to use it. I'll add more features to it over time, and it will be merged into main at some point.
Also: The Cli interface is very unstable and can change at any point as I am adding more features. So please don't rely on it in anything else than a one-time usage script.
