### ISSUE TITLE
[Design] Linked undo & redo

### ISSUE THREAD

**Issue by lainsce** [flxzt/rnote#3]
Going forward, in libadwaita-using projects, the usage of `linked` css class in a GtkBox holding GtkButtons in the headerbar is discouraged due to different design direction than others using libadwaita.

Please understand this, and change those instances with buttons directly on the headerbar, and a separation to the other controls from the once-linked buttons with a separator in-between those and the rest of the UI up there, with the `spacer` css class.

**Comment by flxzt** [comment]
This sounds reasonable, changed it
