### ISSUE TITLE
Mouse very hard to see on high dpi displays

### ISSUE THREAD

**Issue by nilsmartel** [flxzt/rnote#304]
**Describe the bug**
On high DPI Displays the cursor becomes very hard to recognize, to the point of being close to invisible to the naked eye

**To Reproduce**
Now, this is very uncomfortable, but most you just want to get a high res display.
I am using a matebook x pro or something similar sounding.

**Expected behavior**
Have some indication about the current cursor position, when the cursor gets to small.
I

** Console Output **
Run with `flatpak run com.github.flxzt.rnote` and post the output here

**Screenshots**
![image](https://user-images.githubusercontent.com/28377948/196510300-37844591-aee9-4935-93eb-fa0eadc0d865.png)

Suchbild, try finding the cursor here

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version -
 - Installation source Flatpak
 - Desktop Environment Gnome

**Additional context**

**Comment by nilsmartel** [comment]
PS:

Your creation is one of the most beautiful apps I have ever worked with, and I truly mean ever. After years with windows, years with macs, and some time with linux, I came across a lot of software, as is expected. But close to nothing looked so very truly beautiful

**Comment by Tuba2** [comment]
I believe this has already been solved by the cursor picker proposed in #247 — which still has not been released in a public Flatpak build. We HIDPI-screeners will be able to use it soon enough ;)

**Comment by flxzt** [comment]
Yes, should be solved by the addition of a cursor picker, with the addition of larger variants. You can try the latest beta on flathub to test them, if you want. I also just added additional "crosshair" & "beam" cursors ( unfortunately I didn't add those to the beta ).
