### ISSUE TITLE
Color Selection is slightly shifted [ui]

### ISSUE THREAD

**Issue by nilsmartel** [flxzt/rnote#305]
**Describe the bug**
The position of the colors is slightly wrong

**Screenshots**
The black color field has a different indent than the other fields. It's shifted more to the right
![image](https://user-images.githubusercontent.com/28377948/196511411-3e40004d-2d0a-4a4d-9523-877ae33ba674.png)

This seems to happen with all colors. The yellow field on the bottom ever so slightly overlaps with the green one.
![image](https://user-images.githubusercontent.com/28377948/196511542-b15774db-f25b-4de1-88d7-1e2b5e721cb0.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Installation source Flatpak
 - Desktop Environment Gnome

**Comment by flxzt** [comment]
Yeah, the borders of these buttons are overlapping when they are grouped together. Should be fixable by tweaking some CSS.
