### ISSUE TITLE
File Format stabilization

### ISSUE THREAD

**Issue by OmegaRogue** [flxzt/rnote#316]
Is there an ETA for when the file format is going to be stable?

**Comment by flxzt** [comment]
No, not yet. All I can say right now is that I am committed to provide an upgrade path whenever possible.

**Comment by OmegaRogue** [comment]
So it should be safe to use rNote for taking notes in class?

**Comment by flxzt** [comment]
I think so! In the case that there will be an incompatible break in the format at some point in the future, it is still possible to downgrade to a specific version and export the documents. (see: https://github.com/flxzt/rnote#installation )

**Comment by OmegaRogue** [comment]
Thanks!
