### ISSUE TITLE
Selection cannot be dragged, resized or rotated using stylus

### ISSUE THREAD

**Issue by ben-hansske** [flxzt/rnote#321]
**Describe the bug**
The 5.6 update apparently broke dragging, resizing and rotating the active selection. I can select strokes using the rectangle selection tool, but after that, I can only use my mouse/touchpad to drag/resize/rotate the active selection. If I try to use the stylus, it will start spawn a new rectangle selection instead. Before 5.6 dragging, resizing and rotating with a stylus worked.

**To Reproduce**
1. Draw a few strokes
2. Switch to the Selector - Tool
3. Select Strokes with Rectangle Selection
4. Try to move/resize or rotate using stylus

**Expected behavior**
I should be able to manipulate the active selection using a stylus. It already worked before 5.6

** Console Output **
╰─>$ flatpak run com.github.flxzt.rnote
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.6
 - Installation source: Flatpak
 - Desktop Environment: GNOME 42.4

**Comment by flxzt** [comment]
I can reproduce it, but only when the `touch-drawing` option is enabled.

**Comment by ben-hansske** [comment]
This makes sense. I was trying to debug this issue right now. It seems like rnote-ui/src/appwindow/mod.rs seems to invoke handle_pen_event with PenEvent::Cancel in line 1391. This happens directly in between the calls to handle_pen_event with PenEvent::Proximity and PenEvent::Down. Therefore the selection gets lost.

Disabling "Draw with touch-input" does indeed solve the issue for me. My graphics tablet does not support touch input, therefore I was not sure what that button actually meant. Now I know. Thank you very much!

**Comment by flxzt** [comment]
Thank you for looking into it, that really helped me. Yeah that was an attempt to make the zoom gesture work while touch drawing was enabled, but I think now that it isn't possible in a satisfactory way and was the source of this problem. Removing those PenEvent::Cancel emissions resolves it.
