### ISSUE TITLE
[Feature Request] Stylus Button Shortcut to move the canvas

### ISSUE THREAD

**Issue by Mat931** [flxzt/rnote#337]
**Is your feature request related to a problem? Please describe.**
After switching from Xorg to Wayland I noticed that I can't move the canvas with the stylus button anymore like I used to

**Describe the solution you'd like**
![rnote-move-concept](https://user-images.githubusercontent.com/49403702/200191946-f9da1703-295f-4968-ad51-a540cf359bfd.png)

**Describe alternatives you've considered**
To move the canvas I have to reach for the mouse and use the middle mouse button

**Comment by ritamsaha00** [comment]
Check out #313, if you are still not satisfied maybe @flxzt can help.

**Comment by flxzt** [comment]
It is already available as a tool. You can set the shortcut to "Tools", the last used is remembered
