### ISSUE TITLE
Gesture Eraser

### ISSUE THREAD

**Issue by mityax** [flxzt/rnote#341]
A nice feature from [supernote](https://supernote.com/pages/note-system-everything-you-need-to-stay-organized?gclid=CjwKCAjwtKmaBhBMEiwAyINuwDc8CXV1IILZX6AV5VmbPQwL8n76lL0GdRdRbjvETropkDz-_sa4URoC96AQAvD_BwE) is their gesture eraser:

> Normally when we write on the desk, we hold a pen with one hand and place the other hand next to the notebook or pressed directly on the edge of paper, which is a balanced and comfortable position. "Gesture Eraser" is to utilize the free hand. When you like to use the eraser, just put two fingers on the screen, the pen will turn to area eraser automatically. And the eraser will be switched back to pen function immediately after release of finger-tapping. 

This feature should be easy to implement and would be pretty handy. On MS Surface devices (which make for a large part of Linux touch devices I guess), you usually need to turn the pen around to erase - this is annoying and the gesture eraser would solve it elegantly, allowing a faster and less interrupted workflow.

**Comment by flxzt** [comment]
I like the idea and it be implementable by using gtk gestures. Just so that I understand it correctly: Is this like a hold gesture with two fingers?

It could even be added like the stylus buttons, so that the user can choose which pen this gesture activates.

**Comment by mityax** [comment]
Here's a video of their implementation, which I think is pretty cool:

![GIF](https://cdn.shopifycdn.net/s/files/1/0565/1945/9007/files/b5563d2c-f8d2-4023-8ab8-a1381f2e27b3_600x600.gif?v=1625565347)

However, the encircling part wouldn't even be necessary, in my eyes it'd be fine if the pen ist just toggled to the usual eraser.

**Comment by benjamin051000** [comment]
As an MS Surface user, I personally hate when note apps:
- Don't support the eraser side of the stylus 
AND 
- don't offer an alternative (i.e., only have a software button to switch to eraser

I'm so used to it from OneNote that I have to have a fast way to erase. I'm glad Rnote currently supports both ends of my Surface pen.

This would actually be an awesome feature, especially if we could choose what the gesture actually does. For example, instead of eraser, it could be the select tool.

**Comment by flxzt** [comment]
implemented with #464 . I have to say I personally really like this feature, thanks for the suggestion. I can see the flow for touch-tablets benefiting a lot with it
