### ISSUE TITLE
Add margin when exporting selection

### ISSUE THREAD

**Issue by mityax** [flxzt/rnote#342]
When exporting the current selection the image is auto-cropped to fit the content exactly - this looks weird and sometimes even makes it hard to read things close to the sides correctly.

I'd suggest a small margin around the exported image to circumveat this

**Comment by flxzt** [comment]
Good suggestion, thanks!

**Comment by mityax** [comment]
So cool, thanks a lot for the quick implementation (and your app in general ofc)!
