### ISSUE TITLE
Drop text on canvas

### ISSUE THREAD

**Issue by martin-desktops** [flxzt/rnote#346]
# Feature description
Dropping a text dragged from another app on the canvas would make working with many applications at once much smoother process. It removes a lot of steps to import text resources, what is especially significant improvement to navigation on devices with on-screen keyboard only.

# Concept video:
https://user-images.githubusercontent.com/64419373/201520314-0aee1fc2-32b9-4253-b5b0-2bd41b1a6a26.mp4

# Additional context
It's already possible to drag a text and drop it to some apps like Text Editor:

[Screencast from 2022-11-13 12-24-23.webm](https://user-images.githubusercontent.com/64419373/201520044-c352963b-86fe-48cd-9e3b-3545b14671c1.webm)

**Comment by flxzt** [comment]
Sounds good, thanks for making an effort in the feature request with these videos.

**Comment by flxzt** [comment]
I just noticed (immediately after releasing -.- ) That the text is inserted with the selection, if the typewriter is not already selected. Fixed that, so now it will switch to the typewriter on insertion. Will be included in the next one

**Comment by martin-desktops** [comment]
Not a big deal. I am amazed how seamless the workflow is :) Works like a charm!
