### ISSUE TITLE
Settings are hard to find

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#351]
The only way to get to settings is to expand the sidebar, which confusing because no other app does it like this. Perhaps they should be in a regular preferences dialog instead, or at least there could be some way to get there from the primary menu.

**Comment by flxzt** [comment]
Hi, I'd like to keep the settings in the sidebar, but an action to find them easier sounds good to me. What are your thoughts on this?:

[Bildschirmaufzeichnung vom 2022-11-16, 11-05-04.webm](https://user-images.githubusercontent.com/19841886/202151705-ff3b9055-2788-4e34-9e25-2ce300867bf1.webm)

**Comment by bertob** [comment]
I'd put them in the second group, since that's where Preferences usually goes, but yeah, it's definitely an improvement.

**Comment by flxzt** [comment]
Okay. Lets discuss more menu reordering / merging in #350
