### ISSUE TITLE
UI: Tool icons are off-style

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#352]
Many of the tool icons are not hinted to the pixel grid, have too much detail, or are using an older, smaller/less geometric GNOME symbolic style.

I'd recommend switching them to the following icons from [Icon Library](https://flathub.org/apps/details/org.gnome.design.IconLibrary):
- Brush: `paintbrush` ![paintbrush-symbolic](https://user-images.githubusercontent.com/1908896/201711708-668bdfdd-240d-4178-bbc1-a7bbfa063fd9.svg)
- Shaper: `shapes` ![shapes-symbolic](https://user-images.githubusercontent.com/1908896/201712239-9f45f3cd-d0c8-49e0-8d72-6798f49d9219.svg)
- Typewriter: `text3` ![text3-symbolic](https://user-images.githubusercontent.com/1908896/201710770-adc9156d-2a8e-405a-9390-321d416c7bfe.svg)
- Eraser: `eraser4` ![eraser4-symbolic](https://user-images.githubusercontent.com/1908896/201712416-07afe02d-a602-47c0-b7f3-9daa16fda314.svg)
- Selector: `edit-select-all` ![edit-select-all-symbolic](https://user-images.githubusercontent.com/1908896/201712611-7301e5ff-0a3b-465b-b637-024a9456f002.svg)
- Tools: `wrench-wide` ![wrench-wide-symbolic](https://user-images.githubusercontent.com/1908896/201710789-3d1144cd-1d2e-4d9a-a782-2883f346677c.svg)

![image](https://user-images.githubusercontent.com/1908896/201691671-56fc331a-6bd2-449b-8c73-fd2ee59e0344.png)

**Comment by bertob** [comment]
Yeah, some of these icons are not in the Icon Library until the next update, since I added them a few days ago. That's why I embedded the SVGs directly in the issue :)

I'll think of something else for selector.

**Comment by flxzt** [comment]
There is a similar selection symbol in the icon library, which I think looks better: ![Bildschirmfoto vom 2022-11-18 17-11-29](https://user-images.githubusercontent.com/19841886/202750300-e4f76c01-2c1b-46c1-b37e-0f921db8d211.png)

**Comment by bertob** [comment]
Hmm yeah, I don't hate this one for selection. I'll maybe do another pass on it to make it more rounded later, but definitely an improvement.

What does need fixing though in that latest screenshot is the eraser icon, it's too small compared to other icons.

**Comment by flxzt** [comment]
Personally not a huge fan when everything is too rounded and toy-like, but thats the gnome style I guess 😄. I wonder why that icon is the library app though, or is that the one you want to replace it with the new one?

**Comment by bertob** [comment]
Hmm, this eraser is also a bit small, yeah. It's definitely better than the original one though, because it avoids the off-style 1px lines. I can take another look at it later.

**Comment by flxzt** [comment]
Okay, thank you.

**Comment by flxzt** [comment]
What about simply using a scaled up version with the line removed?: 
![pen-eraser-symbolic](https://user-images.githubusercontent.com/19841886/203533357-7ff5c7ec-6636-4eaf-a62c-92d551a5dcd5.svg)
![Bildschirmfoto vom 2022-11-23 12-18-57](https://user-images.githubusercontent.com/19841886/203534187-da56fa97-9054-479f-ae3f-aad8c73ddd8f.png)
