### ISSUE TITLE
Primary stylus button doesn't work properly

### ISSUE THREAD

**Issue by ritamsaha00** [flxzt/rnote#355]
**Describe the bug**
Since the new update, the primary button only toggles on the selection tool, even if the settings is set to other tools (eraser tool in my case).

**To Reproduce**
I do not know how. It just started since I updated my OS and rnote.

** Console Output **
Run with `flatpak run com.github.flxzt.rnote` and post the output here

```
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress
predict with stroke modeler failed, status: FAILED_PRECONDITION: Cannot construct prediction when no stroke is in-progress

(rnote:2): Gtk-CRITICAL **: 11:06:04.750: The layout manager of type GtkBoxLayout 0x564c72cac250 does not create GtkLayoutChild instances
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Version: 22.10 x86_64
 - Installation source: Flatpak
 - Desktop Environment: 43

**Comment by flxzt** [comment]
Hi, try to select the tool you want to be mapped to the button while holding the button, it should remember it. On some stylus pens one of the buttons is mapped to another "mode" (which other pens have a "eraser" side on that toggles that mode), so the settings are  not always consistent.

**Comment by ritamsaha00** [comment]
So, I tried this method, but it's still not working. Is there anything else I can do?

**Comment by wisp3rwind** [comment]
> Hi, try to select the tool that you want as a shortcut while holding the button, it should remember it. On some stylus pens one of the buttons is mapped to another "mode" (where other pens have a "eraser" side that toggles that mode), so the settings are not always consistent.

Thanks, this also works for me (for context, this is using a Bamboo Ink Plus).

I had to attempt this is a few times until it actually remembered this correctly, not quite sure what I did differently the last time.
