### ISSUE TITLE
You cannot write anything over a colour-filled shapes

### ISSUE THREAD

**Issue by ritamsaha00** [flxzt/rnote#369]
**Describe the bug**
If you draw a shape and fill it with colour and try to write something using the brush tool, the writing will be behind the shape; thus it will not be visible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Rnote
2. select the shape tool, and choose a shape fill colour (anything but the transparent colour)
3. Try to write something with the brush tool

**Expected behaviour**
The stroke by stylus when the brush tool is chosen should be in front of the shape instead of behind it.

** Console Output **
Run with `flatpak run com.github.flxzt.rnote` and post the output here

No useful output was obtained.

**Screenshots**

![Screenshot from 2022-11-24 00-11-55](https://user-images.githubusercontent.com/69363775/203624399-e226736f-2d96-4853-a853-9d3e864e00c9.png)
![Screenshot from 2022-11-24 00-12-05](https://user-images.githubusercontent.com/69363775/203624434-f78fb346-ab71-49fc-b799-b5656e9f9d55.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.10
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43

**Additional context**

**Comment by flxzt** [comment]
Are you writing with the marker? Try switching to the "Solid" brush style. The marker is supposed to work as a highlighter behind the writing / shapes

**Comment by ritamsaha00** [comment]
That does clear up things, but if I am being honest, I am more comfortable with writing with the marker brush than the solid brush. Is there any way we could accommodate, maybe a separate highlighter brush with less opaque colours?

**Comment by flxzt** [comment]
I want to, it is mainly blocked because the rendering for a single, larger half-transparent stroke gets slow very soon. I hope that I can rework the rendering soon, so when that is done it should be possible to add such a pen.

But if you want to have a fixed width brush, you could also set the option "pressure curve" to "constant" for the solid style. :)
