### ISSUE TITLE
Better emoji icon

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#372]
The current emoji icon in the text tool is off-style, I'd use this one: ![smile-symbolic](https://user-images.githubusercontent.com/1908896/203801231-6242ef16-f4b9-4cd2-843c-65dc7c4f7de8.svg)

![image](https://user-images.githubusercontent.com/1908896/203801279-595ab986-81d9-4e01-9410-5d58eeceb2a4.png)

**Comment by flxzt** [comment]
Thanks!
