### ISSUE TITLE
Feature Request: Support system GTK theme

### ISSUE THREAD

**Issue by proudmuslim-dev** [flxzt/rnote#38]
I've just found this app and have been seriously enjoying it- thank you! My only gripe is that it doesn't use my system theme, so I thought I'd open this issue

**Comment by flxzt** [comment]
Its a libadwaita app, so it does not support theming so app devs like me can make sure the UI is as polished as possible. :) Tough, coming with Gnome 42, it will respect the Light / Dark system setting and sometime in the future a libadwaita recoloring API is coming too.

**Comment by proudmuslim-dev** [comment]
Ah I see, thanks for your response
