### ISSUE TITLE
Open File dialog yields "The folder contents could not be displayed", Rnote hangs until dismissed

### ISSUE THREAD

**Issue by benjamin051000** [flxzt/rnote#382]
**Describe the bug**
Opening a file causes an error dialogue to popup (see screenshot below). The popup appears behind the original Rnote window, which makes it difficult to notice. Further, the file picker also opens on top of both, making it even more difficult to see the error popup.

If I select a .rnote file to open, the file is read successfully, but the UI hangs until the dialogue is dismissed by pressing OK. I can see UI responds to cursor clicks and hovers (buttons change color on hover and click), but no buttons actually perform any actions, including the minimize, maximize, and exit buttons. At this point a force quit is required.

Dismissing the popup dialogue appears to resolve the hang and the UI appears to resume normal functionality.

**To Reproduce**
1. Open Rnote
2. Press Ctrl+O to open a file
3. Error dialogue appears behind main window
5. UI hangs until dialogue box is dismissed

**Expected behavior**
I expected the dialogue box to pop up in front of the main window so I can recognize and dismiss it to continue using Rnote.

** Console Output **
```log
(rnote:2): GLib-GObject-WARNING **: 13:04:49.139: invalid (NULL) pointer instance

(rnote:2): GLib-GObject-CRITICAL **: 13:04:49.139: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

<<Pressing Ctrl+O>>

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_new_bytestring: assertion 'string != NULL' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_new_variant: assertion 'value != NULL' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_get_type: assertion 'value != NULL' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_builder_add_value: assertion '!GVSB(builder)->expected_type || g_variant_is_of_type (value, GVSB(builder)->expected_type)' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_builder_end: assertion 'GVSB(builder)->offset >= GVSB(builder)->min_items' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_get_type: assertion 'value != NULL' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(rnote:2): GLib-CRITICAL **: 13:04:51.338: g_variant_builder_add_value: assertion '!GVSB(builder)->expected_type || g_variant_is_of_type (value, GVSB(builder)->expected_type)' failed
```

**Screenshots**
![Screenshot from 2022-11-28 12-57-56](https://user-images.githubusercontent.com/34549440/204347862-59b1d50c-b13e-402f-87d5-9a800254fdce.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37 Workstation Edition
 - Rnote v0.5.8
 - Installation source: Flatpak
 - DE: GNOME 43.1 Wayland

**Additional context**
I am unable to reproduce this bug on my Desktop (also running F37), but on my Laptop (Microsoft Surface Pro 5 with the surface-linux kernel) this bug occurs.

In Flatseal, I use default permissions, but I have added the `Filesystem > All user files` (`filesystem=home`) which I believe grants access to everything in my `$HOME` dir. Not sure if this is related.

The file picker works normally and does not hang, only the main window hangs.

**Comment by benjamin051000** [comment]
I just noticed #344, sorry. We can discuss further there

**Comment by flxzt** [comment]
Thanks for the detailed bug report! This is the same issue as #344, so I'll close this one track fixing it in there.
