### ISSUE TITLE
popup does not hide then modifying combobox setting

### ISSUE THREAD

**Issue by olbotta** [flxzt/rnote#395]
**Describe the bug**
"quick settings" popup does not hide then touching combobox setting

**To Reproduce**
1. open a "quick setting" that contains a combobox
2. click on the combobox
3. click one of the values of the combombox
4. click ouside of the popup (eg. in the page) or on the button which enables the pupup

**Expected behaviour**
popup should close like when modifying other settings

**Screenshots**
[Video explaination](https://user-images.githubusercontent.com/29437446/206224863-72ea7d8f-aa69-49e4-b063-7ffacc9459a1.webm)

**Desktop (please complete the following information):**
Fedora 37 Gnome 43 (wayland), Flatpack

**Comment by flxzt** [comment]
Thanks for the recording the video. This is the same issue as #206 so I'll close this one as duplicate. The issue seems to be a GTK bug..
