### ISSUE TITLE
Colourblind Mode

### ISSUE THREAD

**Issue by ritamsaha00** [flxzt/rnote#397]
Maybe a very small percentage of user is colourblind, but having an option that gives you colourblind friendly background colour and text/stroke colour is a huge utility feature.

If you/anyone can implement it, that would be really great.

**Comment by flxzt** [comment]
I came across this [colorblind filters](https://extensions.gnome.org/extension/5589/colorblind-filters/) gnome shell extension, which aims to correct colors at a system level

**Comment by ritamsaha00** [comment]
Yeah, I saw that on Reddit yesterday; now there is no need to add extra features to each app. It's a really awesome extension.
