### ISSUE TITLE
Reload file if file changed on disk

### ISSUE THREAD

**Issue by l0drex** [flxzt/rnote#399]
**Is your feature request related to a problem? Please describe.**
I sync my files with a cloud provider. When I have one file open on two PCs, and change it on one, rnote treats the outdated file on the other pc as a new document.

**Describe the solution you'd like**
A dialog window should pop up to let me choose which version of the file I want to keep, e.g. one button to reload from disk and one to keep the currently opened file.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by flxzt** [comment]
This sounds like the same issue as #461
