### ISSUE TITLE
Weird "Draw with mouse" option

### ISSUE THREAD

**Issue by jannuary** [flxzt/rnote#4]
When the app starts, it seems like none of the tools do anything if you're not using the app on touch. Turns out, the reason is the "Draw with mouse" option in the secondary menu, which is off by default.

What is the use case for having the mouse do nothing, and is it even important to have an option for that at all?

**Comment by flxzt** [comment]
The default is to use stylus input, which enables variable stroke width and a button shortcut (on the stylus) to enable the eraser temporarily. The mouse drawing option disables that in favor of more input methods ( basically anything that is represented as a pointer in GTK4 ).

I should probably put an explanation somewhere in the description and / or have a hint at the first app startup. the freedesktop metainfo unfortunately does not support a recommendation for a stylus (yet)

**Comment by jannuary** [comment]
This seems sorta hacky - ideally, full stylus support would work in tandem with mouse support, but I'm not versed enough in GTK or stylus input to know for sure how to achieve that.

**Comment by SeaDve** [comment]
> When the app starts, it seems like none of the tools do anything if you're not using the app on touch. Turns out, the reason is the "Draw with mouse" option in the secondary menu, which is off by default.

I also spent 5 minutes trying to figure out what's not working until I saw that option. Anyway, nice app

**Comment by Exalm** [comment]
I'd expect pointer to draw as well. Implementation-wise it would just be regular GtkGestureDrag/Pan/etc + checking the device type  would do it, but you'd have to check the input source from the handlers - not ideal but you probably already have to do that anyway.

**Comment by flxzt** [comment]
changed the default until I make it work in tandem. I think the app needs to have options to toggle the different pointer inputs for drawing and dragging the sheet though, thinking about wacom tablets where you might want to drag the screen around with the mouse and only use stylus input, or on a tablet, where you only have touch input, or on a 2in1 where you have everything and you have different personal preferences

**Comment by flxzt** [comment]
I think I'll close this as  the "Draw with mouse" option no longer exists.

**Comment by Adityashaw** [comment]
> I hope it it less confusing now, stylus and mouse drawing should work now at the same time. I refactored the "mouse drawing" setting to a "draw with touch input" setting, which should cover most user preferences.
> 
> I would love to have some feedback!

When should one `enable` the `Draw with touch input` settings? Should a drawing tablet user keep it enabled or disabled?

Sorry to ask this in issues but I don't see a documentation for same. Let me know if there's a doc (even if it is a draft version)!

**Comment by flxzt** [comment]
Well, whenever you want to draw with touch. I assume most users of touch-only tablets toggle it frequently to be able to use touch navigation as well. For users with an external drawing tablet I'd suggest to leave it disabled, but as long as there is no touchscreen connected it should not make a difference.

**Comment by Adityashaw** [comment]
> For users with an external drawing tablet I'd suggest to leave it disabled, but as long as there is no touchscreen connected it should not make a difference.

Got it now! I was thinking why this option is not doing anything but I don't have a touch screen, haha.

**Comment by PourquoiEstTu** [comment]
> I assume most users of touch-only tablets toggle it frequently to be able to use touch navigation as well.

Would really appreciate a dedicated keyboard shortcut for toggling Draw With Touch Input on and off exactly because of this. I use a "dumb" stylus that uses touch input to draw and having to go into the menu to toggle or moving to the keyboard to zoom can be a bit of a hassle.
