### ISSUE TITLE
Full screen mode and Floating Toolbar 

### ISSUE THREAD

**Issue by aanandharaja** [flxzt/rnote#40]
This software is very neat and simple, please consider about adding this features.
1. Full Screen mode for online class
2. floating bottom toolbar
3. Add option to change the cursor icon, (like pen cursor) 
Thankyou

**Comment by flxzt** [comment]
implemented full screen support. A bottom toolbar probably won't be implemented, i don't any UI at the bottom. (Right now its not needed for anything anyways, is it?)
