### ISSUE TITLE
Menu Icon stays grey

### ISSUE THREAD

**Issue by amit9838** [flxzt/rnote#421]
I have applied custom gtk-4.0 color palatte for dark theme.
![image](https://user-images.githubusercontent.com/61614402/209350893-dad7aa6a-8d9c-468e-bae0-6a7fc097d1c9.png)

**Comment by flxzt** [comment]
Does the menu open when you click it? Sounds like a theming issue to me, since the icon is non-standard. I'd suggest sticking to the default adwaita theme for Rnote, meaning not overwriting GTK_THEME.

**Comment by amit9838** [comment]
yes button is functioning properly, Ok thanks
