### ISSUE TITLE
Pasting clipboard image with stylus/right click

### ISSUE THREAD

**Issue by Shahin-rmz** [flxzt/rnote#426]
**Please submit only one feature request in one issue!**

If it is UX / UI related, don't post how a single aspect of the UI should be changed, but rather in which use case you felt the UI is lacking or should be improved.

**Is your feature request related to a problem? Please describe.**
When I am on Tablet mode, it is not easy to paste an image using ctrl+v.
Is there a solution paste clipboard only by mouse/pen in Rnote?

**Describe the solution you'd like**
an option in setting, that sets the behavior of second button of the mouse to open a small menu, so we can choose next tool. there will be also `paste` option.

**Describe alternatives you've considered**
a paste button on the upper bar of the app.

**Comment by Heiseneberg-maybe** [comment]
You can paste by going in the hamburger menu and selecting "Clipboard", a menu will open and in that menu you'll find the paste option. 
Alternatively you can select the option "Import file" in the hamburger menu and select the image or file (using the file picker dialog) that you want to import
