### ISSUE TITLE
open  Rnote files on Android device

### ISSUE THREAD

**Issue by Shahin-rmz** [flxzt/rnote#427]
Hello, it is not a feature request, but I couln't find any other ways to ask this question.
is there any ways to open `.rnote` files on Android devices?

Ps. **Rnote is AWESOME**.
**THANK YOU FOR SHOWING LINUX SUPERIORITY WITH POWER OF RUST.**

**Comment by Heiseneberg-maybe** [comment]
There isn't yet.
This is a duplicate of  #390

**Comment by Shahin-rmz** [comment]
Thanks
closed as duplicate.
ps:
Happy new year. :champagne:
