### ISSUE TITLE
Download icon used for save button instead of a save icon

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#428]
**Describe the bug**
The save button in the top left uses a download icon instead of the normal floppy diskette to represent saving, which just isn't intuitive and is confusing.

**To Reproduce**
1. Look at the top left save icon
2. It's a download icon

**Expected behavior**
The save button should use a save icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/50517631/210158890-cf69a022-c014-4692-be35-cc4fd5390ca7.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 37
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.2

**Comment by flxzt** [comment]
In this case I am simply following what Gnome has as save icon. I can see that it is ambiguous / confusing at first, but since other apps are using the same icon as well there are benefits to keep it consistent with them. Maybe this should be opened as an issue in the gnome design repository.

**Comment by flxzt** [comment]
I'll close it for now, because I want Rnote to be consistent with the rest of the ecosystem.
