### ISSUE TITLE
Import PDF pages are not aligned with rnote pages

### ISSUE THREAD

**Issue by romanovzky** [flxzt/rnote#429]
**Describe the bug**
When I open a PDF through rnote, the pages are not aligned with rnote pages.

**To Reproduce**
1. Right click on pdf
2. Choose "Open Width"
3. Choose "rnote"

(same happens when importing the pdf from a new rnote window)

**Expected behavior**
The pages to be aligned.

** Console Output **
There was no output.

**Screenshots**
![Screenshot from 2023-01-02 11-07-57](https://user-images.githubusercontent.com/7794475/210246541-45febfc2-980a-4e53-8a81-ea098aefe052.png)
![Screenshot from 2023-01-02 11-07-18](https://user-images.githubusercontent.com/7794475/210246553-dca82807-62d9-4bb8-9347-4e57344d4892.png)
![Screenshot from 2023-01-02 11-07-27](https://user-images.githubusercontent.com/7794475/210246556-f72a29a8-25a2-4d09-afc2-56bce8b58b92.png)
![Screenshot from 2023-01-02 11-07-33](https://user-images.githubusercontent.com/7794475/210246561-36221f9d-da1a-405e-a99b-88f7a2ce13af.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS (rolling distro and kept up-to-date)
 - Version: Rnote: 0.5.12
 - Installation source: flatpak
 - Desktop Environment: Gnome 43.2

**Comment by flxzt** [comment]
It is not really a bug, the offset there is intentional. I'd say simply reducing the import page width percentage should be a solution, and / or aligning it manually after import.

A dedicated PDF annotation mode is also planned, the issue for that is #153 .

**Comment by LuckyTurtleDev** [comment]
I hit the same issue.

> I'd say simply reducing the import page width percentage should be a solution, and / or aligning it manually after import.

I do not think this would be a good solution. It looks like the pdf side does match the side of rnote exactly it has only a offset to the bottom right.
The PDF annotation will be an alternative for simple drawing on pdf. But users, witch does still want to add a pdf to an existing note, will still hit this issue.
Maybe an option to map the pdf pages to the rnote pages would be a good solution.
The current solution (manual trying to hit exactly the site borders) is pretty annoying.

**Comment by flxzt** [comment]
> Maybe an option to map the pdf pages to the rnote pages would be a good solution.  
 
That is basically what I want to do as an annotation mode. There are some details I didn't work out yet though.

This way users can get both: Either import the pdf pages as individual images and can be moved and transformed freely like right now, and a dedicated mode where the layout is managed automatically. This would also enable retaining the pdf in a richer way so that new features that modify the pdf directly can be implemented in the future

**Comment by flxzt** [comment]
I'll close this, the PDF annotation mode feature progress is tracked in the other issue
