### ISSUE TITLE
Resizing image glitch

### ISSUE THREAD

**Issue by JanDeDinoMan** [flxzt/rnote#43]
When attempting to resize an image using my laptops touchscreen the image will glitch to seemingly random sizes before becoming the correct size.
Note that this only happens when a secondary display is connected!
This is on Pop!_OS 21.10 with Rnote 0.2.5 Flatpak

https://user-images.githubusercontent.com/23642000/149985295-3a305e24-4b98-4a85-bc92-9b1405e8d9cf.mp4

**Comment by flxzt** [comment]
v0.3.0 refactored the selector, please report back if this still happens with the newest version.

**Comment by flxzt** [comment]
Closing due to no response.
