### ISSUE TITLE
Poor clarity on vector pdfs at lower zoom levels

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#431]
**Describe the bug**
When you import a pdf with vector text, the rendered text is not sharp at lower zoom levels unless you zoom in further than you want too, then zoom out.

**To Reproduce**
1. Open a pdf with vector text in rnote.
2. While using rnote in a regular horizontal window, zoom out until the entire pdf fits vertically in view - page top and bottom aligns with top and bottom of rnote view.
3. Observe text in pdf and its clarity. For me, the smaller text looks blurry.
4. Zoom in onto the pdf until the pdf page fills the horizontal view of rnote. The text should be larger, and clearer than before.
5. Zoom out to the same level as previously - so pdf page fits in vertical view of rnote. The text is now smaller, but remains clearer than initially.
6. If you zoom out to far, the scaling/rendering catches up, and the text becomes blurry again.

**Expected behavior**
Vector text from pdfs should always be clear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50517631/210452780-5b8384ee-ec32-49a9-83ff-8e5873fd4bad.png)
![image](https://user-images.githubusercontent.com/50517631/210452534-80c3ab23-32b9-4a27-94e7-b4ccb81cc758.png)
![image](https://user-images.githubusercontent.com/50517631/210452560-59de063e-9b4e-407f-9921-3b0f8a50b96d.png)
![image](https://user-images.githubusercontent.com/50517631/210452687-b81fa81b-7a4e-4809-8a32-b87216e2e284.png)

**Desktop (please complete the following information):**
 - OS: Fedora: 37
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.2

This is quite difficult to show in screenshots, as the resolution is not native to your screen, however, it is very obvious once you realise it when actually using the program.

**Comment by flxzt** [comment]
I think the asymmetry of the sharpness after zooming in / out should be fixed now, I don't think I can do much about the text-antialiasing of the svg renderer. I'd appreciate feedback. :)

**Comment by flxzt** [comment]
Additionally, with 43904619f4705e406003c1365190925871287ed5 there is now a bitmap image scaling option, to make the bitmap import a more useful alternative

**Comment by flxzt** [comment]
Should be fixed with b9923bc65b767028e47a952ef77ae0fcedb2cab6
