### ISSUE TITLE
Pressing the save button rapidly after having made changes causes a crash

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#432]
**Describe the bug**
After having made a stroke, tapping the save button rapidly crashes the program. This causes data loss.

**To Reproduce**
1. Make a stroke with a stylus
2. rapidly press the save button a couple times
3. Save icon says highlighted, program stops responding, then hard crashes.

**Expected behavior**
Should either rate limit saving or only allow saving once at a time, so saving many times at once does not crash the program.

** Console Output **
( remind me to do this later, I don't have time for it rn)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.2

**Additional context**
I just press the save button a couple times without thinking, not sure how many times you need to do it exactly to cause a crash.

**Comment by Shahin-rmz** [comment]
I second this.
I write uni notes with Rnote and summerization.
When the size of the `.rnote` file expands around 15 MB, the app has trouble saving and and I afraid to loose notes.
Any solution to that?
PS. I love Rnote. Just can wish if it was more stable.

**Comment by flxzt** [comment]
Is already fixed, will be included in the next release
