### ISSUE TITLE
Windows build CI/Action for releases 

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#433]
Installing visual studio and other dependencies isn't viable for people who just want to use the app without developing for it.
Unless I'm just not seeing it on the repo, there's no pre-built binaries for it.

If you do make a installer, you could try submit the windows build to the [the windows package manager community repo](https://github.com/microsoft/winget-pkgs), but that would require creating schemas (which i have no experience making 😆 )

**Comment by LeSnake04** [comment]
This might help: https://www.collabora.com/news-and-blog/blog/2021/04/29/build-your-own-application-with-gtk4-as-a-meson-subproject/
