### ISSUE TITLE
Popup warning about file change, prompting for a reload, after saving 

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#434]
**Describe the bug**
After saving your notes, a popup appears at the bottom, telling you that a change was made and prompts you to reload. This makes sense if it was modified by another instance of rnote, but is unnecessary when you have just saved it in the same program.

**To Reproduce**
1. Create a blank note and save it.
2. Make any change on the note.
3. Save the note.
4. Popup prompting a reload appears.

**Expected behavior**
Program does not prompt a reload when it is what initiated the file changing on disk.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.2

**Additional context**
A simple fix would be storing the hash of the rnotes file after saving it, then having the function that prompts a reload to only call if the hash of the rnotes file has changed since the last save (or if no save hash exists because the notes haven't been saved since opening).

**Comment by Kneemund** [comment]
Which version of rnote are you using?

**Comment by wiryfuture** [comment]
> Which version of rnote are you using?

0.5.12

**Comment by flxzt** [comment]
@wiryfuture are you getting this only when you are saving a new file or is this also the case after loading in an existing one?

**Comment by wiryfuture** [comment]
> @wiryfuture are you getting this only when you are saving a new file or is this also the case after loading in an existing one , modifying and then saving it?

both - it always shows.

**Comment by flxzt** [comment]
I think I know what was happening, and I am fairly confident that #452 will fix this

**Comment by flxzt** [comment]
@wiryfuture could you try the newest beta that includes the fix?

**Comment by wiryfuture** [comment]
> @wiryfuture could you try the newest beta that includes the fix?

Is the build available on flathub by any chance? I can't remember how to get betas off there

**Comment by flxzt** [comment]
yes, it is published in the flathub beta repo. Check here: https://discourse.flathub.org/t/how-to-use-flathub-beta/2111 

The beta should then appear as an entry in software, or ask you which repo when installing it via cli

**Comment by wiryfuture** [comment]
> @wiryfuture could you try the newest beta that includes the fix?

seems to

**Comment by flxzt** [comment]
Could you run the app with `RUST_LOG=rnote=debug flatpak run com.github.flxzt.rnote` and post the logs when it happens with the autosave?

**Comment by wiryfuture** [comment]
Quick note, I have also found that the autosave popping up steals your focus if you are writing with the stylus and you need to left the stylus off the screen and place it down again to be able to write again.

**Comment by wiryfuture** [comment]
> Could you run the app with `RUST_LOG=rnote=debug flatpak run com.github.flxzt.rnote` and post the logs when it happens with the autosave?

running it like this does not give me any logs, the terminal stays blank.

**Comment by flxzt** [comment]
huh, you're right, it doesn't log at all with the released flatpak builds currently. Let me look into that, meanwhile you don't have set up building from the git repo by chance?

**Comment by wiryfuture** [comment]
I've just tried this, but tbh it seems to have disappeared on its own after a while and now it just doesn't happen (on the same version), so I can't reproduce it anymore.

**Comment by flxzt** [comment]
Not the resolution I had hoped for. The bug might still be there, but might not trigger for you any longer. If you encounter it again, please reopen

**Comment by wiryfuture** [comment]
yes
