### ISSUE TITLE
Split eraser only erasing one segment at a time

### ISSUE THREAD

**Issue by D0V4HKIIN** [flxzt/rnote#438]
**Describe the bug**
The split eraser only erases one segment at a time which makes that when deleting a long line with a big eraser tool, you can see the line slowly getting erased.

**To Reproduce**
1. Draw a long line
2. Select the eraser tool and set it to split eraser and set it's size to something big like 400
3. Erase the line
4. Observe the line getting deleted slowly

**Expected behavior**
I expect the line to be deleted immediately instead of having to wait for every single stroke to get deleted.

https://user-images.githubusercontent.com/43830391/211166008-e00f63b9-aff9-420b-bfea-72bfa3df4980.mp4

**Comment by D0V4HKIIN** [comment]
I played a bit with the code on my fork but my solution feels more like a workaround than a fix.
https://github.com/d0V4HKIIN/rnote/tree/eraser

**Comment by flxzt** [comment]
That does look like a workaround, but I appreciate the effort. I modified hittest() so that it returns all colliding segment indices, and am iterating over them to create new split strokes. @D0V4HKIIN can you test the fix, in branch `fix-split-strokes`, just to make sure it works as intended?

**Comment by D0V4HKIIN** [comment]
> That does look like a workaround, but I appreciate the effort. I modified hittest() so that it returns all colliding segment indices, and am iterating over them to create new split strokes. @D0V4HKIIN can you test the fix, in branch `fix-split-strokes`, just to make sure it works as intended?

I don't have much time lastly, but i will test the main branch now that it has been merged.
