### ISSUE TITLE
Rnote not detecting pressure from Surface Pen

### ISSUE THREAD

**Issue by JonathanMathBoi** [flxzt/rnote#448]
**Describe the bug**
When using a Surface pen on Rnote, the pen acts like a mouse and ignores all pressure input. The eraser also acts as a mouse input rather than as a pen eraser input.

**Expected behavior**
When using a Surface pen on Rnote, the pen should be recognized as a pressure sensitive pen and the eraser should act as a pen eraser input.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation source: Flatpak
 - Desktop Environment: KDE 5.26.5
 - Display Server: X11

**Additional context**
This issue only occurs in Rnote and not in other applications such as Xournalpp, where the pen is recognized properly and is pressure sensitive, and the eraser acts as an eraser. This issue is specific to using Rnote.

**Comment by flxzt** [comment]
Lets keep this issue in #194
