### ISSUE TITLE
Scroll by Dragging without Scrollbar

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#45]
Hi, 

when I'm working on a document with a wacom tablet pen, scrolling a sheet is cumbersome, since hitting the scrollbar is not so easy. 

A second option to move the sheet up and down would be to make the grey fields next to sheet itself a dragging target, 
that is, once the pen pointer hits the grey field, moving it up and down moves the sheet accordingly.

**Comment by redtrumpet** [comment]
I would especially like to be able to scroll by pressing the button on my Wacom pen. Similarly to how scrolling works in most drawing software.

**Comment by flxzt** [comment]
Related to #18 to add as a button action, but I think dragging with the mouse in the grey fields is also a good idea.

**Comment by flxzt** [comment]
The newest release added scrolling by dragging with the stylus on the side. What I also noticed, at least on my machine, when you hover and press the second stylus button, GTK emulates a middle mouse button which also can be used to scroll.

Configurable actions for the buttons will come some time later, but I wanted to share that in case you missed it.

**Comment by maymage** [comment]
Hi, 

thanks for the tip. I will try it out, when I'm back in my office - in case it's already on flathub?!?

> Configurable actions for the buttons will come some time later, but I wanted to share that in case you missed it.

Good to know - the dragging-on-grey feature will be useful to free up a pen button action then.. 

---

Btw a big thanks to you: I use this app now basically daily and it has served me well in an online job interview the other day \o/

**Comment by flxzt** [comment]
v0.3.0 is [published](https://flathub.org/builds/#/builders/32/builds/76372), but from my experience it takes up to an hour to show up in `flatpak update`, and a little more in gnome software.  
Well thank you! Awesome to hear that it is actually used "in production"

**Comment by maymage** [comment]
Hi.. just tested this new feature. Works flawlessly. 

Hence closing.
