### ISSUE TITLE
Secondary click does not work as intended

### ISSUE THREAD

**Issue by mackdroid** [flxzt/rnote#457]
**Describe the bug**
Secondary tool/click using mouse no longer follows the cursor as intended

**To Reproduce**

1. Open rnote
2. Use the secondary button action

**Expected behavior**
The tool follows the cursor

** Console Output **
```
DEBUG rnote::app::imp > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 16:19:14.575: The layout manager of type GtkBoxLayout 0x7fde30006420 does not create GtkLayoutChild instances
```

**Screenshots**
[Screencast from 2023-01-19 16-05-30.webm](https://user-images.githubusercontent.com/68280146/213423610-15e1f439-7bc1-4a42-8377-eca12bfcd222.webm)

**Desktop (please complete the following information):**
 - OS: Vanilla OS (tested also on fedora silverblue)
 - Version: 22.10
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.1

**Comment by flxzt** [comment]
I can't reproduce unfortunately.

**Comment by flxzt** [comment]
The latest app updates did not touch this, so it sounds like that. Thanks for remembering and resolving the issue.
