### ISSUE TITLE
Image pasting, from file system or clipboard not working

### ISSUE THREAD

**Issue by diminDDL** [flxzt/rnote#458]
**Describe the bug**
When trying to drag and drop/ctrl+v images from clipboard or file explorer nothing happens. It used to work flawlessly earlier.

**To Reproduce**
1. Open rnote
2. Try dragging a PNG into the drawing area
3. Nothing happens

**Expected behavior**
The image would be pasted into the drawing area.

**Console Output**
Run the app in the terminal with ` flatpak --env=RUST_LOG=rnote=debug run com.github.flxzt.rnote` and post the output
```
~$ flatpak --env=RUST_LOG=rnote=debug run com.github.flxzt.rnote
 DEBUG rnote::app::imp > ... env_logger initialized


```
Output is empty.

**Desktop (please complete the following information):**
 - OS: KDE neon 5.26 x86_64
 - Version rnote version 0.5.12
 - Installation source Flatpak
 - Desktop Environment KDE plasma 5

**Additional context**
More system information:
```
Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.15.0-58-generic (64-bit)
Graphics Platform: X11
```

**Comment by flxzt** [comment]
Does Rnote have at least read permissions to the directory where the file is located? You can grant it in flatseal. I can't repro, clipboardpasting and drag & drop works fine here. Except for SVG clipboard pasting, but that is a known issue

**Comment by diminDDL** [comment]
Giving it all file permissions allowed me to use ctrl+c, ctrl+v of files however not drag and dropping from Dolphin.

**Comment by flxzt** [comment]
hm, in a VM with KDE and the flatpak drag & drop works fine for me. Are you sure this is not a directory access permissions problem?

**Comment by diminDDL** [comment]
It used to work just fine, I will try downgrading and see if that changes anything to determine if maybe something in KDE Neon changed regarding permissions.

**Comment by flxzt** [comment]
I noticed you only mentioned images, is this for all files or really only bitmap images?

**Comment by diminDDL** [comment]
Idk what else I could drag and drop, but it works on text with flat seal file access enabled. And with downgrading it still kept the current behavior, so this seems to be a KDE issue.

**Comment by flxzt** [comment]
other files to drag & drop onto the canvas could be: `.rnote` save files, `.xopp`, `.svg`, `.pdf`
