### ISSUE TITLE
Windows build info

### ISSUE THREAD

**Issue by avacadox21** [flxzt/rnote#46]
Before, build tutorial for windows was present on readme.md, can you give few little lines on it

**Comment by flxzt** [comment]
I think you're refering to what is now in CONTRIBUTING.md, but there never were any build instructions for windows.  
But if someone manages to do it, please report back so I can add them, maybe we could even ship a installer (although linux / flatpk will probably stay the target I am focusing on the most)

**Comment by avacadox21** [comment]
Can I build it with cargo?

**Comment by flxzt** [comment]
No, rnote uses meson as its build system

**Comment by flxzt** [comment]
There is this docker image that could be used to cross-compile to windows, if anyone wants to have a go at it. https://github.com/MGlolenstine/gtk4-cross

**Comment by VodnikAngus** [comment]
To not show the cmd window on windows when app launches you have to mark app as gui adding cli flag '-mwindows' should do the trick. More info: http://users.wfu.edu/cottrell/cross-gtk/

**Comment by flxzt** [comment]
Should have mentioned this here too, I already experimented with a windows build and documented my steps [here](https://github.com/flxzt/rnote/blob/main/misc/building/rnote-windows-build.md).

**Comment by flxzt** [comment]
@iwoithe If you would be willing to create a script, that would be very nice. On my machine I am getting a lot of UTF8 parsing errors though, resulting in a lot of blank labels in the app, did you experience that too?

**Comment by iwoithe** [comment]
> On my machine I am getting a lot of UTF8 validation errors though, resulting in a lot of blank labels in the app, did you experience that too?

I haven't actually re-built it in a few weeks but I will check if this occurs for me too (this was not an issue when I built rnote the first time).

> @iwoithe If you would be willing to create a script, that would be very nice.

I am happy to do this. Would you like it to be a Bash or Python script?

**Comment by flxzt** [comment]
For windows a python script might be better. It could then be extended to create a installer at some point I think? If somebody has expertise with that and would like to help, I would really appreciate it!

**Comment by iwoithe** [comment]
> For windows a python script might be better.

I'll start working on it.

> It could then be extended to create a installer at some point I think?

Yeah, this would be good. I am happy to do this. I'd prefer using Inno Setup as that is what I've had experience in but I am fine to use another setup installer creator if you wish.

**Comment by flxzt** [comment]
Whatever works best for you! I read that Inno is most pleasant to write and the only real downside is that it can only produce .exe files, not MSI. But I don't really think we need to worry about this at the moment.

**Comment by flxzt** [comment]
I think this should be solved, there are (currently) up to date and tested instruction how to build on windows available here: https://github.com/flxzt/rnote/blob/main/misc/building/rnote-windows-build.md
