### ISSUE TITLE
Pinch to Zoom gesture incorrectly triggers current tool on 5.13 Beta

### ISSUE THREAD

**Issue by fotnite-vevo** [flxzt/rnote#466]
**Describe the bug**
Using the pinch to zoom touchscreen gesture causes the currently selected tool to trigger at the position of one of the fingers used to pinch (doesn't affect pinch to zoom touchpad gesture).

Behavior when selecting the Brush tool is especially strange, it appears a single pivot is made every time the gesture is used, and all of the pivots are part of the same stroke. This has the appearance of looking like a "polygon tool".

5.12 does not exhibit this issue.

**To Reproduce**
1. Attempt to pinch to zoom

**Expected behavior**
Pinch to zoom does not do anything apart from zooming in/out from the canvas

** Console Output **
If the Brush tool is selected, this console output is seen on every use of the gesture:
`rnote_compose::builders:penpathmodeledbuilder > penpathbodeledbuilder : update_modeler_w_element(): n_steps exceeds configured max outputs per call, restarting modeler`

No console output displays for other tools.

**Screenshots**
Strange behavior seen when using Brush tool: 
![Screenshot from 2023-01-23 16-36-05](https://user-images.githubusercontent.com/68102115/214176575-7698b276-203f-4847-9692-5092641b8dfc.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: N/A
 - Installation source: Github Repo & AUR
 - Desktop Environment: 43.2

**Comment by flxzt** [comment]
This has to be the fastest bug report I have ever seen :P Are you building off main? I just pushed 9300862d38ffd4e952c9c1323541abb7ded79d66 which should at least fix this bug ( still logs an error though, I am wrestling with handling gesture state a little bit )

**Comment by fotnite-vevo** [comment]
Or maybe my timing's just unlucky. This isn't the first time I've installed something during the ~ 2 hour window it's broken.

Yeah, I was building from the commit just before that. I just rebuilt from the most recent one and the main issue seems to be fixed, though I am seeing the error you mentioned as well. Nothing to do but to close it, keep up the good work!

**Comment by flxzt** [comment]
btw. I wouldn't recommend using upstream for documents you care about, only for testing and trying out new stuff. Things might break
