### ISSUE TITLE
(Regression on beta) Pen options reset to default if you open a file

### ISSUE THREAD

**Issue by wiryfuture** [flxzt/rnote#468]
**Describe the bug**
Pen options, such as the pressure curve and stroke dots position distribution, reset to 'Linear' and 'Normal' when you open a file. The stroke width is stored however.
The pen options are saved for the default "new document" that appears when you open rnote, but reset to default when you open a file.

**To Reproduce**
1. Open rnote.
2. Open a .rnote file
3. Set pen stroke dots position distribution or pressure curve to any non default option, then close rnote.
4. Open rnote again
5. Open the file
6. The options have reset back to Linear/Normal.

**Expected behavior**
Options should save between sessions and files.

**Desktop (please complete the following information):**
 Fedora 37, Gnome 43.2, flatpak beta

**Comment by flxzt** [comment]
was an oversight from the refactor for the tabs feature ( #437 ). All options should sync with the UI correctly now.
