### ISSUE TITLE
Error in Building rnote on Mac OS X

### ISSUE THREAD

**Issue by coccopuffs** [flxzt/rnote#472]
**Introduction**
Hello, this is my first time attempting to build rnote on Mac. I come from a data science background and am weak in development. I was hoping someone could help me or point me in the right direction. Thanks!

When running the following line in the tutorial for building rnote on Mac...
`meson compile -C _mesonbuild`

I run into this error...
`[28/31] Generating app-cargo-build with a custom command
/bin/sh: /usr/bin/python: No such file or directory
FAILED: rnote 
/usr/bin/python /Users/mahesh/rnote/build-aux/cargo_build.py /Users/mahesh/rnote/_mesonbuild /Users/mahesh/rnote CARGO_HOME=/Users/mahesh/rnote/_mesonbuild/cargo-home /Users/mahesh/.cargo/bin/cargo '--manifest-path /Users/mahesh/rnote/Cargo.toml --target-dir /Users/mahesh/rnote/_mesonbuild/target -p rnote --release' /Users/mahesh/rnote/_mesonbuild/target/release/rnote /Users/mahesh/rnote/_mesonbuild/rnote
[31/31] Generating rnote-ui/data/com.g...ote.metainfo.xml with a custom command
ninja: build stopped: subcommand failed.`

**My Attempts to Fix The Situation**
1. I went into /usr/bin to examine the python directory. It was named python3 instead. Thinking this was the issue I attempted to rename the folder to python3, but ran into an error doing so.

2. I also tried changing python to python3  in these following lines of code located in  /rnote/_mesonbuild/build.ninja. When running the altered build.ninja, the terminal output stated ninja ran into a lexing error. 

`build rnote: CUSTOM_COMMAND ../rnote-compose/src/builders/cubbezbuilder.rs ../r$
 pool = console
 COMMAND = /usr/bin/python /Users/mahesh/rnote/build-aux/cargo_build.py /Users/$
 description = Generating$ app-cargo-build$ with$ a$ custom$ command`

**Desktop Version**
 - OS: [Mac OS X]
 - Version [12.6.2]
 - Installation source [Source Code on Github]

**Comment by flxzt** [comment]
also if you `git pull` to the lasted commit this should be resolved, as the build script now is using `#!/usr/bin/env python3`

**Comment by dehesselle** [comment]
@coccopuffs We do have a macOS app now. Does that help or is your main focus to build it yourself?

**Comment by dehesselle** [comment]
@flxzt No response from OP, I think you can close this one.
