### ISSUE TITLE
Pen colors synced between open documents in UI but not in practice

### ISSUE THREAD

**Issue by PJansky** [flxzt/rnote#475]
**Describe the bug**
When changing the pen color in a document, the selected color in the UI is changed in all other open documents. This syncing only effects the UI but not the color of the actual pen strokes. It is therefore possible, that the selected color in the UI doesn't match the color of the pen stroke, if the pen color was changed in a different document.  

**To Reproduce**
1. Open two rnote documents
2. Change the pen color in one (the pen color is updated in both)
3. The new pen color only affects the document where the color was changed

**Expected behavior**
The pen color of each document should be independent and the UI should reflect this.

**Screenshots**
[Screencast from 27.01.2023 11:33:22.webm](https://user-images.githubusercontent.com/46072333/215067572-1a703acf-b0d2-4b55-97cc-8cf4bd83d2a9.webm)

**Comment by flxzt** [comment]
ah yes, multi-window was long overlooked. should be fixed
