### ISSUE TITLE
support pen/earse/select quick switch

### ISSUE THREAD

**Issue by jeffrey4l** [flxzt/rnote#481]
**Please submit only one feature request in one issue!**

Now we have to use `ctrl+<num>` to switch between tool and it is permanent. And it is not convenient to type. 

**Describe the solution you'd like**

Is it possible to support fast tool switch through one key on keyboard? like

* when ctrl is pressed: switch to earse temperary.
* when shift is pressed: switch to Selector temperary
* when space is pressed: we can drag the canvse temperary

**Describe alternatives you've considered**

now we have button shortcuts feature to support fast and temperary tool switch , but it only limit to stylus two button and mouse right button.

**Comment by flxzt** [comment]
Regarding dragging the canvas, it is already possible with `Alt + Drag`, and zooming with `Alt + Shift + Drag`

Using **only** the modifiers (Ctrl, Alt) as shortcuts won't work / is not something that should be done.

However it would be an improvement to let users remap the default `ctrl+<num>` ones. There is already an issue for it ( #18 ) .

**Comment by Heiseneberg-maybe** [comment]
>Regarding dragging the canvas, it is already possible with Alt + Drag, and zooming with Alt + Shift + Drag

I just noticed that these shortcuts do not appear in the Shortcuts window. 
I am using version 0.5.13-beta4 of Rnote

**Comment by flxzt** [comment]
Unfortunately there is [no support](https://docs.gtk.org/gtk4/enum.ShortcutType.html) to visualize drag gestures combined with keyboard shortcuts, but I'll add these entries with "Alt + Shift + Drag" and "Alt + Drag" as subtitles.
