### ISSUE TITLE
Bring back scrollbars

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [flxzt/rnote#496]
**Please submit only one feature request in one issue!**

**Is your feature request related to a problem? Please describe.**
I have a cheap drawing tablet that has no programmable shortcut buttons. I was happy to discover the scrollbars in the top and right sides of the page which I could use with my pen. While it wasn't as convenient as shortcut keys, it certainly made it easier for me to scroll around without using my touchpad or mouse. However, once I updated to 0.5.13, I was disappointed to find that the scrollbars were gone.

**Describe the solution you'd like**
I simply just want my scrollbars back man

**Describe alternatives you've considered**
Maybe scrolling buttons? Similar to how the undo/redo buttons used to be floating in the top left.

**Additional context**
Old version:
![Screenshot from 2023-02-07 14-18-13](https://user-images.githubusercontent.com/60950821/217343736-97e93854-e1b4-47b1-b8e1-919a0c059756.png)

New version:
![Screenshot from 2023-02-07 14-14-46](https://user-images.githubusercontent.com/60950821/217343766-c482eb34-9711-4a51-a90a-928e1c3a995e.png)

**Comment by flxzt** [comment]
Hey **man**, I am aware that some rely on scrollbars for navigation. Check the settings, you can re-enable them.

**Comment by Stephen-Hamilton-C** [comment]
Ah, I see it. Although it was turned off. When I turned it on and off again, the scrollbars came back. Thanks!

**Comment by flxzt** [comment]
btw. there is also alt + drag to move the canvas, if you have that as a key on the tablet
