### ISSUE TITLE
Create an option to disable floating toolbars

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [flxzt/rnote#497]
**Please submit only one feature request in one issue!**

**Is your feature request related to a problem? Please describe.**
I loved the appearance of RNote 0.5.12. The toolbars were attached to the sides and your infinite page was in the center waiting to be used. Now, with 0.5.13's floating toolbars, I feel slightly constrained. Like there's paper I can see, but there's a toolbar in the way. Whereas before, the toolbars felt like they were out of the way so I could see the entire page.

This, ~~combined with missing scrollbars~~ (realized it was just a stuck setting) is actually making me stay with 0.5.12.

**Describe the solution you'd like**
Just a simple toggle switch in settings that can attach the toolbars back to the sides of the window. Maybe something like "Enable Floating Toolbars" and it defaults to on.

**Describe alternatives you've considered**
Perhaps just reverting back to the original style.

**Additional context**
Old toolbars:
![Screenshot from 2023-02-07 14-19-34](https://user-images.githubusercontent.com/60950821/217345060-fa71bc84-3c74-45de-b1f8-dc46ce7b5be8.png)

New toolbars:
![Screenshot from 2023-02-07 14-19-55](https://user-images.githubusercontent.com/60950821/217345080-15dde310-4c75-4d0b-86f3-c36ef2a46c05.png)

**Comment by flxzt** [comment]
Happy to iterate on the current design, there is already discussion in another issue. But there won't be an option to revert to the old layout, it didn't work anymore with other changes like tabs and the global colorpicker and it would be a huge maintenance burden.

And realistically it is a net gain of available space to the canvas, by eliminating most of the empty space of the toolbars.
