### ISSUE TITLE
Headerbar papercuts 

### ISSUE THREAD

**Issue by jannuary** [flxzt/rnote#5]
- The app icon in the top left isn't something that's done anymore. It's especially weird since it doesn't appear to do anything, even though it does appear clickable with the new styling.
- The position of the panel between tools and menus is weird: it's not really aligned to anything, so it looks odd visually. I'd recommend placing New and Undo/Redo on the left, before the tools.
- It's not intuitive what "Fit to Format" does - the icon is unusual and there is no immediate feedback after pressing it.

![image](https://user-images.githubusercontent.com/27908024/135751417-01c6ded9-d835-42f7-bc7d-7c48264dcaa4.png)

**Comment by flxzt** [comment]
My attempt on fixing it:

![Bildschirmfoto vom 2022-05-01 09-56-13](https://user-images.githubusercontent.com/19841886/166137350-51a1690e-d5c9-4021-9d02-7b88707ef130.png)

**Comment by flxzt** [comment]
@jannuary do you have a suggestion for a better icon for the "fit to format button"?
