### ISSUE TITLE
rnote crashes when using the arrow keys to navigate within a textbox containing special characters

### ISSUE THREAD

**Issue by p-mng** [flxzt/rnote#500]
**Describe the bug**
rnote tends to crash when using the arrow keys to navigate within a textbox containing special characters like `σ`.

**To Reproduce**
1. Create a new document containing just a textbox
2. Add the following two lines to the textbox
    1. `σ`
    2. `σ`
3. Put the cursor at the end of the first line and try to navigate down.
4. Crash

**Expected behavior**
rnote does not crash.

**Console Output**

    thread 'main' panicked at 'assertion failed: self.text.is_char_boundary(idx)', /usr/src/debug/rnote/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/piet-cairo-0.6.2/src/text.rs:444:9

**Desktop**
 - OS: Arch Linux, fully updated as of 2022-02-08
 - Version: 0.5.13
 - Installation source: Archlinux Community Repo
 - Desktop Environment: Gnome 43.2

**Comment by flxzt** [comment]
Seems to happen only when the last character of the entire text is non-ascii, then the cursor doesn't land on a character boundary and therefore panics

**Comment by p-mng** [comment]
Seems to also happen with the following text with `%` as the last character:

    σ² = 0,4² * 0,06² + 0,6² * 0,09² + 2 * 0,4* 0,6 * 0,00515 ≈ 0,0059
    σ ≈ 0,0768 ≈ 7,68 %

Put the cursor at the beginning of the second line, insert a tabstop and use the arrow keys to move up and the program will crash. This only happens if there is no word wrap withing the lines.

**Comment by flxzt** [comment]
It is/was a general logic error when calculating the offset of the cursor when jumping to the next line. Worked fine in most cases when a character has only one byte length (ascii) but it occasionally jumped "between" boundaries.

The fix here is to hittest based on the x offset of the current, it matches human intuiton better anyways for non-monospace fonts
