### ISSUE TITLE
Left side of semi infinite layout hard to use

### ISSUE THREAD

**Issue by D0V4HKIIN** [flxzt/rnote#502]
**Is your feature request related to a problem? Please describe.**
When using semi infinite layout with the new floating menu on the left, it has become very hard to write on the far left of the canvas because it is mostly covered by the floating menu. See screenshot. This was not the case before with the old style menu.

**Describe the solution you'd like**
There could be a bigger padding between the side of the window and the canvas so that the menu is not covering the canvas when fully scrolled to the left.

**Describe alternatives you've considered**
Reverting back to the old style menu but i don't think that is a good idea.

![image](https://user-images.githubusercontent.com/43830391/217872204-61a70f7f-3b47-43ab-a261-8ec16fff7741.png)

**Comment by flxzt** [comment]
Oh true, I didn't consider that. We could simply increase the value of the horizontal margins `const` to make room for it, like I did with the vertical margins.
