### ISSUE TITLE
Crash on Launch with latest version

### ISSUE THREAD

**Issue by LeSnake04** [flxzt/rnote#504]
**Describe the bug**
When I launch the app, it  instatly crashes. 

**To Reproduce**
1. Start App

**Expected behavior**
Lauch Application.

** Console Output **
Run the app in the terminal with ` flatpak --env=RUST_LOG=rnote=debug run com.github.flxzt.rnote` and post the output
```
(rnote:2): Gtk-WARNING **: 09:23:12.573: GtkImage 0x55a73e06f300 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 09:23:12.573: GtkImage 0x55a73e06f490 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 09:23:12.582: GtkImage 0x55a73e085470 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 09:23:12.582: GtkImage 0x55a73e085600 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', rnote-ui/src/strokewidthpicker/strokewidthpreview.rs:97:35
```

(Will update with full output when I have time to recreate the issue again)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 36 
 - Installation source: Flatpak [e.g. Flatpak, Archlinux Community Repo, ... ]
 - Desktop Environment: Gnome 42  [e.g. Gnome 41.2]

**Additional context**
Downgrading to 5.12 Fixes it: 
```
sudo flatpak update com.github.flxzt.rnote --commit=616c2ce6a571a837860eba621658a3b0b4a2a5812cca226c807cd2f1ea9702e9                                                                                                                   
```

**Comment by flxzt** [comment]
Do you have a custom theme stylesheet that overwrites the default adwaita one? It seems like `window_fg_color` was not found, which should be defined in the stylesheet. In any case, this shouldn't cause a panic so I'll make it fall back to black

**Comment by flxzt** [comment]
fixed with 6f4976025d3f76591b5014c8cb7b394e9ddbfa01

**Comment by LeSnake04** [comment]
I tried to get gradience working in the past (though unsucessfully) and have a custom GTK3 theme, so this seems plausible.  

I will test if its works. (I know rust, dont worry about sending me instructions.)

**Comment by LeSnake04** [comment]
Works great. Thanks for the quick fix.
