### ISSUE TITLE
When running from terminal: Pen behaves like mouse and touchpad like pen

### ISSUE THREAD

**Issue by PhilDevProg** [flxzt/rnote#512]
**Describe the bug**
When running from a terminal RNote recognizes the pointer of the touchpad as a pen and the actual pen as a normal mouse.

**To Reproduce**
1. `flatpak run com.github.flxzt.rnote`
2. Use pen
3. Not abel to use pen because it behaves like a mouse (with mouse pointer)
4. Use touchpad
5. Beeing able to us it as a pen (ith pen pointer)

**Expected behavior**
Pen behaving like a pen and touchpad like a mouse

**Console Output**
 2023-02-15T14:38:50.901Z DEBUG rnote::app::imp > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 15:39:00.358: The layout manager of type GtkBoxLayout 0x556d511e9c20 does not create GtkLayoutChild instances

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 37
 - Installation source: Flatpak
 - Desktop Environment: GNOME 43.2 (Wayland)

**Comment by flxzt** [comment]
Is this happening in the newest beta or on a stable release?

**Comment by flxzt** [comment]
I don't fully understand. Can you explain what you mean by pen & mouse input and what the difference between each would be?

**Comment by PhilDevProg** [comment]
By pen input, I mean that the cursor changes the the little circle and you can draw with it. By mouse input, I mean that the cursor stays as an arrow and you can't draw with it which was the case if I remember correctly.

**Comment by flxzt** [comment]
Ah, so mouse input would be to drag the canvas around when dragging with a single touch with the touchpad, right?

In that case, I'd say it is intentional to be able to draw with the touchpad. You can navigate by either: using a two-finger drag gesture, or by dragging with a single finger *and* holding `Alt`. Zooming is possible with `Alt + Shift`

**Comment by PhilDevProg** [comment]
Ah, okay. I must have remembered it wrong.
