### ISSUE TITLE
Feature Request: Enable toggle tools for stylus keys

### ISSUE THREAD

**Issue by TangdizhiH** [flxzt/rnote#514]
**Is your feature request related to a problem? Please describe.**

The problem here is that all the stylus shortcuts are *one time changes*. For example, suppose I'm writing on the canvas and I want to drag camera to another area of the canvas, sometimes it is not possible to accomplish such adjustment in one stroke. But in rnote we can only switch to tool for one time, this means that I have to press the stylus button again and again to get to the target area 

**Describe the solution you'd like**

In the setting for button shortcut, we should give a checkbox to user whether to set this button as "toggle" button. This way, you will switch to your target tool when you press it, and switch back to the previous tool only when you press it again. 

**Additional context**

I think such scenario are very common. When you are writing or thinking, you will frequently need to switch between "draging the canvas" and "write something down". Therefore introducing toggle method is very important for user to concentrate to the work they are doing rather than "which state the stylus is in".

BTW, thank you for this awesome app to make writing on linux such a smooth and enjoyable experience.

**Comment by flxzt** [comment]
Thanks :)

This would be a nice improvement.

You are aware of the option to set the shortcut permanent on a button, right? (The `[ ] perm.` checkbox). Not completely the same but similar.

A way to implement this would be to replace that checkbox by another dropdown giving the choice between:

- activating once (like the current default)
- permanent (like the permanent checkbox)
- toggling ( set / reset on subsequent presses of the same button / activating the same gesture )
