### ISSUE TITLE
Discussion new UI

### ISSUE THREAD

**Issue by PJansky** [flxzt/rnote#516]
This issue is probably better suited for the discussion tab, but I thought if I put it here, more people can see this and chime in. 
I personally had no major problem with the old design, updated the UI, I think we can try to make it better.

I don't think the new 3 panel design is ideal from a UX perspective and this is reflected by other note-taking apps like Notability, Goodnotes or OneNote not having anything similar. Most other note-taking apps I've looked at have one toolbar at the top. This gives the user a good mental model of "If I want to change something, I look to the top of the window". With the new Rnote design, the user has to think about which tools/settings are where. stroke color -> top; stoke width -> left; shaper -> bottom; fill color of shape -> top. I understand what you tried to do with having the top panel staying constant and having the left panel change based on the tool selected in the bottom panel, but I don't think this really works. In addition the bottom toolbar is often covered by your hand while note-taking.
I personally think a more minimalistic top toolbar approach like the one found in GoodNotes would be better suited for Rnote. It looks to me like a good middle ground in between the feature richness of OneNote and still keeping a more simple design like Notability.

Maybe @bertob could also chime in if he finds the time

Goodnotes UI:
![goodnotes-notability-comparison-2](https://user-images.githubusercontent.com/46072333/219649520-3d633e60-d965-458d-a5b3-a006c6e0770d.jpeg)

**Comment by flxzt** [comment]
Lets keep the discussion about the layout of the toolbars in #367
