### ISSUE TITLE
Size presets for eraser

### ISSUE THREAD

**Issue by D0V4HKIIN** [flxzt/rnote#520]
**Is your feature request related to a problem? Please describe.**
The brush and shaper tool both have size presets but not the eraser.

**Describe the solution you'd like**
Add size presets for the eraser in the same way as it is done for the brush/shaper. This way the ui is more consistent and feels more natural to use.

**Comment by flxzt** [comment]
Sounds good. I *think* I didn't add it there because the width preview circles didn't really fit for the eraser, but it could be easily implemented to draw a rounded rect or something similar instead
