### ISSUE TITLE
Document Print Issue

### ISSUE THREAD

**Issue by winpower21** [flxzt/rnote#524]
When exporting a document as pdf and then printing it (tried from different devices) or directly printing the document from the app, the printout comes out with coloured lines all over the page. 
![photo_2023-02-21_17-20-44](https://user-images.githubusercontent.com/95289325/220337594-e594bb92-cc4a-4c0b-8c0c-9a513aae8ffc.jpg)
![photo_2023-02-21_17-20-41](https://user-images.githubusercontent.com/95289325/220337601-12996350-d7e5-457b-84b7-b454910ea81c.jpg)

**Comment by flxzt** [comment]
I can replicate this consistently. Very weird

**Comment by Redmauss** [comment]
I have this exact same issue, it occurs on both printing directly from rnote and from printing exported PDF's from rnote.  I used to note have this issue, maybe an update caused this?

**Comment by winpower21** [comment]
I tried to export it in .xopp format and then export with Xournal++, and the print was normal. Only happening when printing directly or exporting pdf or printing to document.

**Comment by winpower21** [comment]
@flxzt I am new to the linux environment so could you explain how I can apply this fix. The Rnote app is showing up on the latest version and no updates are available but the issue is sill occuring.

**Comment by flxzt** [comment]
the fix will be included in the next release

**Comment by winpower21** [comment]
Ok, thanks for the update
