### ISSUE TITLE
Green square X occasionally visible when creating a table after dragging out to make cells

### ISSUE THREAD

**Issue by philipwilk** [flxzt/rnote#527]
**Describe the bug**
When creating a table, when dragging out to create cells, there is occasionally an X that flashes up, made out of lots of small green squares that look half transparent, right in the middle of the table, in line with the diagonals of the corners.

**To Reproduce**
1. select table creation tool
2. draw a cell
3. drag to create more cells. sometimes you have to drag around for a bit, sometimes it appears immediately.

**Expected behavior**
No x made of green squares flashing in and out of existence.

**Screenshots**
Cant catch because it's so fast

**Desktop (please complete the following information):**
Fedora 37, Gnome 43.2, latest flatpak beta.

**Additional context**
It flashes into existence for less than a second *after* you stop dragging the table, then disappears. Very random as to when it happens or not.

**Comment by flxzt** [comment]
Sounds weird. I can't reproduce it, maybe you could record a video that shows this? Otherwise I don't have any ideas where to look to fix this.

**Comment by flxzt** [comment]
Without more info it is difficult to work on this.
