### ISSUE TITLE
Units of page size change to pixel after drawing on canvas

### ISSUE THREAD

**Issue by PJansky** [flxzt/rnote#535]
**Describe the bug**
After setting the canvas size in mm or cm, drawing on the screen changes the units to pixel. When setting the page size to a predefined format like A4, the format also gets reset to custom.

**To Reproduce**
1. Set page size in mm or cm
2. Draw on canvas
3. Page size set in pixel, page format changed to custom

**Expected behavior**
Keep the units used to specify the page size and don't forget the format. This bug only effects the UI, the canvas size is correct.

**Screenshots**
[Screencast from 02.03.2023 14:22:07.webm](https://user-images.githubusercontent.com/46072333/222441739-cb36a95d-b5fa-43b1-b7c3-888c98f61cf1.webm)

**Desktop (please complete the following information):**
 - Version: v5.14
 - Installation source: Flatpak

**Comment by PJansky** [comment]
The same thing applies to the "Pattern Width" and "Pattern Height" settings

**Comment by flxzt** [comment]
223cd7378b9937045a5f9bde5fdfe6bd24d6736a removes the (unneeded) UI refresh when the a stroke is finished, but this only "delays" the issue to when the pen style has changed / or some other action happened that triggers a UI refresh.

To fix this, the unit type would need to be stored in the widget and not be reset when the value gets synced with the document.

**Comment by flxzt** [comment]
the unit is fixed, saving the document format would need more refactor because only the document format preset are not actually stored anywhere.
