### ISSUE TITLE
Zoom tool

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#539]
Currently zooming is only possible through either:

- touch pinch gestures
- mouse scrolling
- holding `alt + shift` and then drag with a pointer
- clicking the plus / minus buttons in the canvas menu

Those options require either a keyboard or touch input, or are nested inside a menu. A nice addition would be to add a dedicated "zoom tool" in the tools sidebar page, which works like: down y-offsets while dragging zoom out, up y-offsets zoom in.

The main use case for this would be: being able to navigate around on the canvas easily with a tablet, while "touch-drawing" is enabled. ( No keyboard, and touch input is propagated to the pens). Adding this would work nicely together with the "two finger long press" shortcut activator

**Describe alternatives you've considered**

Using the plus / minus buttons in the canvas menu, but having to always go into the menu for it has too much friction

**Comment by OmegaRogue** [comment]
Having a "zoom lock" button would also be nice, to prevent accidental zooming with touch without using the dedicated zoom tool

**Comment by LeSnake04** [comment]
Agree. Especially when using a real life ruler to solve a math problem or drawing stuff. (I had to do it a few times. It really sucked bc you easily zoom on accident or by reflexes)

**Comment by OmegaRogue** [comment]
> Agree. Especially when using a real life ruler to solve a math problem or drawing stuff. (I had to do it a few times. It really sucked bc you easily zoom on accident or by reflexes)

For that case, a virtual ruler would also be a nice thing, tho that's a different suggestions

**Comment by LeSnake04** [comment]
I am trying to implement the block zoom part as an exercise to learn the code. It looks like I got it working already, just need to add the config and button.

**Comment by LeSnake04** [comment]
About the zoom button parts: cant we just reuse the functione from the tittle bar control panel.

In general: in which file are the panel buttons located?

**Comment by flxzt** [comment]
Oh I originally meant implementing it in a different way. Like the way the zooming is implemented when holding `Alt + Shift` and then dragging the pointer towards up / down

**Comment by LeSnake04** [comment]
Are you thinking of a "zoom to selected area" 
 
![Peek 2023-03-24 18-41](https://user-images.githubusercontent.com/47243761/227600699-994d565d-86b1-48e1-939e-1a2c05c81d7b.gif)


Or of a Click to zoom to that position:

![Peek 2023-03-24 18-39](https://user-images.githubusercontent.com/47243761/227600414-fd419cf3-e45f-4a2d-b664-4fdaf3a0c325.gif)

Combining these without a toggle is defiantly a TERRIBLE idea for a programs made for a pen.
Trying click to zoom in gimp with a pen :
![Peek 2023-03-24 18-47](https://user-images.githubusercontent.com/47243761/227601828-88487ec8-cf6f-4bb6-a98d-f8df45905a59.gif)
A slight slip and have a 13000% zoom

**Comment by LeSnake04** [comment]
I adde the videos to the post above.

**Comment by flxzt** [comment]
I already described it pretty clearly in the issue:

> which works like: down y-offsets while dragging zoom out, up y-offsets zoom in.
