### ISSUE TITLE
Dynamic titlebar resizing to allow thinner windows

### ISSUE THREAD

**Issue by astrosticks** [flxzt/rnote#54]
Here is the absolute thinnest that the Rnote window can go on my 1366px-wide display: 
![Screenshot from 2022-01-21 14-10-08](https://user-images.githubusercontent.com/32315760/150593944-25321c31-ada4-4dfd-9d8a-8b228b28109e.png)

For my use case, taking notes in class, I'd like to be able to split-screen Rnote with Zoom, which can be pretty greedy and use over half of my screen. Same with Discord. 

The solution I'd like to propose is dynamically hiding/transforming different elements in the titlebar to allow the interface to shrink further. I've marked up my general thoughts on the titlebar areas below: 

![image](https://user-images.githubusercontent.com/32315760/150595258-d957a6c1-6724-4300-9693-72981e376253.png)

I think the biggest and most necessary change is to collapse the tool selection bar into a dropdown when the window size requires it.

**Comment by flxzt** [comment]
I implemented this: I don't like the look 100%, but I can't really say what exactly and I guess it should improve usability a lot in comparison to before and thats what matters.

https://user-images.githubusercontent.com/19841886/152613478-5497fd72-957c-47a6-85b6-01eac748a01b.mp4

**Comment by VodnikAngus** [comment]
That looks awesome, I have email notifications turned on for this project and I love seeing things like this happening in real time.

Biggest problem for me on that video is that undo/redo buttons are not fully aligned to the left.

**Comment by flxzt** [comment]
Without the spacing the alignment looks awful though and you have to reach even further to the left as a lefthanded person, or to the right as a righthanded person
![Bildschirmfoto vom 2022-02-04 23-58-40](https://user-images.githubusercontent.com/19841886/152614326-f451cbac-94ff-48d3-bb0f-14fddf58d9cf.png)

**Comment by astrosticks** [comment]
I think this certainly fixes the minimum width issue! I think we should close this issue but there should definitely be individual threads for addressing issues of ease of reach and dynamic layout features.

**Comment by flxzt** [comment]
Sure. I think the discussions is the best place for throwing some ideas around.
