### ISSUE TITLE
Canvas moves/shakes/jumps while writing

### ISSUE THREAD

**Issue by PapierFliegr** [flxzt/rnote#549]
**Describe the bug**
I use a Lenovo M14t as an external monitor (supported by libwacom) . While writing with the stylus that came with the M14t the Canves moves/shakes/jumps and zooms all the way out. Additionally after writing something I can't move or zoom the canvas or press on any buttons, i.e. touch input won't be accepted (but only in rnote).

**To Reproduce**
Not sure how to reproduce. Just happend while writing sometimes near the edge, sometimes whie zooming in, sometimes just random. See video below.

**Expected behavior**

** Console Output **
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` and post the output

**Screenshot**
https://user-images.githubusercontent.com/96027888/224574722-a2ae4d7f-75fa-4910-b4ce-e888b715b4cd.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Version: 0.5.16
 - Installation source: flatpak
 - Desktop Environment: Gnome 43.1

**Additional context**

**Comment by PapierFliegr** [comment]
Not sure, but maybe part of #534.

**Comment by flxzt** [comment]
#518 might be related

**Comment by flxzt** [comment]
> While writing with the stylus that came with the M14t the Canves moves/shakes/jumps and zooms all the way out.

Okay, 2d3b70179984c7695cb1ab4712aba593ff5b018d and e8ce3239f93513413cf50301e7e43053a0560fc2 should have fixed this, at least when writing near the edge.  
It might be that the canvas gets moved slightly when a button is pressed, but as mentioned in #518 this is probably an issue in gtk's input handling so there is no solution yet.

> Additionally after writing something I can't move or zoom the canvas or press on any buttons, i.e. touch input won't be accepted

This is a different issue, and might be the same as #329 . More context about that would be needed (in a new issue)

**Comment by PapierFliegr** [comment]
How can I try changed version? Do I have to wait for 0.5.17? It's my first time reporting a bug so I don' know the procedures.

**Comment by flxzt** [comment]
yeah wait for a new release if you don't want to build from source. But if you want to do that (which would be awesome so we can verify the fix), you can follow: https://github.com/flxzt/rnote/blob/main/BUILDING.md .

**Comment by flxzt** [comment]
The sporadic jumps are fixed though

**Comment by PapierFliegr** [comment]
That is true.
