### ISSUE TITLE
Add ability to edit brush and shape strokes

### ISSUE THREAD

**Issue by dalcde** [flxzt/rnote#55]
It would be convenient to be able to change all strokes in a selection to a new color.

**Comment by defini-tiv** [comment]
This feature could be thought more general:

- color
- stroke width
- stroke style

And all other properties of this kind would be useful to be able to change retrospectively.

**Comment by jaklt** [comment]
I second @dalcde's suggestion, I use it in Xournal++ all the time. I often write something and after some time I realise that it's probably not as significant so I make it smaller, move it to the side and change its colour to something not as prominent. This is also useful the other way around, after writing something I often decide to make it stand out, so I just change the colour of it.

**Comment by e87131** [comment]
MS apps seem to allow for this (OneNote, Whiteboard)
great for exporting in different colors if youre drawing on black bg and exporting for print or something

**Comment by LeSnake04** [comment]
Assuming the color is just a variable, changing it should be as easy as:

1. Get current color
2. Loop over all selected objects, setting the color of the object. 

I dont know how easy it is to get write access to selected objects though.2
