### ISSUE TITLE
Cant erase a drawn line (without reopening the document / resizing after selection)

### ISSUE THREAD

**Issue by rizajur** [flxzt/rnote#558]
**Describe the bug**
 i can erase all drawings beside one line and the eraser is 100% on the drawn line but nothing happens 
I posted a video of the issue below in a commend, it looks like the borders of erased objects often overlap even tiny the not erasable stroke

**To Reproduce**
This is rly tricky since its  quite rare (not very) but super annoying ,  to fix it i had to close rnote and open the document again. 

**Expected behavior**
Fail safe check if there is a object to erase so you dont have to close and reopen to be able to erase it.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Installation source Flatpak
 - Desktop Environment Gnome 43

**Comment by flxzt** [comment]
Try to find a case where this consistently happens, otherwise it will be difficult to reproduce and fix.

**Comment by rizajur** [comment]
Puh taf one, its not related to pictures. But just random happens that it thinks there is no object to erase while there is,
but when i draw over it and erase its just erasing the new drawings and the buggy lines stay

**Comment by rizajur** [comment]
no clue but this bug is very frequent on my notebook

**Comment by flxzt** [comment]
are you then able to select those strokes or is that impossible as well?

To see if they are missing hitboxes, can you do the following:
- enable the `developer settings` in the app (hamburger) menu. Then a new submenu appears
- enable `Visual debugging` and then screenshot the strokes that are undeletable

**Comment by rizajur** [comment]
I'm strangely able to select the line stroke i cant erase.
Once i resized the stroke im able to erase it.


https://user-images.githubusercontent.com/123980461/226164772-0142764d-bfb6-48c3-9f5d-7ae8ef78d403.mp4



It seems like a somewhat interference with the deleted lines behind. 
But i could be fully wrong about that and it may just be a coincidence.

**Comment by rizajur** [comment]
https://user-images.githubusercontent.com/123980461/226194739-a325b798-4a86-463d-a32c-4394883984dc.mp4

**Comment by maymage** [comment]
I confirm, that this happens from time to time.

The uneraseable elements are however selectable and can then be removed using the trash symbol in the selection tool bar.

**Comment by sirius-0** [comment]
It happens to me every time I click the delete button while drawing a line

https://user-images.githubusercontent.com/67059270/226968044-b501d40a-6566-4895-af65-d0425c10ae41.mp4

**Comment by flxzt** [comment]
ah thanks, that might be it! When changing the pen mid-stroke, a `Cancel` event was missing
