### ISSUE TITLE
New shape: Circles

### ISSUE THREAD

**Issue by PhilDevProg** [flxzt/rnote#559]
**Is your feature request related to a problem? Please describe.**
There already are shapes for ellipses but with them it's quite hard to make a perfect round circle

**Describe the solution you'd like**
A circle shape that works like the normal ellipse but is always perfectly round

**Comment by Heiseneberg-maybe** [comment]
In the settings of the shapes there are Constraints, once enabled  you can choose various ratios
One of them is 1:1 which when used for creating ellipses creates circles

**Comment by PhilDevProg** [comment]
So that's what they are for, I always asked myself what they mean. Thank you!
