### ISSUE TITLE
More keyboard navigation shortcuts in typewriter text box

### ISSUE THREAD

**Issue by pipipear** [flxzt/rnote#560]
The keyboard navigation in the typewriter text-box would be enhanced by some additional shortcuts:

| shortcut   | action                            |
|------------|-----------------------------------|
| ctrl+left  | cursor moves one word left        |
| ctrl+right | cursor moves one word right       |
| home       | cursor jumps to start of line     |
| end        | cursor jumps to end of line       |
| ctrl+home  | cursor jumps to start of text box |
| ctrl+end   | cursor jumps to end of text box   |

**Comment by flxzt** [comment]
this is not a bug? Those shortcuts just aren't yet implemented.

**Comment by Kneemund** [comment]
The main question is what style to use for the whole-word movement. I don't think that there are many objective arguments, so this is pretty much only opinion-based. Here are two of them in comparison (there may be some other quirks I didn't find out about yet or that I got wrong):

||Browser Style|LibreOffice Style|
|:---:|---|---|
|**Starting Position**|Lorem ipsum &nbsp; &nbsp; \| &nbsp; &nbsp; dolor sit amet|Lorem ipsum &nbsp; &nbsp; \| &nbsp; &nbsp; dolor sit amet|
|**Navigate Word Left**|Lorem \|ipsum &nbsp; &nbsp; &nbsp; &nbsp; dolor sit amet|Lorem \|ipsum &nbsp; &nbsp; &nbsp; &nbsp; dolor sit amet|
|**Navigate Word Right**|Lorem ipsum &nbsp; &nbsp; &nbsp; &nbsp; dolor\| sit amet|Lorem ipsum &nbsp; &nbsp; &nbsp; &nbsp; \|dolor sit amet|
|**Delete Word Left**|Lorem \| &nbsp; &nbsp; dolor sit amet|Lorem \| &nbsp; &nbsp; dolor sit amet|
|**Delete Word Right**|Lorem ipsum &nbsp; &nbsp; \| sit amet|Lorem ipsum &nbsp; &nbsp; \| sit amet|
||Non-alphanumerical characters are treated like whitespace, but are part of the word that's *directly* to the left if there is one.|Non-alphanumerical characters are treated like separate words, even if there is no whitespace between them and alphanumerical characters.|

Personally, I prefer the browser style, as the LibreOffice one is quite inconsistent (and thus more work to replicate, specifically Delete vs. Navigate).

Opinions are very welcome. It doesn't have to be one of the above, it can also be a mixture or a new one :)
