### ISSUE TITLE
Import PDF try to fit into proper area (set page format)

### ISSUE THREAD

**Issue by rizajur** [flxzt/rnote#566]
**Is your feature request related to a problem?**
Annoying import position 

Im using endless documents but have shown borders for DinA4 Pages and import a lot of PDF's in the same format,
but every time i import it, its not placed in the borders of the fitting format instead it gets placed somewhere in the middle. 
So the format is not the center of rnote when opening and the imported PDF is placed in the place which rnote centers which is not related to the set format (rnote borders).

This results that i have to move it in the format fitting spot, so the imported pdf is within the drawn borders of rnote. 

**Describe the solution you'd like**
Check if the pdf is in a specific format and if it could be placed within the center of a format that is used for rnote borders.

**Describe alternatives you've considered**
Make an optional import checkbox something like move imported file into the set border format. (width 100% so fitting 100% the format if it is the same)

**Additional context**
Thanks so much for the current state, its already very good.

**Comment by PhilDevProg** [comment]
RNote seems to place the PDF at the point where the cursor was placed on the document the last time so going with the cursor to the left top x and then importing the file without hovering over the canvas again should place it the right way.

**Comment by rizajur** [comment]
nice to know but most of the time when launching rnote I'm using the file manager when opening a PDF (so open pdf with rnote)

**Comment by flxzt** [comment]
Rnote places the pages with a fixed offset based on the current viewport when the pdf is imported through the file manager. When drag & dropping it it should place it under the cursor.

**Comment by rizajur** [comment]
>current viewport when the pdf is imported through the file manager. When drag & dropping it it should place it under the cursor.

whats the viewport when opening rnote from the file manager? its always the same position but never fits the borders i have set,
resulting that i have to move it in order to get proper exported pdfs. if thats intended behaviour, okay, im just asking to be sure we are addressing the same behaviour.

**Comment by flxzt** [comment]
to clarify: it places the imports by the current viewport, capped to the document sizes. E.g. when viewport has negative x, positive y but the document origin is at (0.0, 0.0), the import will be at (0.0, positive y + import-offset)
