### ISSUE TITLE
Launch error on `rnote` 0.5.17

### ISSUE THREAD

**Issue by orhun** [flxzt/rnote#568]
**Describe the bug**

I'm getting the following error after running `rnote`:

```
thread 'main' panicked at 'Source property state expected type GVariant but transform_from function returned gchararray', /usr/src/debug/rnote/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.17.5/src/object.rs:3756:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. Build `rnote` 0.5.17 from [Arch Linux repositories](https://github.com/archlinux/svntogit-community/blob/packages/rnote/trunk/PKGBUILD).
2. Run `rnote`

**Expected behavior**
Successful run.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: `#1 SMP PREEMPT_DYNAMIC Sat, 11 Mar 2023 14:28:13 +0000 x86_64 GNU/Linux`
 - Installation source: Arch Linux community
 - Desktop Environment: i3wm

**Additional context**
None.

**Comment by flxzt** [comment]
Can confirm, it panics when the color-scheme is set to anything else than `Use System Colors`, which internally is `Default`. This is the reason I didn't notice it before.

#547 which updated to the newest gtk-rs introduced this. Specifically the bind [here](https://github.com/flxzt/rnote/blob/main/rnote-ui/src/appwindow/appsettings.rs#L14) are causing the panic.

I couldn't fix the bind, it always keeps panicking for me. Either something is wrong or I am using this (undocumented) API in the wrong way.   
For the sake of a quick fix I replaced it by property callback that saves the color-scheme to the preference every time it is changed.
