### ISSUE TITLE
[BUG][HiDPI] Low quality drawing cursor

### ISSUE THREAD

**Issue by farline99** [flxzt/rnote#570]
Drawing cursor has poor quality with 2736x1824 resolution and 200% scaling. 
Screenshot:
https://pasteboard.co/xGTppQiIZVnk.png

**Comment by rizajur** [comment]
you can post images on github , if you using umatrix you have to whitelist githubs dynamic cdns

**Comment by flxzt** [comment]
Unfortunately without a proper bug report it is difficult to work on this. The screenshot URL is also broken. If this is still an issue, and more info is provided it can be reopened (but this is likely an issue in the toolkit rather than something that can be fixed on the app level anyway)
