### ISSUE TITLE
Reconsidering version numbering scheme

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#571]
The versioning scheme should be reconsidered.

The current one is: basically following SemVer for file format breakage. This is the reason the version is `0.5.*` for quite a while now.
While being in "pre-stable" / `0.x`, following this scheme doesn't leave room for patch releases. It would be very beneficial to be able to do that.

My thoughts about it:

Long term:

doing a `1.0` release. Feature releases then will be `1.1`, `1.2` etc. while patch releases are `1.1.1`, `1.1.2`, etc. . But before doing that the file format should be thoroughly reconsidered, because no matter how we communicate it, the expectation will be that files post `1.0` will be something that can be relied upon for some time.

Short term: 

Drop the restriction that incrementing `0.x` reflects a break in the file format. We could then do feature releases with `0.x`, and it will leave room for patch releases. The downside of that is if we do have to break it, we can't communicate it to users as cleanly and easily.

Though ideally we should always try as hard as possible to provide at least a lossy upgrade path for the file format from older to newer versions like it is already done for some versions in `0.5.x`. And reserve us the option to break when transitioning to `1.0`.

Other approaches:

- use `yyyy.mm.dd`. Personally I don't hate that either
- ?

other devs: thoughts, ideas?

**Comment by Kneemund** [comment]
Sounds good to me. I'd stick to semantic versioning, it conveys much more information than e.g. the release date (especially without fixed release cycles).

> The current one is: basically following SemVer for file format breakage. This is the reason the version is 0.5.* for quite a while now.
While being in "pre-stable" / 0.x, following this scheme doesn't leave room for patch releases. It would be very beneficial to be able to do that.

Isn't major for breaking changes, minor for non-breaking changes and patch for fixes anyway? That wouldn't convey the fact that this is still unstable software, but maybe we could use a pre/postfix instead? Something like `pre-5.18.0`. Although that sounds more like a beta release, and is a pretty big change...

**Comment by dehesselle** [comment]
> Isn't major for breaking changes, minor for non-breaking changes and patch for fixes anyway?

Correct, with major version `0` basically allowing for anything:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

So technically you don't need to worry for breaking things while it's `0.x.y`. Of course, if you have communicated it differently in the past, announce it once with the first release when you're changing strategies.

> Something like `pre-5.18.0`

While it's an example, I'm still going to nitpick: that is not a valid SemVer version.

**Comment by flxzt** [comment]
okay, I think I'll do to what I outlined in the original post: I'll increment to `0.6.0` in the next version, since that will be a "feature" release

If there will ever be a breakage in the file format while being in pre-release, we'll just have to communicate it prominently in the changelog and maybe by implementing a pop-up on first app start telling users about it, with instructions how to port / downgrade. 

Unfortunately, there is no mechanism to display a message to users warning about a breakage prior to upgrading package (flatpak & native packages). I also doubt many would have noticed that a file format break would have been reflected in incrementing the minor version number.

But this all is only hypothetical, I don't plan on breaking it unless absolutely necessary.
