### ISSUE TITLE
Import PDF: Set scaling number to something that fits into the file format automatically

### ISSUE THREAD

**Issue by PhilDevProg** [flxzt/rnote#574]
**Is your feature request related to a problem? Please describe.**
When scanning documents, the PDF is often not A4/... and when importing it, you have to manually resize it to make it either smaller or bigger.

**Describe the solution you'd like**
In the Import PDF dialog could be a button which calculates how big the scaling has to be for the PDF to be not too big/small and fit into the page format.

**Comment by rizajur** [comment]
For me using 100% works all the time, in case the pdf your importing is 100% width

**Comment by flxzt** [comment]
You can already set the pdf page width (takes the width of the first page) in relation to the format width in the import dialog.

**Comment by PhilDevProg** [comment]
@flxzt I know that I can set it manually but the feature I'd like to have is a button that automatically calculates this number to let the PDF automatically fit the page  the best it can. When scanning documents with a camera, the PDF is most of the time not A4/... but has no specific format, just a height and width and you have to manually resize it to fit the page the best way possible. This feature would scale it automatically to fit the page (not too big, not too small).

**Comment by flxzt** [comment]
I don't understand. How would you determine the *percentage* ?
