### ISSUE TITLE
Change Textcolor after writing

### ISSUE THREAD

**Issue by PapierFliegr** [flxzt/rnote#577]
**Is your feature request related to a problem? Please describe.**
Changing the color of a written text is not possible, so everytime someone wants to change the color, they have to delete everything and write it again.

**Describe the solution you'd like**
Select text, click on desired color to change color of text.

**Comment by Kneemund** [comment]
What you described will be possible in the next release, as it's already implemented (not just for text). See #55 (and the related PR).

In the meantime, you can change the color of existing text by selecting the typewriter tool, editing the text field and then selecting a different color in the color picker.
