### ISSUE TITLE
Typewriter navigation with Ctrl key

### ISSUE THREAD

**Issue by ElbertCode** [flxzt/rnote#584]
In most text editors and text input fields in general, if you're holding down the Ctrl key while performing an action, it counts for a whole word. This applies to navigation with the arrow keys, selection with the Shift key pressed and deletion with the Backspace/Del key. It would be nice if this could be implemented in Rnote, since when you type a text in a handwriting note it will probably be quite long and especially there it would improve the navigation and therefore the UX.

**Comment by flxzt** [comment]
agree, but this feature request already exists with #560
