### ISSUE TITLE
Option to remove a single formating of a selected text

### ISSUE THREAD

**Issue by ElbertCode** [flxzt/rnote#586]
**Is your feature request related to a problem? Please describe.**
If you select a multi-formatted text (e.g. bold and italic) in typewriter mode, you can only remove all formatting at once.

**Describe the solution you'd like**
Add the option to remove only a specific formatting by clicking on the corresponding icon. For example, for a bold and italic text, click on the "bold" icon to "unbold" the text so that the text is only italic.

**Comment by Kneemund** [comment]
This has been implemented by #829.
