### ISSUE TITLE
File browser: Show correct icon for .rnote files

### ISSUE THREAD

**Issue by ElbertCode** [flxzt/rnote#594]
**Is your feature request related to a problem? Please describe.**
Currently, files from Rnote have the default logo in the integrated file browser for an unknown file type (white blank page with a crease in the top right).

**Describe the solution you'd like**
It would be nice if a more appropriate icon, such as the Rnote app icon, were displayed instead.

**Additional context**
I am aware that neither Nautilus nor Dolphin show a suitable icon for .rnote files, but since it is in the app itself, it should be implemented.

**Comment by dehesselle** [comment]
This requires some dedicated changes to the packaging process on macOS. I'll take care of those.
