### ISSUE TITLE
Empty exported images from infinite canvas pages behind origin

### ISSUE THREAD

**Issue by ElbertCode** [flxzt/rnote#605]
**Describe the bug**
If you try the individual pages of an document with an infinite canvas, all pages "behind" the origin are empty.

**To Reproduce**
1. Change the document layout to "infinite"
2. Write something to the left or above the origin (the little green "x")
3. Use the "Export Document Pages" feature
4. The pages to the left or above the origin are empty.

**Expected behavior**
All exported images should contain the content of their respective page (like those of the pages bottom right of the origin do).

**Console Output**
Export as PNG:
```
 2023-04-04T08:25:55.358Z DEBUG rnote::app::imp > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 10:26:11.411: The layout manager of type GtkBoxLayout 0x7f4e64015650 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:26:11.411: The layout manager of type GtkBoxLayout 0x55df4ffce200 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:26:11.412: The layout manager of type GtkBoxLayout 0x55df503b2ea0 does not create GtkLayoutChild instances
```
Export as JPEG:
```
 2023-04-04T08:29:25.164Z DEBUG rnote::app::imp > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 10:29:43.325: The layout manager of type GtkBoxLayout 0x55f90c1aeaa0 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:29:43.325: The layout manager of type GtkBoxLayout 0x55f90c1a3600 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:29:43.325: The layout manager of type GtkBoxLayout 0x55f90c0b4b90 does not create GtkLayoutChild instances
```
Export as SVG:
```
 2023-04-04T08:31:19.093Z DEBUG rnote::app::imp > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 10:31:36.295: The layout manager of type GtkBoxLayout 0x5577bdc1d790 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:31:36.295: The layout manager of type GtkBoxLayout 0x5577bdc57790 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 10:31:36.295: The layout manager of type GtkBoxLayout 0x7f6a58009af0 does not create GtkLayoutChild instances
```

**Screenshots**
This is a screenshot of the Rnote document:
![Screenshot_20230404_095239](https://user-images.githubusercontent.com/67899667/229725292-83cde87b-1b90-4730-8f7f-1284fab21874.png)
And these are the exported images (as you can see there's nothing on the images of the pages 1-3):
|  |1 | 2 | 3 | 4 |
|--------|--------|--------|--------|--------|
| **PNG** | ![Neues Dokument - Page 01](https://user-images.githubusercontent.com/67899667/229727616-68254c27-a21a-40fb-b495-b03950359ee7.png) | ![Neues Dokument - Page 02](https://user-images.githubusercontent.com/67899667/229727865-8804c80c-64e5-457d-b078-3b5c4616540f.png) | ![Neues Dokument - Page 03](https://user-images.githubusercontent.com/67899667/229727937-4dabb79c-ac63-480f-a4f2-0e37393bcc76.png) | ![Neues Dokument - Page 04](https://user-images.githubusercontent.com/67899667/229727999-e736ae2a-c35e-4929-80b4-9ece9b1bfd52.png) |
| **JPEG** | ![Neues Dokument - Page 01](https://user-images.githubusercontent.com/67899667/229729110-7b7eb0cb-e83e-4419-957c-5b79c06e1e10.jpg) | ![Neues Dokument - Page 02](https://user-images.githubusercontent.com/67899667/229729190-ca489f12-f27b-4d6a-8c8a-a9af467c29bc.jpg) | ![Neues Dokument - Page 03](https://user-images.githubusercontent.com/67899667/229729232-614c2157-1174-4977-910e-cc80bfabe05a.jpg) | ![Neues Dokument - Page 04](https://user-images.githubusercontent.com/67899667/229729287-0d6030b6-6386-4ac5-be9e-7d54b62ba352.jpg) |
| **SVG** | ![Neues Dokument - Page 01](https://user-images.githubusercontent.com/67899667/229729862-68e98c2e-4b67-4d1e-8c25-8bd4509ba8dd.svg) | ![Neues Dokument - Page 02](https://user-images.githubusercontent.com/67899667/229729921-08ede415-f6c0-46b3-a701-e55d2ab71c73.svg) | ![Neues Dokument - Page 03](https://user-images.githubusercontent.com/67899667/229729975-db466e4d-93ac-40a0-8933-6a33c5336ba1.svg) | ![Neues Dokument - Page 04](https://user-images.githubusercontent.com/67899667/229730013-2c0130ee-120d-4079-9272-323d1140832d.svg) | 

**Desktop**
 - OS: Manjaro Linux
 - Version: 0.5.18
 - Installation source: Flatpak
 - Desktop Environment: KDE Plasma 5.26.5

**Additional context**
- I tested it with different page formats (including "custom") and both portrait & landscape but the error occurs every time.
- The app displays the message that the document would have been exported successfully.
- The exported SVGs are at least displayed correctly in Inkscape, but neither in Firefox nor when I import them into Rnote.

**Comment by flxzt** [comment]
the fix here is: move the bounds of the wrapped `<svg>` element of the pages so that the offset is always [0.0, 0.0]. Most viewers apparently don't display anything when the svg has a negative offset

**Comment by ElbertCode** [comment]
Does this also solve the problem for PNGs and JPEGs?

**Comment by flxzt** [comment]
yes, as bitmaps are rendered via the svg
