### ISSUE TITLE
PDF bulk import from file managers can cause crashes

### ISSUE THREAD

**Issue by JDFranz** [flxzt/rnote#616]
I've noticed that the PDF import feature seems to be a little buggy on certain occasions. Especially selecting files in nautilus and then opening in Rnote seems to crash the software. Moreover, a solution to bulk import PDFs into .Rnote files would save a lot of time. Example: select files in nautilus and then right click > import into nautilus > opens context menue for importing > creates .Rnote files with filenames resembling the PDF filenames. With the specified settings. Additional context: This feature would be especially interesting for engineering students for processing exercises and solutions to readily available templates for studying. (It is usually a tiresome task taking multiple hours for a single subject)

**Comment by flxzt** [comment]
Can you please use the bug report template? Especially console output when the app crashes might be useful.

**Comment by flxzt** [comment]
Closing because no further info was provided.
