### ISSUE TITLE
Rnote does not display Simplified Chinese normally in the Simplified Chinese operating system

### ISSUE THREAD

**Issue by Mr-Spade** [flxzt/rnote#621]
**Describe the bug**
I cautiously did some testing on a fedora virtual machine. When I install fedora in French and Japanese and install rnote through flatpak, rnote is normally displayed in the corresponding language.

However, when I installed it in Simplified Chinese, rnote did not display Chinese as expected, but displayed plain English.

(However, there are some small problems with French and Japanese, for example, after I installed fedora in French and installed rnote, if I switch the language setting of the OS to Japanese, rnote will display plain English instead of Japanese, I'm not sure about this Is it related to the problem just now, or because switching the system language will still miss some language-related packages that need to be installed)

I guess this may be because Simplified Chinese is abbreviated as zh_cn in some places and zh_hans in some places. Wondering if you'd be handy to do some testing on this?

Or, a possibly simpler solution is to add an option to switch languages in rnote, allowing users to customize the language used by rnote, then this problem can also be solved.

grateful!

**To Reproduce**
1. Install fedora with Simplified Chinese
2. Add flathub repo
3. Install rnote
4. Open rnote, show plain English

**Expected behavior**
Rnote should show Simplified Chinese

**Console Output**
```
 2023-04-14T11:00:30.249Z DEBUG rnote::app::imp > ... env_logger initialized
(rnote:2): Gtk-WARNING **: 19:00:30.348: Failed to set property GtkEventControllerScroll.flags to 水平: Unknown flag: '水平'
(rnote:2): Gtk-WARNING **: 19:00:30.348: Failed to set property GtkEventControllerScroll.flags to 水平: Unknown flag: '水平'
```
("水平" means "horizontal" in Chinese)

**Desktop (please complete the following information):**
 - OS: fedora 37
 - Version: latest
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43

**Comment by LeSnake04** [comment]
This might has been fixed with #612. I only pasted character though  (since I dont know chinese) , so I am not sure. Also, Pasting seems fine on stable already.

When you know how to compile it would be great if could test it on main.

**Comment by LeSnake04** [comment]
Also, Chinese input on English ui works fine (Fedora 37, inteligent pinyin)

**Comment by flxzt** [comment]
@LeSnake04 I think this issue is about the UI not being displayed in Chinese, not about text being written into the 
typewriter.

--- 

Note that the simplified chinese locale is currently only at [49%](https://hosted.weblate.org/projects/rnote/repo/zh_Hans/) translated, so only some string can / should be in Chinese in the UI.

 I'd first do the following:

- Check if the correct locale is installed via `flatpak info com.github.flxzt.rnote.Locale`. In `subdirectories` there should be `zh_Hans`.

- Check `flatpak config` and compare that matches. I think it should be: `languages: *unset* (default zn_hans)` and `extra-languages: *unset*` so it uses the system locale settings.

- Check your system locale: `localectl` and compare if that matches

**Comment by Mr-Spade** [comment]
@flxzt Thanks. I tried these commands, but flatpak says:

```
~$ flatpak config --set languages 'cn;zh_hans'
Error: 'zh_hans' does not look like a language code
```

Seems like `cn` and `zh` are language codes, but `zh_hans` is not. I tried `flatpak config --set languages 'cn;zh' && flatpak update` and it did download a couple of packages, but nothing seems to change, rnote is still displayed in full English.

**Comment by flxzt** [comment]
my bad, then `zh`. What is the output of the other commands?

**Comment by Mr-Spade** [comment]
The output of the command looks like this:

```

~$ flatpak info com.github.flxzt.rnote.Locale
            ID: com.github.flxzt.rnote.Locale
           Ref: runtime/com.github.flxzt.rnote.Locale/x86_64/stable
          Arch: x86_64
        Branch: stable
        Origin: flathub
    Collection: org.flathub.Stable
  Installation: system
     Installed: 25.6 kB

        Commit: 01a7711bf03c522ff12c408f9ff83049a44be7ffddbd2cac11155a1a96bdf3a8
        Parent: 2d5ab938ad241300204ddab30aea02889e39687f1fa30d0399c310e6155b7443
       Subject: update to v0.5.18 (#27) (4ef4a1da)
          Date: 2023-03-16 22:45:04 +0000
Subdirectories: /cn,/zh

~$ flatpak config
languages: cn;zh (default: zh)
extra-languages: *unset*

~$ localectl
   System Locale: LANG=zh_CN.UTF-8
                  LANGUAGE=zh_CN:zh
       VC Keymap: n/a
      X11 Layout: cn
       X11 Model: pc105
```

I wonder can it be fixed by changing the current `zh_hans` to `zh` or `cn`?

**Comment by flxzt** [comment]
I **think** the issue here is that the system locale is `zh_CN` and does not recognize `zh_hans`. Other apps seem to have fixed this by renaming `zh_hans` to `zh_CN` (see [here](https://github.com/GeopJr/Collision/issues/58) . I am not sure if we should do the same, I believe `zh_hans` is actually more correct, but obviously there should be some sort of recognition of `zh_CN`.

Is it possible to change to or add zh_hans as locale on your system?

**Comment by Mr-Spade** [comment]
Thank you very much for your patient answer. I made some modifications according to your tips, and finally successfully displayed Simplified Chinese in Rnote.

The steps I took are as follows:

Edit the /etc/default/locale file, the original content is:

```
# File generated by update-locale
LANG="zh_CN.UTF-8"
LANGUAGE="zh_CN:zh"
```

The edited content is:

```
# File generated by update-locale
LANG="zh_CN.UTF-8"
LANGUAGE="zh_CN:zh:zh_Hans"
```

Then restart the computer. In this way, the result after typing `localectl` in the terminal becomes:

```
    System Locale: LANG=zh_CN.UTF-8
                   LANGUAGE=zh_CN:zh:zh_Hans
        VC Keymap: n/a
       X11 Layout: cn
        X11 Model: pc105
```

Open Rnote to display Chinese normally.

According to the results obtained on my computer, I speculate that changing `zh_Hans` to `zh_CN` and `zh_Hant` to `zh_TW` should help users whose system language is Chinese without any additional configuration. Chinese is displayed in , since the default Chinese setting of the system does not include `zh_Hans`. But if you don't want to do that, I think it might be a good idea to keep the status quo since there is a solution.

Anyway, thank you very much for helping me solve this problem. I'm finally able to see Chinese in Rnote, and I plan to submit some Chinese translations of Rnote in the near future to help supplement the progress of the Chinese translation :)
