### ISSUE TITLE
automatic shape recognition system

### ISSUE THREAD

**Issue by MrGumpIT** [flxzt/rnote#622]
**Please submit only one feature request in one issue!**

**Is your feature request related to a problem? Please describe.**
The current method of selecting shapes is slow, many keys to select, an automatic shape recognition system would be useful at least for common shapes such as lines, squares and circles

**Additional context**
I use Rnote for the study, I am currently using it for electrical engineering, to draw a clean circuit I have to switch continuously between shapes and freehand writing, this is slow and frustrating

Describe the solution you'd like
I would like an automatic shape system, which can be activated simply with a button

**Comment by ElbertCode** [comment]
Are you talking about selecting or creating shapes? If the latter, this is the same as #120 .

**Comment by MrGumpIT** [comment]
Sorry I hadn't seen it already there, I'm deleting mine!

**Comment by MrGumpIT** [comment]
Sorry I hadn't seen it already there, I'm deleting mine!
