### ISSUE TITLE
Random Crash, Lost File

### ISSUE THREAD

**Issue by PapierFliegr** [flxzt/rnote#626]
**Describe the bug**
Rnote just crashed (closed on its own). Happens rarely sometimes, but was not a problem until now since I had the file saved before and (I guess) autosave saved the current progress. 
This time I had a draft file (not saved yet) and after the crash the file was lost. 
Is there a default space where drafts are automatically saved? If not maybe add that? Autosave on drafts?

**To Reproduce**
Not sure how to reproduce... Happens rarely

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Version: 0.5.18
 - Installation source: Flatpak
 - Desktop Environment: Gnome 43.1

**Further Information**
Could be an issue of my hardware. On Win11 OneNote sometimes crashed randomly as well.

**Comment by ElbertCode** [comment]
The proposed solution (auto saving crafts) looks like #545
