### ISSUE TITLE
crash on Gnome 44 when starting app through UI

### ISSUE THREAD

**Issue by Heiseneberg-maybe** [flxzt/rnote#629]
**Describe the bug**
I just updated Fedora to Fedora 38, which is using gnome 44 and now Rnote refuses to work
(There are no extensions active)

**To Reproduce**
1. Open the app
2. Wait a bit, even while doing nothing 
3. The circle next to the name of the app keeps spinning 
4. It doesn't stop spinning
5. The app closes abruptly

**Expected behavior**
The app should start and not close after a bit

** Console Output **
Running the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote`  reports the expected behaviour  of the app: the app starts and works. (The wheel does not appear at all)

**Video**
[Rnote_crash_gnome44.webm](https://user-images.githubusercontent.com/104737846/233025260-7baf4923-67a3-4023-99e4-b30ba8214b25.webm)

**Desktop:**
 - OS: [Fedora]
 - Version: [38]
 - Installation source: [Flatpak]
 - Desktop Environment: [e.g. Gnome 44]

**Comment by flxzt** [comment]
I also updated to 38 yesterday, but I don't experience that. What is the output in the terminal when the app crashes?

**Comment by Heiseneberg-maybe** [comment]
Running the app from the terminal with the command flatpak com.github.flxzt.rnote doesn't make the app crash and reports this:
(rnote:2): Gtk-CRITICAL **: 11:21:49.334: The layout manager of type GtkBoxLayout 0x55aa373a5e00 does not create GtkLayoutChild instances
[eric@jesse ~]$ flatpak run com.github.flxzt.rnote 

(rnote:2): Gtk-CRITICAL **: 11:22:20.714: The layout manager of type GtkBoxLayout 0x55cb9cf1b110 does not create GtkLayoutChild instances

So it seems like it crashes only when it's opened from the app list and the app favorites

**Comment by Kneemund** [comment]
Could you open `/usr/share/applications/com.github.flxzt.rnote.desktop` (assuming that Fedora/flatpak stores the `.desktop` files there too)? There should be a line containing `Exec=[command]`. Running that command should have the same effect as launching it from the app grid.

**Comment by Heiseneberg-maybe** [comment]
The command shown in `/var/lib/flatpak/exports/share/applications/com.github.flxzt.rnote.desktop` is `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=rnote --file-forwarding com.github.flxzt.rnote @@ %f @@`. 
With this command the app opens normally and the terminal shows: 
2023-04-22T14:26:07.016Z WARN  rnote::utils > failed to query FileInfo from file
2023-04-22T14:26:07.016Z ERROR rnote::appwindow > tried to open unsupported file type

**Comment by Heiseneberg-maybe** [comment]
I just updated to version 6.0.0 and the problem disappeared. 
I downgraded to version  0.5.18 to see if the problem was still present and in doing so the app didn't load. 
So the problem is fixed in the current version, I would consider the issue closed, even tho the reason of the bug has not been discovered.
