### ISSUE TITLE
GTK 4.4 in Cargo.toml, but GTK 4.6 in meson.build

### ISSUE THREAD

**Issue by vlisivka** [flxzt/rnote#63]
Rnote compiles and works with GTK 4.4, but meson.build requires GTK 4.6 (fairly new).

  * Cargo.toml: `gtk4 = {version = "0.4", features = ["v4_4"]}`
  * meson.buidl: `dependency('gtk4', version: '>= 4.6')`

Currently supported, Fedora 34 and 35 are using GTK 4.4, while upcoming Fedora 36 will use GTK 4.6, so it's not possible to build rnote on supported version of Fedora.

Is there a reason for this?

Workaround: just change required version in meson.build from 4.6 to 4.4.

**Comment by flxzt** [comment]
See the flatpak manifest in build-aux. I am using the a Gtk version there with a specific commit because it is one after a fix that fixed #11.
