### ISSUE TITLE
HP MPP 2.0 Tilt pen: Stylus buttons action not working

### ISSUE THREAD

**Issue by Firnin** [flxzt/rnote#631]
Hey :)
First of all, thank you for this amazing piece of software, I really enjoy using it!
The only problem I really have is this: For me the actions via the stylus buttons and pressure sensitivity do not work in rnote - while those features work in Xournal++. See the attached screenshots for comparison between Xournal++ and Rnote, as well as my Rnote settings,
As it says in the title, I am using the HP MPP 2.0 Tilt pen.
Has this something to do with my settings or is this specific hardware not supported by Rnote? Thanks in advance for your answers :)

**Desktop (please complete the following information):**
 - OS: Manjaro 
 - Kernel-Version: 6.1.23-1-MANJARO (64 bit) 
 - Installation source: Flatpak
 - Desktop Environment: KDE Plasma 5.27.4, X11
 - Hardware: HP Envy x360 15-eu0xxx
![image](https://user-images.githubusercontent.com/32936646/233181176-9e93051a-d68a-4920-b2bf-2b3463de4a16.png)
![image](https://user-images.githubusercontent.com/32936646/233181337-f489fc6c-5e8f-485d-a5b5-f548797b7bb3.png)

**Comment by flxzt** [comment]
Unfortunately you are not alone with stylus pressure / the pen not being recognized, there are numerous users that report the same, mainly HP pens. See: #194, #615 .

These issues seem to be originating from the input part of the UI stack, so I don't know if we can do much about it in the application. As soon as we are able to retrieve pressure values, we use them.

Maybe check if a switch to wayland (if you are on x11) solves this. You can also check through `sudo libinput debug-events` if variable pressure is reported there, and with `sudo libinput list-devices` if the pen is recognized by it at all. But considering that it works under Xournal++ it seems to be that the issue lies somewhere in between. Does the pen pressure work in the paint demo of `gtk4-demo` ?

**Comment by LeSnake04** [comment]
@flxzt Since there are 3 issues about this already, maybe consider a "Master" issue Referenceing all specific issues so we can discus about this in general. 

Maybe also add a note about this in the Readme about this and link to the "Master" issue.

**Comment by Firnin** [comment]
@flxzt Thank you for the answer :)
The paint demo of gtk4-demo does not seem to work at all with my pen, which I find kind of strange ^^"
The stylus is being detected by `sudo libinput list-devices`
<details>
<summary>
This is my output with `sudo libinput debug-events` and a quick doodle on Xournal++
</summary>
<pre>
 event16  TABLET_TOOL_AXIS        +7.507s               270.50*/85.02*  tilt: 7.14/-0.26        pressure: 0.55*
 event16  TABLET_TOOL_AXIS        +7.509s               270.52*/84.71*  tilt: 7.15*/-0.08*      pressure: 0.55*
 event16  TABLET_TOOL_AXIS        +7.512s               270.53*/84.40*  tilt: 7.16/0.09 pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.516s               270.55*/84.13*  tilt: 7.15*/0.28*       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.521s               270.60*/83.84*  tilt: 7.14/0.46 pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.523s               270.63*/83.56*  tilt: 7.14*/0.63*       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.527s               270.68*/83.29*  tilt: 7.13/0.80 pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.531s               270.71*/83.03*  tilt: 7.12*/0.96*       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.536s               270.76*/82.76*  tilt: 7.11/1.12 pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.538s               270.79*/82.47*  tilt: 7.11*/1.27*       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.542s               270.82*/82.19*  tilt: 7.10/1.42 pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +7.546s               270.85*/81.90*  tilt: 7.09*/1.58*       pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.551s               270.90*/81.63*  tilt: 7.08/1.74 pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.554s               270.94*/81.35*  tilt: 7.06*/1.90*       pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.557s               270.97*/81.08*  tilt: 7.04/2.06 pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.561s               271.02*/80.82*  tilt: 7.00/2.22*        pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.566s               271.06*/80.55*  tilt: 6.97/2.37 pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +7.569s               271.11*/80.31*  tilt: 6.94*/2.51*       pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +7.572s               271.16*/80.05*  tilt: 6.90/2.65 pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +7.576s               271.21*/79.82*  tilt: 6.87*/2.79*       pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +7.581s               271.27*/79.58*  tilt: 6.84/2.92 pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +7.584s               271.32*/79.34*  tilt: 6.82*/3.04*       pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +7.587s               271.39*/79.10*  tilt: 6.79/3.17 pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +7.591s               271.44*/78.87*  tilt: 6.76*/3.29*       pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +7.596s               271.50*/78.65*  tilt: 6.73/3.40 pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +7.599s               271.55*/78.44*  tilt: 6.71*/3.53*       pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +7.602s               271.60*/78.24*  tilt: 6.68/3.65 pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.606s               271.65*/78.05*  tilt: 6.68*/3.80*       pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.611s               271.69*/77.87*  tilt: 6.67/3.95 pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.614s               271.76*/77.69*  tilt: 6.66*/4.09*       pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.617s               271.82*/77.52*  tilt: 6.65/4.23 pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.621s               271.90*/77.34*  tilt: 6.63*/4.36*       pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.626s               271.98*/77.18*  tilt: 6.61/4.49 pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.629s               272.08*/77.00*  tilt: 6.59*/4.62*       pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +7.632s               272.16*/76.82*  tilt: 6.56/4.74 pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.636s               272.26*/76.65*  tilt: 6.54*/4.85*       pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.642s               272.34*/76.48*  tilt: 6.52/4.97 pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.644s               272.42*/76.34*  tilt: 6.52*/5.11*       pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.647s               272.50*/76.21*  tilt: 6.52/5.25 pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.651s               272.60*/76.10*  tilt: 6.50*/5.38*       pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.656s               272.69*/76.00*  tilt: 6.48/5.51 pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.659s               272.79*/75.92*  tilt: 6.44*/5.61*       pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +7.662s               272.89*/75.84*  tilt: 6.41/5.72 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.666s               272.98*/75.76*  tilt: 6.39*/5.83*       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.671s               273.08*/75.68*  tilt: 6.38/5.95 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.674s               273.18*/75.61*  tilt: 6.37*/6.06*       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.677s               273.29*/75.55*  tilt: 6.35/6.16 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.681s               273.40*/75.48*  tilt: 6.34*/6.28*       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.686s               273.55*/75.44*  tilt: 6.33/6.40 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.689s               273.71*/75.37*  tilt: 6.32*/6.53*       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.692s               273.89*/75.31*  tilt: 6.30/6.65 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.696s               274.10*/75.24*  tilt: 6.29*/6.77*       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.701s               274.26*/75.18*  tilt: 6.28/6.89 pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +7.704s               274.42*/75.11*  tilt: 6.27*/7.00*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.707s               274.55*/75.06*  tilt: 6.25/7.11 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.711s               274.66*/75.02*  tilt: 6.24*/7.21*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.717s               274.77*/74.98*  tilt: 6.23/7.32 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.719s               274.87*/74.95*  tilt: 6.22*/7.42*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.722s               274.98*/74.92*  tilt: 6.21/7.51 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.726s               275.08*/74.89*  tilt: 6.20*/7.60*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.732s               275.21*/74.87*  tilt: 6.19/7.69 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.734s               275.35*/74.87   tilt: 6.19*/7.78*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.737s               275.52*/74.87   tilt: 6.18/7.86 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.741s               275.69*/74.87   tilt: 6.16*/7.94*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.747s               275.89*/74.87   tilt: 6.13/8.02 pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.749s               276.06*/74.87   tilt: 6.11*/8.10*       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +7.752s               276.26*/74.87   tilt: 6.09/8.17 pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.756s               276.44*/74.87   tilt: 6.07*/8.24*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.762s               276.61*/74.87*  tilt: 6.04/8.31 pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.764s               276.77*/74.89*  tilt: 6.02*/8.39*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.767s               276.95*/74.90*  tilt: 6.00/8.47 pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.771s               277.11*/74.94*  tilt: 5.97*/8.53*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.777s               277.26*/74.97*  tilt: 5.93/8.59 pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.779s               277.39*/75.00*  tilt: 5.89*/8.64*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.782s               277.52*/75.03*  tilt: 5.84/8.68 pressure: 0.64
 event16  TABLET_TOOL_AXIS        +7.786s               277.63*/75.06*  tilt: 5.80*/8.73*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.792s               277.76*/75.08*  tilt: 5.75/8.79 pressure: 0.64
 event16  TABLET_TOOL_AXIS        +7.794s               277.87*/75.11*  tilt: 5.71*/8.85*       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.797s               277.98*/75.13*  tilt: 5.67/8.92 pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +7.801s               278.10*/75.15*  tilt: 5.64*/9.00*       pressure: 0.64
 event16  TABLET_TOOL_AXIS        +7.807s               278.21*/75.16*  tilt: 5.60/9.07 pressure: 0.64*
 event16  TABLET_TOOL_TIP         +7.809s               278.47*/75.21*  tilt: 0.00*/0.00*       pressure: 0.00* up
 event16  TABLET_TOOL_AXIS        +7.857s               278.66*/75.02*  tilt: 0.00/0.00 pressure: 0.00
 event16  TABLET_TOOL_AXIS        +7.861s               278.90*/74.74*  tilt: 0.00/0.00 pressure: 0.00
 event16  TABLET_TOOL_PROXIMITY   +7.911s               279.42/74.11    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out 
-event2   KEYBOARD_KEY            +9.677s       *** (-1) pressed
</pre>
</details>

<details>
<summary>
And this is on Rnote (don't know if the opened application makes a difference)
</summary>
<pre>
event16  TABLET_TOOL_AXIS        +4.596s               155.82*/88.10*  tilt: 12.58/11.60       pressure: 0.42*
 event16  TABLET_TOOL_AXIS        +4.601s               155.81*/88.24*  tilt: 12.66*/11.59*     pressure: 0.43*
 event16  TABLET_TOOL_AXIS        +4.605s               155.77*/88.39*  tilt: 12.73/11.59       pressure: 0.43*
 event16  TABLET_TOOL_AXIS        +4.608s               155.76*/88.52*  tilt: 12.80*/11.57*     pressure: 0.44*
 event16  TABLET_TOOL_AXIS        +4.611s               155.74*/88.63*  tilt: 12.87/11.55       pressure: 0.45*
 event16  TABLET_TOOL_AXIS        +4.616s               155.73*/88.73*  tilt: 12.94*/11.53*     pressure: 0.46*
 event16  TABLET_TOOL_AXIS        +4.621s               155.71*/88.82*  tilt: 13.00/11.51       pressure: 0.46*
 event16  TABLET_TOOL_AXIS        +4.623s               155.69*/88.90*  tilt: 13.06*/11.50*     pressure: 0.47*
 event16  TABLET_TOOL_AXIS        +4.626s               155.68*/88.98*  tilt: 13.12/11.48       pressure: 0.48*
 event16  TABLET_TOOL_AXIS        +4.630s               155.66*/89.05*  tilt: 13.18*/11.46*     pressure: 0.48*
 event16  TABLET_TOOL_AXIS        +4.636s               155.65*/89.11*  tilt: 13.23/11.44       pressure: 0.49*
 event16  TABLET_TOOL_AXIS        +4.638s               155.63*/89.18*  tilt: 13.29*/11.43*     pressure: 0.50*
 event16  TABLET_TOOL_AXIS        +4.641s               155.61*/89.24*  tilt: 13.34/11.41       pressure: 0.50*
 event16  TABLET_TOOL_AXIS        +4.645s               155.60*/89.31*  tilt: 13.39*/11.38*     pressure: 0.51*
 event16  TABLET_TOOL_AXIS        +4.651s               155.58*/89.37*  tilt: 13.44/11.34       pressure: 0.51*
 event16  TABLET_TOOL_AXIS        +4.653s               155.55*/89.44*  tilt: 13.49*/11.31*     pressure: 0.52*
 event16  TABLET_TOOL_AXIS        +4.656s               155.52*/89.50*  tilt: 13.53/11.28       pressure: 0.52*
 event16  TABLET_TOOL_AXIS        +4.661s               155.48*/89.56*  tilt: 13.59*/11.26*     pressure: 0.53*
 event16  TABLET_TOOL_AXIS        +4.666s               155.44*/89.63*  tilt: 13.65/11.23       pressure: 0.53*
 event16  TABLET_TOOL_AXIS        +4.668s               155.37*/89.69*  tilt: 13.71*/11.19*     pressure: 0.54*
 event16  TABLET_TOOL_AXIS        +4.671s               155.32*/89.76*  tilt: 13.76/11.15       pressure: 0.54*
 event16  TABLET_TOOL_AXIS        +4.675s               155.24*/89.81*  tilt: 13.80*/11.11*     pressure: 0.55*
 event16  TABLET_TOOL_AXIS        +4.681s               155.18*/89.87*  tilt: 13.83/11.07       pressure: 0.55*
 event16  TABLET_TOOL_AXIS        +4.683s               155.11*/89.92*  tilt: 13.87/11.04*      pressure: 0.55*
 event16  TABLET_TOOL_AXIS        +4.686s               155.05*/89.97*  tilt: 13.90/11.00       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +4.690s               154.98*/90.02*  tilt: 13.93*/10.96*     pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +4.696s               154.92*/90.06*  tilt: 13.96/10.91       pressure: 0.56*
 event16  TABLET_TOOL_AXIS        +4.698s               154.85*/90.11*  tilt: 13.99*/10.86*     pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +4.701s               154.79*/90.16*  tilt: 14.02/10.82       pressure: 0.57*
 event16  TABLET_TOOL_AXIS        +4.705s               154.73*/90.21*  tilt: 14.07*/10.79*     pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +4.711s               154.65*/90.26*  tilt: 14.11/10.76       pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +4.713s               154.56*/90.31*  tilt: 14.15*/10.74*     pressure: 0.58*
 event16  TABLET_TOOL_AXIS        +4.716s               154.48*/90.35*  tilt: 14.19/10.71       pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +4.720s               154.40*/90.40*  tilt: 14.23*/10.68*     pressure: 0.59*
 event16  TABLET_TOOL_AXIS        +4.726s               154.32*/90.45*  tilt: 14.26/10.66       pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +4.728s               154.23*/90.50*  tilt: 14.32*/10.65*     pressure: 0.60*
 event16  TABLET_TOOL_AXIS        +4.731s               154.15*/90.55*  tilt: 14.37/10.64       pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +4.735s               154.06*/90.60*  tilt: 14.42*/10.64*     pressure: 0.61*
 event16  TABLET_TOOL_AXIS        +4.741s               153.98*/90.65*  tilt: 14.47/10.63       pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +4.743s               153.90*/90.69*  tilt: 14.50*/10.61*     pressure: 0.62*
 event16  TABLET_TOOL_AXIS        +4.746s               153.82*/90.74*  tilt: 14.53/10.58       pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +4.750s               153.74*/90.77*  tilt: 14.54*/10.55*     pressure: 0.63*
 event16  TABLET_TOOL_AXIS        +4.756s               153.66*/90.82*  tilt: 14.55/10.51       pressure: 0.64*
 event16  TABLET_TOOL_AXIS        +4.758s               153.56*/90.87*  tilt: 14.57*/10.47*     pressure: 0.65*
 event16  TABLET_TOOL_AXIS        +4.761s               153.47*/90.94*  tilt: 14.58/10.44       pressure: 0.65*
 event16  TABLET_TOOL_AXIS        +4.766s               153.37*/91.00*  tilt: 14.61*/10.42*     pressure: 0.65*
 event16  TABLET_TOOL_AXIS        +4.771s               153.26*/91.06*  tilt: 14.63/10.40       pressure: 0.66*
 event16  TABLET_TOOL_AXIS        +4.773s               153.15*/91.16*  tilt: 14.67*/10.40*     pressure: 0.66*
 event16  TABLET_TOOL_AXIS        +4.776s               153.02*/91.26*  tilt: 14.71/10.40       pressure: 0.67*
 event16  TABLET_TOOL_AXIS        +4.780s               152.89*/91.37*  tilt: 14.74*/10.39*     pressure: 0.67*
 event16  TABLET_TOOL_AXIS        +4.786s               152.77*/91.48*  tilt: 14.76/10.37       pressure: 0.67*
 event16  TABLET_TOOL_AXIS        +4.788s               152.68*/91.58*  tilt: 14.77*/10.34*     pressure: 0.68*
 event16  TABLET_TOOL_AXIS        +4.791s               152.58*/91.68*  tilt: 14.77/10.31       pressure: 0.68*
 event16  TABLET_TOOL_AXIS        +4.796s               152.50*/91.77*  tilt: 14.80*/10.30*     pressure: 0.68*
 event16  TABLET_TOOL_AXIS        +4.801s               152.42*/91.87*  tilt: 14.82/10.29       pressure: 0.69*
 event16  TABLET_TOOL_AXIS        +4.803s               152.34*/91.97*  tilt: 14.84*/10.28*     pressure: 0.69*
 event16  TABLET_TOOL_AXIS        +4.806s               152.26*/92.06*  tilt: 14.86/10.26       pressure: 0.69*
 event16  TABLET_TOOL_AXIS        +4.810s               152.18*/92.16*  tilt: 14.88*/10.25*     pressure: 0.69*
 event16  TABLET_TOOL_AXIS        +4.816s               152.11*/92.27*  tilt: 14.89/10.24       pressure: 0.70*
 event16  TABLET_TOOL_AXIS        +4.818s               152.05*/92.37*  tilt: 14.93/10.24*      pressure: 0.70*
 event16  TABLET_TOOL_AXIS        +4.821s               151.98*/92.48*  tilt: 14.96/10.25       pressure: 0.70*
 event16  TABLET_TOOL_AXIS        +4.825s               151.94*/92.56*  tilt: 14.99*/10.25*     pressure: 0.70*
 event16  TABLET_TOOL_AXIS        +4.831s               151.89*/92.66*  tilt: 15.02/10.26       pressure: 0.71*
 event16  TABLET_TOOL_AXIS        +4.833s               151.84*/92.76*  tilt: 15.03*/10.25*     pressure: 0.71*
 event16  TABLET_TOOL_AXIS        +4.836s               151.79*/92.85*  tilt: 15.04/10.24       pressure: 0.71*
 event16  TABLET_TOOL_AXIS        +4.840s               151.74*/92.95*  tilt: 15.06*/10.23*     pressure: 0.71*
 event16  TABLET_TOOL_AXIS        +4.846s               151.69*/93.05*  tilt: 15.07/10.22       pressure: 0.71*
 event16  TABLET_TOOL_AXIS        +4.848s               151.66*/93.15*  tilt: 15.08*/10.22*     pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.852s               151.63*/93.23*  tilt: 15.09/10.21       pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.855s               151.60*/93.29*  tilt: 15.08*/10.18*     pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.861s               151.58*/93.34*  tilt: 15.07/10.16       pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.863s               151.55*/93.39*  tilt: 15.08*/10.13*     pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.867s               151.55/93.44*   tilt: 15.09/10.11       pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.870s               151.53*/93.48*  tilt: 15.12*/10.09*     pressure: 0.72*
 event16  TABLET_TOOL_AXIS        +4.876s               151.52*/93.53*  tilt: 15.14/10.06       pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.878s               151.50*/93.58*  tilt: 15.17*/10.04*     pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.882s               151.48*/93.63*  tilt: 15.19/10.02       pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.885s               151.45*/93.68*  tilt: 15.21*/10.01      pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.891s               151.44*/93.74*  tilt: 15.23/9.99        pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.893s               151.40*/93.79*  tilt: 15.26*/9.97*      pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.897s               151.37*/93.84*  tilt: 15.28/9.95        pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.900s               151.34*/93.89*  tilt: 15.28*/9.94       pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.906s               151.32*/93.94*  tilt: 15.29/9.92        pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.908s               151.29*/93.98*  tilt: 15.29*/9.90*      pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.912s               151.24*/94.05*  tilt: 15.30/9.89        pressure: 0.73*
 event16  TABLET_TOOL_AXIS        +4.915s               151.21*/94.10*  tilt: 15.30*/9.87       pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.921s               151.18*/94.18*  tilt: 15.31/9.86        pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.923s               151.15*/94.24*  tilt: 15.31*/9.83*      pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.927s               151.11*/94.31*  tilt: 15.31/9.80        pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.930s               151.08*/94.37*  tilt: 15.33*/9.77*      pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.936s               151.03*/94.44*  tilt: 15.35/9.74        pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.938s               151.00*/94.50*  tilt: 15.37*/9.72*      pressure: 0.74*
 event16  TABLET_TOOL_AXIS        +4.942s               150.97*/94.58*  tilt: 15.38/9.69        pressure: 0.74
 event16  TABLET_TOOL_AXIS        +4.945s               150.94*/94.66*  tilt: 15.38*/9.66*      pressure: 0.74
 event16  TABLET_TOOL_AXIS        +4.951s               150.90*/94.76*  tilt: 15.38/9.62        pressure: 0.74
 event16  TABLET_TOOL_TIP         +4.953s               150.84*/94.97*  tilt: 0.00*/0.00*       pressure: 0.00* up
 event16  TABLET_TOOL_PROXIMITY   +5.003s               150.84/94.97    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out 
</pre>
</summary>

I will try how it works under wayland, and give feedback

**Comment by LeSnake04** [comment]
Interesting - The pressure value on rnote is actually detected.

**Comment by Firnin** [comment]
I quickly tried out a Wayland Session - The pressure sensitivity and button detection works! Well just one button, but thats enough for me.
Even the paint demo in `gtk4-demo` is working now properly
I think I stick with Wayland for now, unless there are some other breaking bugs (I sure hope not!)
Only thing under Wayland: The text in Rnote is heavily pixelated, but I can live with that.

![Screenshot_20230420_113454](https://user-images.githubusercontent.com/32936646/233325816-13807339-a98d-418f-bdaf-cad3c9d343e7.png)

**Comment by flxzt** [comment]
Since it doesn't work in gtk4-demo, my guess would be that somewhere in gtk the detection of certain HP styli fails on x11, and it falls back to being a generic pointer / mouse device without pressure. I believe the gtk4 dev's treat x11 as "deprecated", so I don't expect this to be fixed soon / at all.

If everything else works as expected in Wayland, I'd suggest switching to it permanently.

The pixelated font seems like a font hinting or aliasing issue at the DE level. In Gnome there are settings for it in "tweaks", I am sure there is something comparable in KDE.

---

@LeSnake04 no it isn't, it is only reported in libinput's diagnostic / debug tool.

**Comment by flxzt** [comment]
I'll close this as it doesn't seem to be an issue with the application and we found a solution
