### ISSUE TITLE
Rnote crashes with: "rnote internal data stream error ../libs/gst/base/gstbasesrc.c"

### ISSUE THREAD

**Issue by lepa22** [flxzt/rnote#633]
**Describe the bug**

After upgrading to Fedora 38 with GNOME 44, Rnote (installed as a Flatpak) crashes with the following error:

    internal data stream error ../libs/gst/base/gstbasesrc.c

The application does not crash completely, so after the crash the window remains open and I am able to continue using it normally, without any loss of the work I was doing. The crashes occur approximately every 5 minutes.

After the crash I get the text mentioned above in the currently open document in a typewriter box (see screenshot below). I also lose the ability to redo changes with the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> shortcut (the redo arrow works properly).

**To Reproduce**

1. Open Rnote.
2. Do something for a while, like writing something, then changing the linewidth, etc.
3. Rnote shall crash after some time (seemingly randomly, but usually less than 5 minutes).
4. After the crash the `internal data stream error ../libs/gst/base/gstbasesrc.c` will be shown in a text box and the ability to redo changes will be lost.

**Expected behavior**

Rnote should not crash.

**Console Output**

When I get a crash, `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` shows:

    2023-04-20T09:27:07.743Z DEBUG rnote::app::imp > ... env_logger initialized
    2023-04-20T09:29:38.154Z DEBUG rnote::appwindow::appwindowactions > recognized clipboard content: plain text

**Screenshots**

![image](https://user-images.githubusercontent.com/16370046/233322531-9f11028e-0150-4f1f-a0bf-de14982fc6a7.png)

**Desktop**

 - OS: Fedora
 - Version: 38
 - Installation source: Flatpak
 - Desktop Environment: Gnome 44

**Additional context**

I'm using Rnote with a Wacom One tablet.

**Comment by lepa22** [comment]
I also found that Cheese does not work and it also shows the same error:

    Internal data stream error.: ../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin35/GstPipeWireSrc:pipewiresrc1:
    streaming stopped, reason not-negotiated (-4)

So this perhaps is a GNOME  issue. But since I use the Flatpak version of Rnote, shouldn't this GNOME issue have no effect?

**Comment by Kneemund** [comment]
The error message is apparently pasted from the clipboard - that's what the console output (second line) and the fact that it is in a text box suggest. This means that it doesn't originate from Rnote, but from gstreamer.

> The application does not crash completely, so after the crash the window remains open and I am able to continue using it normally, without any loss of the work I was doing.

So it does *not* crash, right? You just get the error message from gstreamer?

**Comment by lepa22** [comment]
Hmmm... Let me check something...

**Comment by lepa22** [comment]
So I tried with another text copied and indeed it was displayed in the text box. It seems that it's the whole Shell that crashes and restarts and for some reason the last thing copied gets pasted in Rnote. So you are right, it must be indeed not an issue with Rnote, but I get this a lot with it. Haven't observed the Shell crashing with another app. So I'm closing this issue. Thanks for your insight!

**Comment by flxzt** [comment]
Just FYI, I also get shell crashes, but it seems that it actually is related to writing with the stylus. I didn't have time to investigate this further, and usually fedora gets more stable in the first weeks of a new release.
