### ISSUE TITLE
Feature request: option to hide all UI

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#634]
### Discussed in https://github.com/flxzt/rnote/discussions/510

<div type='discussions-op-text'>

<sup>Originally posted by **liakhovitch** February 14, 2023</sup>
The UI can get a little cramped on smaller devices, especially after 0.5.13. For example, the Surface Go line is meant to be the width of a vertical piece of 8.5x11 sheet when it is in _landscape_ (see attached image), and the various UI elements take away valuable canvas space. Some ideas on how to mitigate this:

- A "hide UI" button, which hides the entire UI (including titlebar). The UI can be returned via a single floating button, or perhaps some sort of gesture.
- An option to automatically hide the UI when a pen is active, and return it on a touch event. This would my personal favorite since I'm a pen-heavy user, but it may not work as well for people who do a lot of typing.

An idea on how _not_ to mitigate this:
- "Smart hide", where individual toolbars pop out from the side of the screen when the cursor is near them. This makes it tricky for touch users to make the bars show up, and for pen users it defeats the point of hiding the UI (ie, increasing usable canvas area)

![image](https://user-images.githubusercontent.com/22508850/218622960-828258de-df18-46a3-b231-b17e1cae6cf9.png)
</div>

**Comment by flxzt** [comment]
continuing in #635

**Comment by Acumane** [comment]
Great update, thank you :heart:


> various UI elements take away valuable canvas space

imo, so does the top bar—must this stick around in Focus Mode?

Also, a shortcut would be much appreciated for us on keyboards. Something like <kbd>Ctrl</kbd> + <kbd>H</kbd> or <kbd>F</kbd>?
