### ISSUE TITLE
Windows anit-maleware throws an error.

### ISSUE THREAD

**Issue by zeromero-dev** [flxzt/rnote#641]
**Error**: Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: 
rnote-win-installer-0.6.0-x86_64.exe 
Publisher:  
Unknown publisher
<br/>
Steps to reproduce: Download and run the installer.
OS: WIN11 PRO 22H2

Solution:
You probably need to add the metadata property of **Publisher** to avoid this.

**Comment by kbdharun** [comment]
This is expected as the application isn't code signed using a commercial license from a certificate authority. Code signing is expensive costing anywhere between 100 to 500 USD per year. I have noticed only a few projects, like Gaphor in the Linux ecosystem using code signing for their Windows binaries.

In the near future, you can safely ignore the warning and proceed with the application's installation.

**Comment by zeromero-dev** [comment]
Sure, didn't know it was that expansive. Learning something new everyday.
Closing the issue.

**Comment by kbdharun** [comment]
> Sure, didn't know it was that expensive. Learning something new every day. Closing the issue.

There is a cheaper alternative to this, i.e getting a Microsoft Developer license to publish to Microsoft Store, which will increase the applications reach, but for the most part `winget` would work for free.

**Comment by ghost** [comment]
@flxzt could maybe consider applying for a free code signing certificate (It is free for OSS projects): [https://signpath.org](https://signpath.org). I hope this is helpful.
