### ISSUE TITLE
Make RNote available via winget, Microsoft Store, and Mac Homebrew

### ISSUE THREAD

**Issue by relma2** [flxzt/rnote#642]
**Describe the solution you'd like**  

Exactly what it says on the tin. As a user, I would like to use a system package manager/app store to install and uninstall _rnote_.

**Comment by dehesselle** [comment]
winget is being taken care of, only a documentation update left to do: https://github.com/flxzt/rnote/pull/647

**Comment by kbdharun** [comment]
Adding to this, Microsoft Store publishing is expensive unlike adding it as a winget manifest (for free, which I did recently). You need a developer account + a code signing account which can add up pretty fast, winget is the cost-efficient and flexible middle ground in this case.  In case of Homebrew, I would suggest you create an issue in the other rnote repo for mac (if it isn't published already).

**Comment by dehesselle** [comment]
FYI issues on the [rnote_macos](https://gitlab.com/dehesselle/rnote_macos) repository are disabled on purpose to keep things consolidated here.

For the moment I consider Homebrew "out of scope" and won't be spending time on this, but you are welcome to create a cask and submit it there @relma2 .
