### ISSUE TITLE
Position of side panel is not remembered

### ISSUE THREAD

**Issue by Leon0402** [flxzt/rnote#65]
When I change the position of the side panel to "left" it is back to "right" on a restart. So the position of the panel is not rembered by rnote. 

Additionally setting the position of the side panel for the first time after a restart always fails. 
![image](https://user-images.githubusercontent.com/33933142/151021959-e1f24f29-3602-46ba-9336-35ebea574ac5.png)

Setting it once to "right" and then to "left" seems to work. This will also shift the content of the side bar a little bit. See the spacing bewteen the last color and last element compared to the previous screenshot:

![image](https://user-images.githubusercontent.com/33933142/151022382-cd9beca7-5d80-4e0d-a58d-cfc6b5e1538c.png)

Also the initial state is not marked in the UI. On startup none of the modes is selected: 
![image](https://user-images.githubusercontent.com/33933142/151022623-a55feffc-9aa5-43f6-8e64-7f15cd8f5b99.png)

I assume some of these or all of these issues could be related.

Version: 0.2.5, Distro: Arch Linux 

Some logs on the CMD that seem unrelated though: 

```
(rnote:167094): Gtk-WARNING **: 17:53:21.656: Unknown key gtk-button-images in /home/leon/.config/gtk-4.0/settings.ini
(rnote:167094): Gtk-WARNING **: 17:53:21.657: Unknown key gtk-menu-images in /home/leon/.config/gtk-4.0/settings.ini
(rnote:167094): Gtk-WARNING **: 17:53:21.657: Unknown key gtk-toolbar-style in /home/leon/.config/gtk-4.0/settings.ini
(rnote:167094): Adwaita-WARNING **: 17:53:21.713: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
(rnote:167094): Gtk-CRITICAL **: 17:53:21.748: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
(rnote:167094): Gtk-CRITICAL **: 17:53:21.750: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
(rnote:167094): Gtk-CRITICAL **: 17:53:21.803: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
(rnote:167094): Gtk-CRITICAL **: 17:53:21.803: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
(rnote:167094): Gtk-CRITICAL **: 17:53:21.819: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
(rnote:167094): Gdk-CRITICAL **: 17:54:06.660: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

```

**Comment by flxzt** [comment]
Are other app settings saved? Like pen colors, widths, format borders etc. ? Check if the "righthanded" setting is saved in dconf / gsettings after closing the app.

**Comment by Leon0402** [comment]
I also tried out the flatpak version with various things. Note thought that I never saved anything:

- sidebar position is remembered
- pencil width, rubber width are remembered
- color of pencil is not remembered
- Last used shape is not remembered 
- last active tab (brush, marker, shaper ...) is not remembered
- Sheet margin is remembered
- Sheet format is not remembered

Presumably everything related to the tools should be remembered? If I like to always draw with blue it would be great if I don't have to set it everytime. Same with other settings like the shape. 

It makes sense to me that the sheet format and things like that are not saved as they are bounded to the document itself I suppose. Although again it might also make sense to reuse the last used settings here as a default for new documents? If I make an A4 document, changes are high, my next document should be A4 too. 

For the AUR arch linux version pretty much the same applies except that the sidebar has the problems as originally described. I had a look in dconf and couldn't find a setting that sounded like the sidebar position. There was only "righthanded", which might be responsible for that? This option was always set to false and changing it to true had no visible effect. 
I'm not quite sure where I can find the settings for the flatpak version in dconf editor.

**Comment by flxzt** [comment]
the settings were refactored in v0.3.0, and should be improved significantly. Basically everything you listed should be persistent. I don't know what caused the issues with the arch package, but i would recommend switching to the flatpak version since I am testing and developing against that myself.

**Comment by maymage** [comment]
Hi.. I'm on v0.3.0 now. 

Panel position (left versus right) is not remembered.

**Comment by Leon0402** [comment]
It seems rnote had made it to community in Arch, so no AUR needed anymore! Therefore I really prefer that version over flatpak, although I will keep both for testing for now. 

The community arch version is now an v.0.3.0 as well. It doesn't contain some of the originally described issues. In particular the state of the panel is now always visible in the settings and it switches without any problems on the first click. But as said by @maymage the position is still not remembered. 

But I have the same issue with the newest flatpak version, so this might be a regression.

**Comment by flxzt** [comment]
yes, its was a regression. I'll do a bug fix release soon

**Comment by Leon0402** [comment]
Yes, I think it's good to keep it open. I can then verify for both release (arch & flatpak) that it is working.

**Comment by Leon0402** [comment]
With the patch it's working with rnote from flatpatk and from arch repos. Thanks!
