### ISSUE TITLE
Google Drive/Cloud Sync

### ISSUE THREAD

**Issue by winpower21** [flxzt/rnote#652]
Currently files can only be saved locally. If possible please add google drive/cloud support so that files can be saved to drive directly and thus be synced between platforms. 
I have tried on linux to add a google account and save files to drive by adding selecting the network drive for Google drive as directory location, but it does not work. 
Also tried using other cloud software like Mega, which worked partially. However it was finicky and at times would corrupt the files.

**Comment by ElbertCode** [comment]
This seems to be related to #461, as fixing the problem there should also fix this one.

**Comment by flxzt** [comment]
Thanks for testing it, but yes, fixing #461 should make it possible to use cloud syncing. I'll close this one as duplicate, and will track progress for a fix there.
