### ISSUE TITLE
Bundle a Handwrite-y Font

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#662]
Hi all, 

my understanding is, that the text fonts, that I can choose from here  

![grafik](https://github.com/flxzt/rnote/assets/36572014/730aa1d6-0b33-499e-987d-99ca195bd0be)

are those from my system - correct me, if I am wrong. 

If so, I do lack a nice looking handwrite-y font, that blends in well with the idea of a note taking app;
like in may case, I'd imagine that many people don't really know how to install an additional font, or if they could learn, 
are too lazy for it.
 
Therefore, in order to improve the default experience,  I would suggest to 

* bundle at least one handwrite-y font with flathub
* set it by default

Personally I like the [Virgil](https://virgil.excalidraw.com/) font that's used by Excalidraw. Tldraw uses [Shantellsans](https://shantellsans.com/).

**Comment by maymage** [comment]
Just for fun

![grafik](https://github.com/flxzt/rnote/assets/36572014/fd580983-6520-43fd-bb30-e7283b264db1)

**Comment by flxzt** [comment]
@dehesselle what would be the best way to bundle a font on MacOS, or do you know how Inkscape will do it in v1.3? Unfortunately I could not find a good way to load in a custom font programmatically in gtk, so I think we have to install it to the system on all platforms.

**Comment by dehesselle** [comment]
I think I'll add it to the application bundle and add the path so that fontconfig finds it. I'll need to run some tests to confirm.

**Comment by dehesselle** [comment]
I've figured it out. (And I noticed "I've done this before" somewhere 😆.) It's an easy setting, doesn't involve fontconfig.
I can move forward anytime, I just need to know which font to bundle.

**Comment by dehesselle** [comment]
One more thing: this feature has an impact on export formats like PDF. The font needs to be embedded during export, otherwise Rnote will create PDFs that don't look like the original drawing.

**Comment by flxzt** [comment]
Currently the text is converted into paths for all vectorized exports during the simplification step (not ideal, I know), so it shouldn't be an issue. But this should definitely be kept in mind for the future.

**Comment by flxzt** [comment]
Here's a small comparison between different open handwrite-y fonts. Open for discussion which ones should be included:

![handwrite-y fonts comparison](https://github.com/flxzt/rnote/assets/19841886/5e9f5319-15f5-4c1b-86d1-97ea7155ee93)

**Comment by maymage** [comment]
Personally, for aesthetic and readability reasons

`Virgil ~ ShantellSans > Gloriah Hallelujah > Grape Nuts`

Is there are reason, we have to choose? 
Depending on  personal handwriting, one may have a preference for one specific font over another, 
so a few distinct, yet lightweight fonts may be desirable.

**Comment by flxzt** [comment]
No, it is possible to bundle multiple fonts. I want to cover a variety of handwriting styles. In the PR right now `Virgil` and `Grape Nuts` is bundled. I personally like `Gloriah Hallelujah`, but it has a really large line height for some reason. ShantellSans style is almost too little handwrite-y in my opinion. I am also open to bundling alternatives/other (open) fonts if there are other suggestions
