### ISSUE TITLE
Text Input Field Alignment

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#667]
Hi all, 

I've started using the text input a lot more in recent time - typing is way faster than hand writing. 

However, since doing math formulae, I often have to switch between pen and keyboard, and so I often have
to recreate text input and position the text field nicely. 

It would be helpful, if the text field would

* vertically: snap to the grid line, so that the letters's base line is on the grid cell bottom
* horizontally: a new text field aligns to the left to another text field, if one is present above

I hope that screenshot makes it clear

![image](https://github.com/flxzt/rnote/assets/36572014/d00d7393-7dce-4725-9b9a-e1725aed6b68)

---

As other snapping mechanisms

* Pressing `Ctrl`while moving the text input field should free us from snapping 
* Perhaps a setting toogle under the emoji symbol would be nice too

**Comment by ElbertCode** [comment]
This seems a lot like #451 to me

**Comment by maymage** [comment]
For the vertical part, yes; the horizontal part just not so much. 

On the other hand the horizontal part is perhaps an overshoot: It should be sufficient to snap to the grid in both dimensions.
