### ISSUE TITLE
Dragging the window around in windows is not working as intended

### ISSUE THREAD

**Issue by Doublonmousse** [flxzt/rnote#677]
**Describe the bug**  
When dragging the window of the app around in windows, the window position does not follow the mouse position. In certain cases, it is possible for the window to end up fully out of the screen. 

This is a Windows only issue. It may be more a gtk issue than a rnote issue however.

**To Reproduce**  
1. Drag the window around in Windows.
2. The window does not follow the mouse position, the movement seems largely "amplified"

**Expected behavior**  
I expect the window to follow the mouse position when dragged.

**Screenshots**  
https://github.com/flxzt/rnote/assets/115779707/723ecc99-f84b-4a0b-bf4e-c5e78025158e

**Desktop :**  
 - OS: Windows 11 22H2, on surface Pro 5 (the screen has a 3:2 aspect ratio)
 - App Version: rnote v0.6.0
 - Installation Source: winget

**Comment by flxzt** [comment]
This should be fixed in Gtk now, and will land in the next Gtk release (4.12)

**Comment by Doublonmousse** [comment]
This is fixed in the 0.8.2 windows version, that probably uses the 4.12 version of gtk in mingw with the 4.10 API.
