### ISSUE TITLE
The brush configuration panel can only be closed by pressing escape when the pressure curve was changed

### ISSUE THREAD

**Issue by Doublonmousse** [flxzt/rnote#678]
**Describe the bug**  

When the brush configuration panel is opened, after changing the pressure curve profile, the only way left to close the panel is to use the escape key, it is not possible to close it using touch, pen or mouse inputs.

The same can be said of the shape configuration panel.

This is a minor annoyance for use cases where the keyboard is readily available but annoying to tablet users where the keyboard may not be used.

**To Reproduce**  
1. Open the brush configuration panel (using touch, pen or mouse)
3. Click on 'pressure curve' (once again, using touch, pen or mouse) and change the curve profile.
4. Try to close the configuration panel using touch, pen or mouse does not work (clicking on the gear icon, or outside the panel but inside the window)
5. The panel does not close. The only way is to use the escape key on a keyboard or click with the mouse outside the window.

**Expected behavior**  
I expected the panel to close like the rest of the app, by clicking outside the panel or clicking again on the gear icon. 
This stop working after step 2 (changing the pressure curve).

**Screenshot**
Using only the mouse, showing each click with an animation. The panel does not close on the first click outside the panel but inside the window, then closes on the second try, with a mouse click outside the rnote window.
[Screencast from 2023-05-15 21-19-27.webm](https://github.com/flxzt/rnote/assets/115779707/44b3aebf-3f20-45c6-8bf0-c297f57770cd)

**Desktop :**  
The issue occurs both on windows and linux. 
- hardware : surface pro 5

Linux version :
 - OS: Fedora 38 on wayland 
 - App Version: rnote v0.6.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 44.0

Windows version :
- OS: Windows 11 22H2
- App Version: rnote v0.6.0
- Installation Source: winget

**Comment by Kneemund** [comment]
Unfortunately, this behavior is caused by GTK4 bugs (see #206), so we can't do much about this.
