### ISSUE TITLE
Xournal export : when the pressure mode is set to constant in rnote, the exported xournal file contains pressure information

### ISSUE THREAD

**Issue by Doublonmousse** [flxzt/rnote#680]
**Describe the bug**  
When exporting a file from rnote where the pressure curve was set to constant, exporting to a xournal file will not remember this setting and export the initial pressure information.

**To Reproduce**  
1. Create a rnote file with pressure set to constant
2. Export the file to a .xopp one
3. Compare the two files

**Expected behavior**  
I expected the pressure information to be left out of the xopp file (and set to the constant value used in rnote)
See the files attached and the screenshot.
[New Documents.zip](https://github.com/flxzt/rnote/files/11488943/New.Documents.zip)

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/115779707/2eeaac18-4cb0-4ecd-9e5a-df309befc262)

**Desktop :**  
 - OS: Fedora 38 on Wayland
 - App Version: rnote v0.6.0
 - Installation Source: flatpak 
 - Desktop Environment: Gnome 44.0

**Comment by flxzt** [comment]
This was an oversight when pressure curves got implemented and I guess was never noticed.
