### ISSUE TITLE
Rnote_cli: export only non-blank area

### ISSUE THREAD

**Issue by antrmn** [flxzt/rnote#682]
**Is your feature request related to a problem? Please describe.**  
If I export a document using this command: `rnote_cli export --output-file test.svg test.rnote` I get ![the following output.](https://github.com/flxzt/rnote/assets/37816362/c370cf90-b245-4d4b-84f2-aa66094b5820)

As you can see, it includes the whole page which can be a waste of visiblespace when one tries to attach this somewhere. 
 
**Describe the solution you'd like**  
The application already provides a "export selection" feature. It would be useful to add a flag in the rnote_cli tool that allows to export the smallest area that includes all the points in the document, also excluding any kind of background (like the dots in the picture above).

**Comment by LeSnake04** [comment]
The background and patter can be toggled with the existing options. They also work with the new option

**Comment by antrmn** [comment]
Works like a charm. Thank you!

**Comment by antrmn** [comment]
I'll wait the PR to be merged before closing this issue

**Comment by LeSnake04** [comment]
Github should automatically close this when the pr gets accepted.

**Comment by LeSnake04** [comment]
The command you're looking for is
 `rnote-cli export selection <FILES> --no-background --no-pattern --output-format <FORMAt> all` or
 `rnote-cli export selection <FILE> --no-background --no-pattern  --output-file <PATH> all`
