### ISSUE TITLE
Ui Scales Badly on Large Screen

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#683]
Hi all, 

below what I see on my screen, when Rnote is only window. 

![image](https://github.com/flxzt/rnote/assets/36572014/0508a697-ec4b-4819-97f6-7e433bf2ed3b)

As you can see, many UI elements are far away from, where the writing action happens, so this creates uncomfortable travel distances. 

---

A partial solution would be to fix the right bar to the sheet rather than the right window border

**Comment by flxzt** [comment]
see #367.
