### ISSUE TITLE
Pointer and actual drawing unaligned

### ISSUE THREAD

**Issue by Gusser93** [flxzt/rnote#685]
**Describe the bug**  
When using a pen, the pointer and the point where I am drawing are not in the same position when not using full screen mode. This is particularly noticeable when using the eraser, where the red square is drawn at some distance from the pointer.

**To Reproduce**  
1. Open Rnote
2. Draw using OpenTabletDriver without using full screen.

**Expected behavior**  
Everything is drawn at the same point where the pointer is.

**Console Output**  
```
 2023-05-25T12:45:33.205Z DEBUG rnote > ... env_logger initialized

(rnote:704362): Gtk-WARNING **: 14:45:34.166: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Schnittstelle »org.freedesktop.portal.Inhibit« des Objekts im Pfad /org/freedesktop/portal/desktop
```

**Screenshots**  
![grafik](https://github.com/flxzt/rnote/assets/12176313/b3f4e903-7c36-4be3-8b70-61c304563125)

![grafik](https://github.com/flxzt/rnote/assets/12176313/b0853620-d7f1-4b2f-8ac6-42a5d20a8d6b)

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 - App Version: rnote v0.6.0
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: hyprland 0.25.0-1
 - xdg-desktop-portal: 1.16.0-3
 - xdg-desktop-portal-hyprland: 0.3.1-1
 - OpenTabletDriver: 0.6.0.4-3

**Additional context**  
I'm using OpenTabletDriver with my Wacom tablet, which worked fine with Xournal++. I wanted to try rnote and came across this bug. I am using Hyprland and wlroots.

**Comment by flxzt** [comment]
this might be the same issue as #338

**Comment by asuradev99** [comment]
I am having a similar issue with Arch Linux on a Surface Pro 8, which has its own pen:

OS: Arch Linux
App Version: rnote v0.7.0-1
Installation Source: Arch Linux Community Repo
Desktop Environment: Hyprland 0.26.0.3
xdg-desktop-portal: 1.16.0-3
xdg-desktop-portal-hyprland: 0.4.0-1

**Comment by OndraLipold** [comment]
Same issue on:

OS: Arch Linux
Kernel: 6.4.10-zen2-1-zen
App Version: rnote v0.7.1-1
Installation Source: Arch Linux Community Repo
Graphic Tablet Driver: xp-pen-tablet 3.2.3.230215-2
Desktop Environment: Hyprland 0.28.0-1
xdg-desktop-portal: 1.16.0-3
xdg-desktop-portal-hyprland: without

Seems like scaling problem from hyprland due to gaps and hyprbar on top. Can be fixed by running RNote in fullscreen.

**Comment by flxzt** [comment]
Since this seems to be an issue with hyprland, I'll close this issue as duplicate and will leave #779 open
