### ISSUE TITLE
wrong default install path on Windows

### ISSUE THREAD

**Issue by dehesselle** [flxzt/rnote#693]
**Describe the bug**  
This is a cosmetic issue. The Windows installer suggests `C:\Program Files (x86)\Rnote` as default installation path. This is not the correct location for 64bit apps, it's supposed to use `C:\Program Files\Rnote`. 

**To Reproduce**  
1. Run the Installer `rnote-win-installer-0.6.0-x86_64`.
2. Accept the license agreement.
3. Observe the suggested installation folder `C:\Program Files (x86)\Rnote`  in the "Select Destination Location" screen.

**Expected behavior**  
The installer suggest a default location of `C:\Program Files\Rnote`.

**Console Output**  
Not applicable.

**Screenshots**  
<img width="372" alt="image" src="https://github.com/flxzt/rnote/assets/11375494/6588717e-1262-42bb-ad33-8601d560f10e">

**Desktop (please complete the following information):**  
 - OS: Windows 10 22H2
 - App Version: rnote v0.6.0
 - Installation Source: official Windows installer

**Comment by Kneemund** [comment]
There are two potential solutions for this:

- Running the installer in 64-bit mode on x64 by adding [`ArchitecturesInstallIn64BitMode=x64`](https://jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls) (and [only allow x64](https://jrsoftware.org/ishelp/index.php?topic=setup_architecturesallowed) to run the installer), or

- changing `autopf` to `autopf64` in the line below (see [constants](https://jrsoftware.org/ishelp/index.php?topic=consts)).

https://github.com/flxzt/rnote/blob/c60af9477392a841fb7227e2704f295b6d4af42d/build-aux/rnote_inno.iss.in#L30

Apparently, 64-bit mode *can* introduce some [issues](https://jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls), but I'm not sure if they apply here.

**Comment by dehesselle** [comment]
Using the 64-bit mode should be safe to use (and the cleaner approach). The section about file system redirection is a bit misleading, it's not an issue here. The Rnote installation is self-contained to its directory.

**Comment by Kneemund** [comment]
Yeah, I agree. Since the binaries are also only intended for x64, restricting the installer to that architecture is also a good idea. [Here](https://github.com/Kneemund/rnote/actions/runs/5132619977) is a build with the 64-bit mode.

Fixing this issue is a breaking change though:
The "32-bit installer" (i.e. current release) version does not get replaced or removed by the 64-bit installer if you keep the default directory. We'll probably have to instruct users to uninstall the old version before installing the next release.

**Comment by dehesselle** [comment]
I can confirm that the installer from the artifact now has the desired behavior.

And yes, that change needs to be prominently announced in the changelog for the next release.

**Comment by flxzt** [comment]
Okay, sounds good. Unfortunate that we didn't get this right for the initial windows release, but it is what it is.

I'll quickly make the changes taken from your branch @Kneemund . Using better compression is also a good improvement.
