### ISSUE TITLE
can't save anything

### ISSUE THREAD

**Issue by wojttom** [flxzt/rnote#696]
"saving document failed" pops up everytime when i try to save, changing save destination didnt help

**Comment by flxzt** [comment]
Please use the bug report template and follow the steps in it - most importantly collect the logs when running the app through the terminal. Otherwise it is difficult to help.

**Comment by wojttom** [comment]
ok sorry,
"saving document failed" pops up everytime when i try to save, changing save destination didnt help

reproducing:
1. just save

Expected behavior:
document is saved to my desired destination or anywhere

console output:
sadly i dont know how to open a rnote console on windows, or havent found a way to open 

Desktop:
OS: win 11 22H2 
App Version: rnote v0.6.0
Installation Source: windows installer from github
