### ISSUE TITLE
high memory usage when using multiple tabs

### ISSUE THREAD

**Issue by LeSnake04** [flxzt/rnote#700]
**Describe the bug**  
When closing a tab, the memory used by the program doesnt change

**To Reproduce**  
1. Close a Tab
2. The memory used by the programs stays exactly the same.

**Expected behavior**  
The memory usage should notably decrease since the canvas should be deallocated.

**Desktop (please complete the following information):**  
 - OS: fedora 37
 - App Version: rote v0.6.0
 - Installation Source: Flatpak
 - Desktop Environment:  Gnome 43

**Additional context**

**Comment by LeSnake04** [comment]
You're right. this was a false conclusion based of the inaccurate system monitor metrics. 

About the serde_json situation: Can we avoid that by using a different serde implementation or using serde into struct?

PS: How did you generate the graphs?

**Comment by flxzt** [comment]
I think you're partially right, see the edited post above.

I wante to refactor to deserialize directly into structs, or use something more efficient than json. Not breaking the format while doing so is a challenge though.

> PS: How did you generate the graphs?

I am using [heaptrack](https://github.com/KDE/heaptrack)

**Comment by flxzt** [comment]
I found the remaining strong reference - the engine task handler held that forever. Aborting it when disposing the parent fixes the leak.

**Comment by flxzt** [comment]
we should probably track improving/reducing memory usage when deserializing in a separate issue, to keep it clean. I'll close this one. Thanks for reporting, I am glad that this is fixed.
