### ISSUE TITLE
Erasing only part of a stroke

### ISSUE THREAD

**Issue by Danacus** [flxzt/rnote#71]
**Is your feature request related to a problem? Please describe.**
I would like to be able to erase only a small part of a single stroke. For example, when I write a word and make a mistake, I would like to be able to erase part of the word and not the entire word. 

**Describe the solution you'd like**
For the erase tool to work similarly to Xournal++ and only remove anything directly under the eraser square.

**Additional context**
I'm not sure how easy to implement this would be, but I feel like this might be a non-trivial task. So it's maybe not the highest priority thing right now.

**Comment by flxzt** [comment]
A tip for an interim solution: switch the pen the same color as the background, and use that as a "white out"

**Comment by flxzt** [comment]
is now a new eraser mode!
