### ISSUE TITLE
easier dark/light mode switching

### ISSUE THREAD

**Issue by user032479798ADhiuh** [flxzt/rnote#716]
This is closely related to issue #635 but refers specifically to using the software rather than just at the export stage.

I'm frequently switching between needing dark and light mode and the usability of a program is much enhanced when it's easy and quick to switch between the two. 

I would like to be able to toggle between "normal" and "full dark" modes: not just the UI but also the image itself, including background and pen colors (and ideally embedded/pasted images too).

Being able to change the ink color of existing strokes has mitigated this problem quite a lot, as I can select all text, change the color from black to white, and then change the background separately. However, for images with lots of different colors I need to individually select the dark parts to make them readable when changing the background to dark mode. It would be nice if a single "dark mode" toggle would do everything at once.

For example, the drawing software [Excalidraw](https://excalidraw.com/) has a dark/light toggle that inverts everything. A white background switches to black, a light blue background switches to dark blue, and pen colors automatically invert their brightness (**not** colours themselves, so an image with dark green and light red pens will go to light red and dark green, so that emphasis and general appearance of the drawing is preserved).

**Comment by Kneemund** [comment]
> I would like to be able to toggle between "normal" and "full dark" modes: not just the UI but also the image itself, including background and pen colors (and ideally embedded/pasted images too).

A feature for inverting the brightness of selected strokes is being worked on in #670. Inverting images is not desirable in most cases I can think of. The PR also adds a button for inverting the brightness of the background colors.

For now, we've decided against binding this color inversion to the UI color scheme. It would require the background colors to be much more limited or even hard-coded depending on the color scheme for it to work as intended in all cases.

**Comment by flxzt** [comment]
I think with @Kneemund enhancements/features for color invertions that are included in the latest releases, this should be resolved. As @Kneemund mentioned we intentionally decided against inverting all content when changing the UI brightness scheme.
