### ISSUE TITLE
ability to reflect selected groups of strokes

### ISSUE THREAD

**Issue by user032479798ADhiuh** [flxzt/rnote#720]
currently it is possible to select a group of strokes and resize and/or rotate them. A missing feature which would be extremely useful when creating complex diagrams would be to reflect them in the horizontal or vertical axes. Either through a "reflect" button, or through, e.g., dragging the bottom left corner of the selection past the bottom right corner, to produce a mirror image.

**Comment by Kneemund** [comment]
This is a duplicate of #207, which already has a draft PR by the way.
