### ISSUE TITLE
Opening a PDF using Rnote does not open import dialog in newest version

### ISSUE THREAD

**Issue by TrojanerHD** [flxzt/rnote#725]
**Describe the bug**  
In previous versions, I could open a PDF and the import dialog for that file would automatically open

**To Reproduce**  
1. Open file explorer (in my case Dolphin)
2. Right-click on a PDF
3. Select Open With → Rnote
4. Rnote opens if it wasn't already open
5. Rnote stays in its default blank document

Alternatively, execute `rnote <document>.pdf` (nothing happens there either)

**Expected behavior**  
I expect Rnote to behave the same as in previous versions: to open the import PDF dialog for selected PDF

<details><summary><b>Console Output</b></summary>
<p>
Nothing special but for completeness sake:

```
RUST_LOG=rnote=debug RUST_BACKTRACE=1 rnote test.pdf
 2023-06-22T10:54:22.069Z DEBUG rnote > ... env_logger initialized

(rnote:8593): Adwaita-WARNING **: 12:54:22.443: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```
</p>
</details> 

**Screenshots**

[Recording 2023-06-22 at 13.01.49.webm](https://github.com/flxzt/rnote/assets/32276754/12efd7e4-260f-46a5-bffb-b204c7bf4d26)

**Desktop (please complete the following information):**  
 - OS: Arch Linux x86_64 using Kernel 6.3.8-arch1-1
 - App Version: 0.7.0-1
 - Installation Source: AUR
 - Desktop Environment: KDE Plasma 5.27.6

**Workaround**
The current workaround is to open Rnote, click on the hamburger menu in the top right, click on import file and search the file using the file selector

**Comment by Kneemund** [comment]
Thanks for the report. The fix will be included in the next minor/major release. Alternatively, you can use/rebuild the `rnote-git` package from the AUR.
