### ISSUE TITLE
Text that could be marked for translation

### ISSUE THREAD

**Issue by oscfdezdz** [flxzt/rnote#74]
**Describe the bug**

Text that could be marked for translation:
- PatternStyle enum in `src/sheet/background.rs`.
- PredefinedFormat enum in `src/sheet/format.rs`.

I've tried to surround the text with `&gettext()` but it doesn't work there.

**Comment by flxzt** [comment]
Yeah, I don't know if it is possible to translate the 'nick' attributes of GEnums directly. One would have to implement a custom [Expression](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.Expression.html) to be registered for the adwaita [ComboRows](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/git/docs/libadwaita/prelude/trait.ComboRowExt.html#tymethod.set_expression) which display the background and predefined format enums. It would match on the enums and give back a String, which could be translated with gettext

**Comment by flxzt** [comment]
Converted the list to String Lists, so they will show up in the .pot once regenerated.
