### ISSUE TITLE
Everything I type or draw converts to pink rectangle shapes

### ISSUE THREAD

**Issue by sornay** [flxzt/rnote#740]
Everything I type or draw converts to a pink rectangle, even though the color isn't set to pink.

 - OS: Windows 11 22h2
 - App Version: [e.g. Rnote v0.7.1]
 - Installation Source: winget (also tried other versions 7 and 6) tried the exe installation as well.

video:

https://github.com/flxzt/rnote/assets/22280669/b5e459ff-f252-450a-b856-b75a1f64a3a3

**Comment by Kneemund** [comment]
The same issue is described in #192, albeit on a different version and OS. I'm afraid that we can't do anything about this. What graphics card and driver do you use?

**Comment by sornay** [comment]
> The same issue is described in #192, albeit on a different version and OS. I'm afraid that we can't do anything about this. What graphics card and driver do you use?

I see. I don't have a dedicated graphic card and my CPU is pretty old too. It's Intel Pentium G645.

**Comment by Kneemund** [comment]
Alright, so it's most likely the same issue that I linked above, which we sadly can't fix on our side. 

You might be able to switch to Linux and use the Mesa GPU driver, assuming that it supports your hardware. If it does, it should/could support the required minimum OpenGL version and stop this issue from happening. 
In most cases, switching to Linux is neither an easy nor quick thing to do though, and may very well be too much trouble than it's worth.
