### ISSUE TITLE
Pen cursor disappears in fullscreen

### ISSUE THREAD

**Issue by Boris00035** [flxzt/rnote#743]
**Describe the bug**  
I am using a wacom drawing tablet. When rnote is in fullscreen mode the pen cursor disappears. When rnote is in windowed mode it does appear. The normal mouse cursor is always visible. 

**To Reproduce**  
1. Launch rnote
2. Try to find the cursor of the pen

**Expected behavior**  
I would expect to see a cursor move as I move the pen on the tablet, or when I draw.

**Console Output**  
Format says to:  "Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` and post the output", but im not running the flatpak version, as rnote is in the arch repos. I checked for rnote options that could give something similar, if anyone could assist how to get console output for not flatpak version let me know!

**Video illustrating issue**  
I was planning to include a video, but my screen capture seems to be broken :/

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 - App Version: Rnote 0.7.1
 - Installation Source: Archlinux Official Repo (tested on flatpak too, same behaviour)
 - Desktop Environment: Gnome 44.3

**Additional context**

**Comment by Kneemund** [comment]
Thanks for the report, this is most likely a Mutter/GTK bug that occurs on Wayland and can be worked around by using a GNOME extension, see #441.

**Comment by Kneemund** [comment]
Hm, the same thing could be happening on X11 too then - AFAIK it also has fullscreen unredirection. Do you mind trying if installing the extension I mentioned in the other issue "fixes" this?

**Comment by Boris00035** [comment]
Will test it out when I get home!

**Comment by Boris00035** [comment]
This did it! Thanks!

**Comment by JumpingCodes** [comment]
Worked for me to. Thank you for the link @Boris00035
