### ISSUE TITLE
(custom theme) Colour picker is not displaying any colours

### ISSUE THREAD

**Issue by RayJW** [flxzt/rnote#745]
**Describe the bug**  
The colour picker is broken and only displays the same colour for all choices. This might be related to theming, but I tried it with different themes, and they all have the same issue, so it's probably not intended behaviour either way.

**To Reproduce**  
1. Apply any theme on Gnome with Tweaks
2. Create link from your theme directory to xdg-config/gtk-4.0
3. Use [stylepak](https://github.com/refi64/stylepak) to install the theme as a flatpak
4. Give rnote permission to xdg-data/themes and xdg-config/gtk-4.0
5. Check the colour picker

**Expected behavior**  
I expect rnote to play nicely with custom themes just like all the other applications because I haven't run into similar issues with anything else so far.

**Console Output**  
>  2023-07-11T17:37:04.666Z DEBUG rnote > ... env_logger initialized
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.251: GtkImage 0x5591dc21fce0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.251: GtkImage 0x5591dc2203a0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.255: GtkImage 0x5591dc2357d0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.255: GtkImage 0x5591dc235e90 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.259: GtkImage 0x5591dc23f2e0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.259: GtkImage 0x5591dc23f9a0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.261: GtkImage 0x5591dc253730 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.
> 
> (rnote:2): Gtk-WARNING **: 19:37:05.262: GtkImage 0x5591dc253df0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/29835902/2c4582b3-6935-4701-89f1-d5f02c26043c)
![image](https://github.com/flxzt/rnote/assets/29835902/05dec6a7-8768-4f04-b370-054d459e3c86)

**Desktop (please complete the following information):**  
 - OS: Fedora 38
 - App Version: Rnote 0.7.1 (but has been happening at least since 0.6.0)
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 44.2

**Additional context**  
I tested with the [Tokyo Night](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme) and [Orchis](https://www.pling.com/p/1357889) themes, but I think I've seen it happen on other ones.

**Comment by Kneemund** [comment]
The pads of the color picker are currently rendered using `ToggleButton`s and custom CSS. The themes you've mentioned most likely overwrite the CSS.

There is a comment in the code indicating that this might change in the future, possibly making those themes work (better) with Rnote.

https://github.com/flxzt/rnote/blob/7a9eac807cb997448bc5c3038d88e2a5ca8daad1/rnote-ui/src/colorpicker/colorpad.rs#L101-L107

**Comment by flxzt** [comment]
Custom themes interfere with our custom application CSS in certain cases, so it is expected that certain things break when using them. I suggest sticking to the default appearance/style for Rnote, custom themes are not supported. I'll close it as not planned.
