### ISSUE TITLE
Add Shortcut for Adding a Page

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#746]
This comes in handy when writing with a fixed layout. 

---
Related

* https://github.com/flxzt/rnote/issues/367#issuecomment-1635659270
* In case https://github.com/flxzt/rnote/discussions/732#discussion-5355379 is ever considered, 
perhaps just `n` for a new page in contrast to `Ctrl+n` for a new document.

**Comment by flxzt** [comment]
keyboard shortcuts `<ctrl><shift>a` for adding a page and `<ctrl><shift>r` for removing a page are now implemented
