### ISSUE TITLE
Choose which panels to hide in hide-panel mode

### ISSUE THREAD

**Issue by PhilDevProg** [flxzt/rnote#747]
**Is your feature request related to a problem? Please describe.**  
I don't need the color panel most of the time. Only sometimes but on a 10.5" display it takes up space that I could use. I could toggle the hide button in the headerbar but that button also hides the other two panels which I need.

**Describe the solution you'd like**  
A little drop-down menu next to the hide button in the header bar where you can choose which panels to hide in the hide-panel mode.

**Describe alternatives you've considered**  
A setting for it in the normal settings.

**Comment by flxzt** [comment]
I don't think this should be implemented. The direction I want ot take is to lay out the toolbars differently depending on the window size. Doing this will be possible in the next libadwaita release through [breakpoints](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Breakpoint.html). I'll update the other discussion about the toolbar layout as soon as I am making progress.
