### ISSUE TITLE
Rnote and rnote-cli crashes when opening/converting old file

### ISSUE THREAD

**Issue by D0V4HKIIN** [flxzt/rnote#748]
**Describe the bug**  
Rnote 0.7.1 crashes when opening an older file. The same happens when converting the file to pdf using rnote-cli.

**To Reproduce**  
1. Download the exercises1.zip and unzip the .rnote file
2. Open in rnote v0.7.
3. Notice rnote crashing instantly

**Expected behavior**  
The file should open as any other rnote file

**Console Output**  
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` and post the output.

```
flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote                                                                                             

 2023-07-16T14:25:39.950Z DEBUG rnote > ... env_logger initialized
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /run/build/rnote/vendor/ijson/src/value.rs:801:27
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 2023-07-16T14:25:59.740Z ERROR rnote::appwindow > load_in_rnote_bytes() failed with Err: oneshot canceled
Rayon: detected unexpected panic; aborting
```

```
flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=full run com.github.flxzt.rnote                                                                                  

 2023-07-16T14:27:45.818Z DEBUG rnote > ... env_logger initialized
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /run/build/rnote/vendor/ijson/src/value.rs:801:27
stack backtrace:
   0:     0x555bb82584fe - <unknown>
   1:     0x555bb7d33e1f - <unknown>
   2:     0x555bb822f294 - <unknown>
   3:     0x555bb8259d5f - <unknown>
   4:     0x555bb825995e - <unknown>
   5:     0x555bb825a9d0 - <unknown>
   6:     0x555bb825a484 - <unknown>
   7:     0x555bb825a416 - <unknown>
   8:     0x555bb825a401 - <unknown>
   9:     0x555bb7b10a52 - <unknown>
  10:     0x555bb7b10b4c - <unknown>
  11:     0x555bb7db18e8 - <unknown>
  12:     0x555bb80baf61 - <unknown>
  13:     0x555bb80bff91 - <unknown>
  14:     0x555bb7c73421 - <unknown>
  15:     0x555bb7b19eb7 - <unknown>
  16:     0x555bb7e1781a - <unknown>
  17:     0x555bb7e175a9 - <unknown>
  18:     0x555bb825ba25 - <unknown>
  19:     0x7fef3a27c1da - <unknown>
  20:     0x7fef3a304f44 - __clone
  21:                0x0 - <unknown>
 2023-07-16T14:27:49.079Z ERROR rnote::appwindow > load_in_rnote_bytes() failed with Err: oneshot canceled
Rayon: detected unexpected panic; aborting
```

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/43830391/6c3b37c5-a10d-4d4f-bf98-1e8427d6ba50)

**Desktop (please complete the following information):**  
 - OS: Manjaro
 - App Version:  Rnote v0.7.1, rnote-cli v0.7.1
 - Installation Source: Rnote: flatpak, rnote-cli: compiled from 0.7.1 release
 - Desktop Environment: Gnome 44.3

** File that crashes: **
[exercises1.zip](https://github.com/flxzt/rnote/files/12064261/exercises1.zip)

**Comment by flxzt** [comment]
there was a missing check in the conversion if the extracted `stroke` JSON value is a `null` value. Adding [this](https://github.com/flxzt/rnote/blob/74900ef00e1235ab66317a2c5f59595163a06b8b/rnote-engine/src/fileformats/rnoteformat/maj0min5patch9.rs#L36) should fix it.
