### ISSUE TITLE
Speed and Smoothness

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#75]
Hi, 

I realized that with increased drawing speed smoothness of the objects decreases notably. 

I remember a related problem with the defunct gnome-extension "draw on your screen"

https://codeberg.org/som/DrawOnYourScreen/issues/45

Perhaps something can be done analogously?

I attach a note to explain the issue better.. 

![2022-01-31_11:28:27_sheet](https://user-images.githubusercontent.com/36572014/151777621-f67cbf99-ce97-4513-a8cd-3b5923d7f223.svg)

**Comment by diegogangl** [comment]
Can confirm with my old Intuos 3
Something like this also happens with the drawing app. Maybe it's related to the speed at which the tablet fires events?
The lines should probably be smoothed, might be useful to ask the GIMP, MyPaint or Krita devs about it

**Comment by flxzt** [comment]
@diegogangl useful to know that it is not entirely a Rnote specific issue. I also had the experience that input event occasionally get delayed or locked up for a short period of time, resulting in those sharp corners.

A possible solution might be to do some sort of interpolation between input events.
