### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by passionate2023** [flxzt/rnote#769]
1. Import menu to import txt files, docx files
2. Option to share the whole note for other users to view/search what we see in web application. basically the shared users should be able to view, search but should not have the privilege to edit/delete the notes of the entire notebook
3. type ahead with number of matches on typing and highlight text in search results in 1st level and second level navigation
4. navigation arrows to navigate the occurrences of the searched keyword in the notes when clicked via search result

**Comment by flxzt** [comment]
Please only post one issue per feature request. Otherwise it is difficult to keep track of them.
