### ISSUE TITLE
some tool section not closing....

### ISSUE THREAD

**Issue by kesu33** [flxzt/rnote#772]
**Describe the bug**  
after pressing choose button from solid to dash the option part not closing ....

**Expected behavior**  
after pressing the setting button the side option part must close..

**Screenshots**  
![rnote](https://github.com/flxzt/rnote/assets/78337487/1eb53226-16f6-4178-90a5-773031cdc49e)

**Desktop (please complete the following information):**  
 - OS: manjaro
 - App Version: [e.g. Rnote v0.7.1]
 - Installation Source: Archlinux Community Repo,
 - Desktop Environment: kde 5.27.7

**Comment by flxzt** [comment]
its a known Gtk issue (see #206)
