### ISSUE TITLE
convertion rnote to pdf with white background and black writings

### ISSUE THREAD

**Issue by kesu33** [flxzt/rnote#773]
**Please submit only one feature request in one issue!**  
In pdf convertion option the pen color (writing color) must become black with white background.

**Is your feature request related to a problem? Please describe.**  
When I am writing in dark mode, with pen color white. Now I want to convert that into pdf with background white (which option is given in print menu) but I want the color of pen must be black (as i am using black and white printer to print the pdf) . Here there is no option.

**Describe the solution you'd like**  
If there is an option in convert to pdf with black color option when writing in white it will be good.

**Comment by flxzt** [comment]
this feature request already exists (see issue #635). There also is already an implementation in PR #670.
