### ISSUE TITLE
Free-hand selection 

### ISSUE THREAD

**Issue by VodnikAngus** [flxzt/rnote#78]
The polygon selection tool only selects elements if it includes the bounding box of a line. That's very unintuitive and hard to control. The correct behavior should be selecting any element that is visibly in the selection.

Also The polygon selection tool should be renamed to free-hand selection or something similar.

**Comment by flxzt** [comment]
I agree, it was a regression. I disgree about the name, but lets keep the discussion for selector improvements in #60
