### ISSUE TITLE
Ability to rescale objects (including stroke width)

### ISSUE THREAD

**Issue by user032479798ADhiuh** [flxzt/rnote#793]
This is slightly related to #563 . Currently, rescaling objects keeps the stroke size at constant width. For handwriting in particular, this can result in details becoming illegible when the size of a selection is reduced.

In #563 it is mentioned that the ability to edit all properties of existing strokes (as in Xournal++) would be difficult to implement. If this is not easily possible, it would also be very useful to just be able to rescale an entire selection with everything "to scale". This would be useful especially in presentations, so that small details can be hidden/zoomed and edited easily.

(Current workaround: export to .xopp, resize the relevant parts of the image in Xournal++, and open the .xopp file in rnote. This works, but of course adds friction compared to being able to resize in rnote)

**Comment by flxzt** [comment]
I can see the advantage of this request.

As you mentioned, the easiest way would be to simply scale the stroke width for all suitable content types (brush strokes, shapes, maybe even text size?) on every selection resize.

**Comment by flxzt** [comment]
this got resolved with #808 !
