### ISSUE TITLE
Export pdf

### ISSUE THREAD

**Issue by VodnikAngus** [flxzt/rnote#80]
I see users exporting from Rnote to pdf, but I can't see that option. Is it a problem on my end?

![image](https://user-images.githubusercontent.com/5102074/152068735-124e72be-43c8-4ee3-918d-61e6ac7b2d57.png)

**Comment by flxzt** [comment]
you have to go through print -> as pdf currently

**Comment by flxzt** [comment]
added a seperate export action, as I don't like the print as pdf option that much
