### ISSUE TITLE
Launch the app as web application to view in browser

### ISSUE THREAD

**Issue by passionate2023** [flxzt/rnote#800]
Launch the app as web app and opens in browser

**Comment by flxzt** [comment]
It's unlikely that this will come, except for a experimental Gtk backend called [broadway](https://docs.gtk.org/gtk4/broadway.html) the UI can't be ported to web.
The only way I could see this happening is writing a entirely new web frontend, while porting/reusing the backend ("rnote-engine").

**Comment by flxzt** [comment]
yeah, I don't think this is feasible. It would be an entirely new/different project.
