### ISSUE TITLE
Hold spacebar and drag to pan

### ISSUE THREAD

**Issue by hypernovaradiation** [flxzt/rnote#805]
Please add the feature -
When the user holds the spacebar and moves the pen, allow them to drag the workspace area in the direction of the pen movement.

**Comment by flxzt** [comment]
That'd be a nice addition. I am thinking about implementing this as a configurable keyboard shortcut (like stylus buttons). This way the user is able to bind any tool, which makes it more universal.

I'll probably use `Ctrl+Space` though.

**Comment by flxzt** [comment]
With the addition of `Ctrl+Space` as a configurable shortcut (can be set to the `Tools` page and the move view tool!) this should be fixed.
