### ISSUE TITLE
Please accept $XNO (Nano) donations.

### ISSUE THREAD

**Issue by avndp** [flxzt/rnote#81]
Have been using Joplin for all my notes and just tried RNote. Great look and feel. Would love to donate to the project! Please accept $XNO (Nano) zero fee & instant donations. It is as simply as installing [Natrium app](https://play.google.com/store/apps/details?id=co.banano.natriumwallet&hl=en_IN&gl=US) or [Nault](https://nault.cc/) and pasting the address in Github page. 

Thanks!

**Comment by flxzt** [comment]
Hi, thanks! I am _really_ not into crypto though. I would appreciate a real life currency donation a lot, even if its a smaller one! I have set up a PayPal and libera donate button in the README

**Comment by rizajur** [comment]
@flxzt still no intrest in crypto in general ? 
i would like to support through btc, ltc or xmr, making a wallet is not hard and you could use it for hosting or other expenses. So saving the real life money for the linux phone or a mobile drawing tablet such as the PineNote to make an effort for porting and optimizing Rnote for those devices seems like a good choice.

**Comment by flxzt** [comment]
No, unfortunately not
