### ISSUE TITLE
Rectangle select can move the sheet

### ISSUE THREAD

**Issue by FedericoCalzoni** [flxzt/rnote#811]
**Is your feature request related to a problem? Please describe.**  
Often using the rectangle select tool I would like to select elements that are not fully inside the view. So I'm forced to zoom-out select, 'do stuff', and zoom again in. Or sometimes is not even possible in that way, if the maximum zoom-out can't feet all the elements. a.e. a long PDF. 

**Describe the solution you'd like**  
When I use the rectangle selection (I don't know if it's feasible and practical with the other tools too) I'd like to see the sheet move when the selection gets close to the edges. (As in file managers)

**Describe alternatives you've considered**  
Be able to zoom-out enough to see al the elements of the note.

**Additional context**  
The same behavior should be applied when moving a selection.

**Comment by flxzt** [comment]
Thanks for the detailed request! This is actually already implemented upstream (see #783) so it will be included in the next release.
