### ISSUE TITLE
Typewriter formatting improvments.

### ISSUE THREAD

**Issue by FedericoCalzoni** [flxzt/rnote#812]
**Is your feature request related to a problem? Please describe.**  
If the text is bold and underlined to remove the underline it is necessary to remove the formatting with the "reset text attributes" button and press again the bold. 

**Describe the solution you'd like**  
Use the same behavior of other writing programs like libreoffice or word, removing the "reset text attributes" button. 

**Additional context**  
Shortcuts for formatting should be added. ctrl+b for bold, ctrl+i for italic and ctrl+u for underline

**Comment by flxzt** [comment]
this is now implemented (see #829).
