### ISSUE TITLE
option to hide the origin indicator cross

### ISSUE THREAD

**Issue by Mitia99** [flxzt/rnote#830]
**Is your feature request related to a problem? Please describe.**  
I mostly use rnote as a Whiteboard so I'd like to have the layout as clean as possible. I already disabled patterns but I have to move the canva in order to hide the green cross. It's not that convenient.

**Describe the solution you'd like**  
![273523697-e0ffbdd5-bcf6-4b12-b526-124d170cae8c.png](https://github.com/flxzt/rnote/assets/56766778/96f4325f-8c10-40ea-ad09-dec9a019d554)

Thanks for considering this,

**Comment by silvasch** [comment]
Hey! I would like to implement this feature, but I'm not sure if it is wanted. Would this be accepted in a PR (@flxzt)?
