### ISSUE TITLE
rnote-cli not bundled with arch community package

### ISSUE THREAD

**Issue by tubbadu** [flxzt/rnote#831]
**Describe the bug**  
The `rnote-cli` binary is not found in Arch

**To Reproduce**  
1. Install rnote from the official arch repo: `pacman -S rnote`
2. Try to use `rnote-cli`
3. Not found

**Expected behavior**  
The tool should be installed alongside rnote

**Desktop (please complete the following information):**  
 - OS: EndeavourOS 
 - App Version: Rnote v0.9.0
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: KDE 5.27.

**Comment by dehesselle** [comment]
I think you need to contact the packager on the Arch Linux side, we don't build the Arch package.

**Comment by flxzt** [comment]
Yes, not bundling the cli with the main `rnote` package  is a decision of the arch packager (and a sensible one imho), not something that can be fixed upstream.
