### ISSUE TITLE
bring back adjustable sidebar width

### ISSUE THREAD

**Issue by BomberBotz** [flxzt/rnote#835]
Previously the side bar was able to scale to whatever size you wanted. Currently that does not work

**To Reproduce**  
Use v.0.9.0

**Expected behavior**  

**Console Output**  
_Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` and post the output._

not sure how to using windows :(

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/140044498/e35a9988-778f-40ee-8a7a-99eba5bea402)

You can see sidebar is huge, and there isn't a way to resize it. Moving cursor close to the sidebar doesn't give the option to resize.

**Desktop (please complete the following information):**  
 - OS: Windows 10 Pro, 22H2
 - App Version:  Rnote v0.9.0
 - Installation Source: Github 
 - Desktop Environment: N/A ?

**Comment by flxzt** [comment]
The previous behaviour was kind of a hack, and the new adaptive widgets that replaced it when the app got ported to libadwaita 1.4 are scaling automatically.

I don't think the ability to resize the width should be reimplemented, but it is possible to define and tweak the min and max widths for the sidebar. I am open for to change them to better values.

**Comment by BomberBotz** [comment]
Preferably having a method to scale it manually would be ideal. the issue with a large sidebar is that it reduces the current available drawing space, making it feel cramped. The benefits of having infinite canvas is that feeling of freedom and open space. The large sidebar restricts the canvas area which reduces the free/open feeling associated with infinite canvas. 2nd, having a large side bar that's very much empty seems sort of pointless. Like its empty space that feels like it can be used for something more useful. If its easy, I hope you can make this small change, I think it would be very benefical.

**Comment by flxzt** [comment]
I'll close, the maximum width got slightly reduced with the last release so it shouldn't take that much space any more when the window is maximized on large screens

**Comment by JeffersonLeung** [comment]
Hmm, this is mostly an issue with smaller screens as there is less real estate for writing.

**Comment by flxzt** [comment]
The sidebar should then change to a overlay when the window is narrow - the width threshold is tweakable, I'm open to increase it if you have suggestions what a good value would be

**Comment by JeffersonLeung** [comment]
Hm, I'm not sure what the value would be (though I am not exactly a coder to define a number). So like around 75% of the current size I think would be ideal, maybe less, but I would have to see first. Also, it can't be adjustable like before? Thats not a possibility anymore?

**Comment by flxzt** [comment]
It might be possible in the code, but it also makes other things more difficult and was kind of a hack. Think of layout of the sidebar - previously the (possibly translated) strings essentially became unreadable when the sidebar got too narrow. It's impossible to anticipate a large range of widths. Things become a lot easier when the min and max widths are specified values.

I increased this threshold from 1000px to 1300px. This should work a lot better.
