### ISSUE TITLE
Sidebar Titlebar doesn't respect theme when rnote window is focused

### ISSUE THREAD

**Issue by philipwilk** [flxzt/rnote#840]
**Describe the bug**  
When the app is focused, the titlebar for the sidebar uses the wrong colour. (stuck on dark) even though I have a light system theme. It appears to be respecting gnome's dark/light theme toggle over my catppuccin system theme.
This only seems to occur when focused, not when unfocused.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Use a system-wide light theme such as catppuccin
2. Have gnome dark toggle on
3. Colours don't match
![image](https://github.com/flxzt/rnote/assets/50517631/728e6b0d-65f2-4c46-b354-206feaec5946)

**Expected behaviour**  
Behaviour When unfocused (as expected):
![image](https://github.com/flxzt/rnote/assets/50517631/fc424b41-ad5c-481a-801f-b03936388fda)

**Console Output** 
N/A (empty)

**Desktop (please complete the following information):**  
 - OS: Nixos Unstable
 - App Version: v0.9.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 44.4

**Comment by flxzt** [comment]
Custom themes are not supported by Gtk4/libadwaita, so if you do use a custom theme you should either try to fix such issues with additional custom css or report them to the theme authors
