### ISSUE TITLE
Palm rejection stopped working

### ISSUE THREAD

**Issue by apmyplol** [flxzt/rnote#845]
**Describe the bug**  
Similar to #820.
Palm rejection stopped working after upgrading my system and I cannot properly write anything.
In addition to #820 touch input is also not blocked when touching the screen with the stylus  and writing something.
Before upgrading I was able to write without any problems except #534 sometimes.

**Console Output**  
`export RUST_LOG=rnote=debug RUST_BACKTRACE=1 & rnote` produces
```
 2023-10-22T12:48:03.651Z DEBUG rnote > ... env_logger initialized

(rnote:2759): Gtk-WARNING **: 14:48:03.717: Unknown key ; gtk-decoration-layout in /home/afa/.config/gtk-4.0/settings.ini

(rnote:2759): Gtk-WARNING **: 14:48:03.719: Unknown key gtk-modules in /home/afa/.config/gtk-4.0/settings.ini

(rnote:2759): Adwaita-WARNING **: 14:48:03.945: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(rnote:2759): Gtk-CRITICAL **: 14:48:04.232: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed

(rnote:2759): Gtk-CRITICAL **: 14:48:27.667: The layout manager of type GtkBoxLayout 0x5563397cba30 does not create GtkLayoutChild instances
```

**Desktop:**  
 - OS: Arch Linux (on surface device with linux-surface kernel)
 - App Version: Rnote v0.9.0
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: KDE Plasma on Wayland

**Additional context**  
I dont really know how palm detection works and have only found on libinput that there is Stylus-touch arbitration which should block touch input events when the stylus is used.
Thus i have tried to downgrade some packages (rnote, plasma-wayland-session, libwacom-surface) but none of these worked.

I would really appreciate it if someone could tell me which packages are responsible for palm rejection that I could try to downgrade or if there are any other things that I could try to get it working again because I use rnote for taking uni notes and need a working system.

**Comment by Doublonmousse** [comment]
If you're on a surface you're probably using `linux-surface` to get pen support, try searching for `iptsd` and how to configure it:

See here : https://github.com/linux-surface/iptsd/wiki/Calibrating-iptsd
There are additional parameters that can be tuned in `/etc/iptsd.conf` as well.

For some reason, everytime I tried to install `linux-surface` there was some additional configuration required (for `iptsd` to get palm rejection and stylus to work (thinks like disabling touch when the pen is on the screen is part of the config but not enabled by default !). On an older model I could get the pen and palm rejection to work reliably, but not a pro 7 (it's working ish at the moment).
