### ISSUE TITLE
Error when building: Could not find version 5.12 of Qt5Core

### ISSUE THREAD

**Issue by silvasch** [flxzt/rnote#853]
**Describe the bug**  
When building rnote on my system the build throws an error:
```
CMake Error at CMakeLists.txt:162 (MESSAGE):
  Could not find the 5.12 version of Qt5Core.  If you're not interested in
  the features it provides set the cmake ENABLE_QT5 option to OFF
Call Stack (most recent call first):
  CMakeLists.txt:212 (find_soft_mandatory_package)
```

**To Reproduce**  
1. Build the project using GNOME Builder

I could fix this bug by disabling Qt5 and Qt6 (because the same thing happens with both packages) in the poppler build configuration:

```json
// build-aux/com.github.flxzt.rnote.Devel.json
{
  "modules": {
    "poppler": {
      "config-opts": [
        "-DENABLE_QT5=OFF",
        "-DENABLE_QT6=OFF"
      ]
    }
  }
}
```

When building with this configuration the error seems to be fixed and I can launch Rnote successfully.
However, I am not sure if qt is required for something that I didn't notice. Would this be okay to disable, or am I breaking another feature?

**Comment by flxzt** [comment]
No, disabling it shouldn't break anything. Do you want to create a PR with that change? If yes, be sure to keep the yaml manifest in sync, I usually generate the json from the yaml with `yq -o=json build-aux/com.github.flxzt.rnote.Devel.yaml > build-aux/com.github.flxzt.rnote.Devel.json` (the json is necessary for gnome builder support).

**Comment by silvasch** [comment]
Perfect, I'll open a PR

**Comment by silvasch** [comment]
The PR is open.
