### ISSUE TITLE
Numbered files get sorted in an unexpected/non-sequential manner in the sidebar

### ISSUE THREAD

**Issue by kmandarin-orange** [flxzt/rnote#855]
**Describe the bug**  
Files with sequential numbers in them are sorted in an unexpected manner (sorted by each individual numeral character, not by the whole number's sequential value)

**To Reproduce**  
1. Create some folders/files that span 0-25ish
2. See that the list reads like: 1, 10, 11, 12, ... 19, 2, 20, 21...

**Expected behavior**  
Numbered files should follow in sequential order of the number's value.

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/55755379/f40a1d0c-ec41-4af4-a8ac-c1f2407cf5e4)

**Desktop (please complete the following information):**  
 - OS: Fedora 39
 - App Version: Rnote 0.9.0
 - Installation Source: Flatpak/Flathub remote
 - Desktop Environment: Gnome 45

**Comment by Doublonmousse** [comment]
Ok, looking at the code, rnote sorts filenames using the standard string comparison given by the Rust standard library (and this is most certainly a lexicographic sort).
The sorting algorithm that would sort things as you would like is called the natural sorting order.

The comparison function to compare two strings can be changed (in the `crates/rnote-ui/src/workspacebrowser/mod.rs` file in the `alphanumeric_sorter` definition) so changing it for a natural sorting order function will result in the correct order.

![image](https://github.com/flxzt/rnote/assets/115779707/68de8f48-befe-4170-a23c-0bf9e47104f5)

However, I added one crate (`humane-sort`) to get a function that would compare things this way. I didn't find it in the standard library (but I may be wrong) and other crates exist for this (`natord` seems more popular and may be less buggy, or at least there is no pending issue in the github repo). The thing is that they were not updated very recently so we should verify first that they work as expected and don't have any pending issues. But as they have the same signature for function choosing one over the over would be easy. 

Licensing should be checked as well

**Comment by flxzt** [comment]
Since these crates are pretty small and don't have any dependencies themselves I think we absolutely can bring them in. humane-sort seems to be a little more recent, but digging through the PR's there is another one that doesn't have bugs in certain edge cases: https://github.com/dragazo/numeric-sort . Dependencies with the MIT licenses are fine, they are compatible with GPL3 and we already have pently dependencies with the same license :)
