### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by yllekz** [flxzt/rnote#86]
**Describe the bug**
I installed rnote from flathub and it won't open.

**To Reproduce**
1. Install rnote from flathub
2. Open rnote
3. nothing happens
4. Side note, it seems the app has disappeared from flathub since yesterday.

**Expected behavior**
The app should open?

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon 20.3
 - Browser n/a
 - Version n/a

**Additional context**
Not sure what else to check for or look, the app should open, no?

**Comment by VodnikAngus** [comment]
Strange, it should work normally. Have you tried running RNote from command line with `flatpak run com.github.flxzt.rnote`? Try doing that and posting output for debugging

**Comment by yllekz** [comment]
Sure. The error is:

```
rnote: symbol lookup error: /app/lib/libgtk-4.so.1: undefined symbol: wl_proxy_marshal_flags
```

**Comment by flxzt** [comment]
This is definitely not a bug in the application
