### ISSUE TITLE
Issue before pull request?

### ISSUE THREAD

**Issue by silvasch** [flxzt/rnote#866]
I'm currently using rnote daily in school and I really like it. I have multiple feature requests that I would like to implement. Should I create an issue for these features first or should I just open a pull request right away?

**Comment by flxzt** [comment]
yes, I think that would be good practice and to possibly avoid wasted work. I don't always have the time to discuss feature requests in detail but I'll try to at least mark them with `discussion needed` tag if it is something where I think it needs to be discussed first before a feature implementation can be merged

**Comment by silvasch** [comment]
Ok, thanks
