### ISSUE TITLE
Ability to open files in the default app from the workspaces sidebar

### ISSUE THREAD

**Issue by silvasch** [flxzt/rnote#867]
**Please submit only one feature request in one issue!**  
I think it would be good to add a menu option in the worspaces sidebar to open files in the default system app.

**Is your feature request related to a problem? Please describe.**  
Sometimes I want to just view a PDF instead of inserting it into the drawing area. I have to open my file manager each time and navigate to the PDF.

**Describe the solution you'd like**  
Add a menu option for opening non-rnote files with the default system app in the workspace sidebar, right under "open".

![Screenshot from 2023-11-03 09-48-16](https://github.com/flxzt/rnote/assets/128063006/26e6893d-1895-4b5f-b140-06fb2718b987)

**Comment by flxzt** [comment]
good idea. The cli already brings in a crate that can provide this in a similar feature
