### ISSUE TITLE
Latest release breaks appdata

### ISSUE THREAD

**Issue by sophie-h** [flxzt/rnote#87]
I have

```xml
    <provides>
      <binary/>
    </provides>
    <launchable type="desktop-id">com.github.flxzt.rnote.desktop</launchable>
```

in my local `appstream.xml`. I think that violates the appstream standard and anyways is probably not what you want :)

Maybe it's missing [here](https://github.com/flxzt/rnote/blob/main/resources/meson.build#L88) to be available in [this line](https://github.com/flxzt/rnote/blob/main/resources/app.metainfo.xml.in.in#L59)?

**Comment by flxzt** [comment]
I'm surprised that the buildbot didn't didn't catch it, considering it even complained about a wrong date one time. Anyways, should be fixed, thanks. (btw: pika backup is really great!)
