### ISSUE TITLE
Add a `CONTRIBUTING.md` document

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#876]
### Discussed in https://github.com/flxzt/rnote/discussions/851

<div type='discussions-op-text'>

<sup>Originally posted by **YosypC** October 27, 2023</sup>
A contributing file is missing. Any plans of making one? If would speed development up.</div>

**Comment by zefr0x** [comment]
> Do you have suggestions what to include in such a file?

### Reviewers & Maintainers

- List of people who are authorized to merge PRs
- What parts does every one responsible for?

### Bug/Features Reports

- Where to file them?
- What environments are we accepting bugs for? (e.g. Linux Flatpak & Windows)
- What types of reports are we focusing on? How do we priorities them? (e.g. UI/UX & Performance)

### Development

- Programming Languages, protocols, APIs, and technologies we are relaying on for this project. (e.g. rust, xml, DBus, cairo)
- How do we manage code formatting and linting (and to what level are we enforcing them)? (e.g. clippy and `cargo format`)
- What are we using for dependency management? (e.g. cargo)
- What are we using for the building process? (e.g. meson)
- How to create a development build for testing?

### Tests

- What tools are used for testing?
- Where to write tests and what to write them for?

### Documentation

- Internal docs?
- User-Facing docs?

### Translation
- To what extend is our project internationalized?
- Is there any platform used for localization? (e.g. weblate)
- What files should we work on?
- How to handle the translation of the application name?

**Comment by flxzt** [comment]
Sounds good! I'll orient myself with an initial draft on this outline. Will open soon, please take a look!
