### ISSUE TITLE
Notes are rendered blurry spontaneously.

### ISSUE THREAD

**Issue by RayJW** [flxzt/rnote#877]
**Describe the bug**  
Since 0.9.0 or maybe 0.9.1 notes are sometimes loaded in a very blurry state and the only way to fix it is to close and reopen the affected note. It only happens on a single note, so when opening multiple notes in the same Rnote "session" some open blurry and others fine. The blurry rendering effects Rnote elements like shapes and handwriting but also embedded PDFs. It also seems like the scaling may be off because when zooming the note the blurriness is also scaled, so it's not significantly more blurry when fully zoomed in. Almost as if everything is rendered properly, just off by a factor.

**To Reproduce**  
1. Open any note.
2. Repeat if not blurry.
3. Every few times, the note is rendered in a low resolution state until being reopened.

**Expected behavior**  
The notes should look sharp every single time like in previous versions.

**Console Output**  
```
2023-11-13T13:10:56.494Z DEBUG rnote > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 14:10:56.761: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed
 2023-11-13T13:10:56.778Z DEBUG rnote_engine::store > state has not changed, no need to record
```

**Screenshots**  
![Blurry rendering](https://github.com/flxzt/rnote/assets/29835902/ae2ee004-1df1-49d7-b5b4-d786987eb61e)
![Proper rendering](https://github.com/flxzt/rnote/assets/29835902/22426091-d4f4-4c48-b7f0-9e5895e4bfec)

**Desktop (please complete the following information):**  
 - OS: Fedora 39
 - App Version: Rnote 0.9.1
 - Installation Source: Flatpak
 - Desktop Environment: 45.1

**Additional context**  
I'm not sure, but I feel like it happens more often with bigger embedded PDFs, i.e. hundreds of pages.

**Comment by silvasch** [comment]
I also noticed this. I think this only happens when a note is *not* opened in a new tab.

**Comment by flxzt** [comment]
Curious. Are you on High-Dpi screens and have set the scale factor above 150% ?

**Comment by flxzt** [comment]
Ah, the issue seems to be that the scale-factor from gtk is not updated when initial documents are loaded. I just pushed a commit that should fix it. @silvasch mind trying it out in a build on your machine just to confirm?

**Comment by silvasch** [comment]
I've tried it out, it works 👍

**Comment by flxzt** [comment]
sweet!

**Comment by RayJW** [comment]
Nice! Thanks to everyone who helped resolve this :)
