### ISSUE TITLE
Lightweight viewer (android or web)

### ISSUE THREAD

**Issue by GGORG0** [flxzt/rnote#882]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. 

After writing notes on a Linux tablet, I'd like to view those notes (synced with syncthing) on my phone without exporting to PDF. No editing is required and it can look crappy - I only need to be able to read the notes.

**Describe the solution you'd like**  

A web or android app that can open .rnote files in read-only mode

**Describe alternatives you've considered**  

Well, I can export everything to PDF, but it's hard to keep exporting all the time to keep the PDFs up-to-date.

**Additional context**  

none

**Comment by flxzt** [comment]
see #390 - I'll close as duplicate
