### ISSUE TITLE
Add Highlighter for PDF marking

### ISSUE THREAD

**Issue by Severin-Obrist** [flxzt/rnote#883]
I like using this app for annotating PDFs, but highlighting text on a PDF doesn't work great with the "marker" option for the pen, as the opacity of the brushstroke changes with pen pressure (as it should for a normal pen). I'd like to see a Marker option that just draws a brushstroke with a constant opacity, similar to how it works in apps like Xournal++.

**Comment by flxzt** [comment]
see #449 - i'll close as duplicate

**Comment by Severin-Obrist** [comment]
Didn't see that, sorry about that

**Comment by flxzt** [comment]
no problem
