### ISSUE TITLE
Eraser pen button release switches back too fast

### ISSUE THREAD

**Issue by RayJW** [flxzt/rnote#889]
**Describe the bug**  
When using a pen button to temporarily switch to the rubber this happens immediately on pressing and releasing. In my case this regularly leads to new strokes being created on accident, because when handwriting quickly, the action of releasing the button and lifting the pen naturally are done at the same time. So every time the button release is a split second faster, there will be new strokes drawn.

**To Reproduce**  
1. Temporarily switch to the rubber tool with a pen button
2. Upon release, it will immediately start to draw again

**Expected behavior**  
I feel like there should be at least a small delay or maybe the rubber should stay active until hovering again because I can't personally think of a case where I immediately want to draw at exactly the same location I stopped erasing without lifting the pen. The selection tool already works that way. When I press the button to start a selection and release it, the selection does not stop until lifting the pen again. Worst case, the delay could be made an advanced option in the settings if users complain about either of the behaviours more than the other.

**Console Output**
```bash
2023-11-16T15:15:10.571Z DEBUG rnote > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 16:15:10.820: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed
```

**Desktop (please complete the following information):**  
 - OS: Fedora 39
 - App Version: Rnote 0.9.2
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 45.1

**Additional context**
I think one workaround for this could be switching the tool of the button to the toggle state. However, that is another issue where those settings don't always apply, get stuck, and only apply to one of the two stylus buttons. That is another bug report I will file once I find the time to do so.

**Comment by flxzt** [comment]
Thanks for the detailed report. I believe #414 is a similar discussion/issue, though for a different pen.

**Comment by flxzt** [comment]
I'll close in favor of #414
