### ISSUE TITLE
Presentation Mode Options, e.g. a laser pointer

### ISSUE THREAD

**Issue by tipptop3d** [flxzt/rnote#890]
For collaboration reasons, we regularly stream our rnote app over discord but the cursor does not get captured, making it very hard to show some concepts to team mates. A feature that would help for this circumstance is something like a powerpoint laser pointer, that disappears after some time automatically, because our current solution of using the normal pen to mark something is really not the best solution.

**Comment by ElbertCode** [comment]
Isn't that a duplicate of #476?

**Comment by flxzt** [comment]
you're right, I'll close as duplicate
