### ISSUE TITLE
Can't change colors with pen

### ISSUE THREAD

**Issue by Exalm** [flxzt/rnote#9]
Seems clicking colors does nothing if you've already drawn anything with the pen until you click the window with a pointer. And the other way - if you change the color you can't draw anything until you do a click.

**Comment by flxzt** [comment]
I can't really replicate the issue, I never had problem with the pen focus when picking colors. Are you on X11 or wayland? Also I assume you have a stylus as input?

**Comment by flxzt** [comment]
Sorry about letting this issue become stale. I remember having this problem too whenever I tested rnote in a wayland session, but at some point it seemed to have resolved. Did this resolve for you as well?

There is still a similar issue with not being able to close nested popovers, that is a GTK issue and is [being tracked here](https://gitlab.gnome.org/GNOME/gtk/-/issues/4529).

**Comment by flxzt** [comment]
ok, thanks for confirming
