### ISSUE TITLE
Add Symbolic Safe Button 

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#90]
Hi, 

since saving modifications is (for now) important, please add a symbolic safe button to the header bar -  I suggest

* in expanded mode: next to the secondary `3 Dots Menu`
* in collapsed mode: top left of the header bar, where there's unused space

**Comment by flxzt** [comment]
Hm, not so sure about adding even more buttons to the headerbar. Its already pretty crowded. I think an (optional) autosave feature would be better.

**Comment by maymage** [comment]
I agree that autosave would be the superior experience - that why I wrote "for now". My 0.2€ 

* *optional* autosave is a option. Better to avoid options and keep one simple workflow.
* if autosave is optional, this issue is valid in the non-opt-in case.. saving becomes very important.
* gnome text editor does autosave, see https://gitlab.gnome.org/GNOME/gnome-text-editor/-/issues/51 abd the mockup link. 

I have no strong feelings on the topic - just that, as long as autosave is not implemented and as of now, saving is unconvenient.

**Comment by flxzt** [comment]
No, you have a point. A button does make it a lot more convenient. I don't love the position but I don't want to add another 50px or so to the minimum width for having it elsewhere, for mobile users.
![Bildschirmfoto vom 2022-02-05 16-44-39](https://user-images.githubusercontent.com/19841886/152648546-a63a5e7f-28fe-4b85-965f-efbf0bc794c3.png)

**Comment by flxzt** [comment]
added in [0c7fa28](https://github.com/flxzt/rnote/commit/0c7fa28bfd6a079f764292c36c4315f0cf41b577)

**Comment by VodnikAngus** [comment]
I don't think the icon is suitable as a save file icon. It is a download icon and I think it could be very confusing for people.

Also the icon spacing around the icon is not even it should be grouped with other icons in the top bar

**Comment by flxzt** [comment]
Its literally the from the design mockup that is linked. On another note, I don't think obsessing over little details like the spacings is a very fruitful discussion. Feel free to submit PRs though, if they are meaningful and have a clear purpose for improving a specific use case.
