### ISSUE TITLE
can't open saved file

### ISSUE THREAD

**Issue by KillerKaninchen1284** [flxzt/rnote#906]
When i wan't to save a file, it says saved, but when I wanted to open it, it says couldnt open the file, and it isnt stored as .rnote.
The Problem is that it only saves some times...

**Comment by flxzt** [comment]
Can you add more details, as requested in the bug report template? And supplying the rnote file could also be useful.

**Comment by KillerKaninchen1284** [comment]
Im sorry heres the form
*To Reproduce**  
Steps to reproduce the behavior:
make a new page, save underit says saved succesfully, close it and open it on a later occasion.
now I cant open it
it says "Dateiöffnung gescheitert" Opening file failed

**Expected behavior**  
it saves the file and im able to open it

**Console Output**  
Im not shure how to do it on windows

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**  
 - Windows 11 220506
 - App Version: 0.9.2
 - Installation Source: Guithub repo


**Additional context**  
I cant upload the original file(guithab doesnt allow it)
heres the content of the file as an .txt
[Test Guithub.txt](https://github.com/flxzt/rnote/files/13498840/Test.Guithub.txt)

**Comment by flxzt** [comment]
Can't you zip the original file? That should work.

**Comment by GabrielAPPer** [comment]
I can probably help KillerKaninchen1284 to recover his file, as I'm facing a similar issue. Whenever a file is saved, it is being saved, by default, without a file extension, so just renaming the file with .rnote at the end will make the save file work again. 
![Screenshot 2023-12-09 005645](https://github.com/flxzt/rnote/assets/84214354/31977d03-e887-468c-8619-4cd5cc428c70)
