### ISSUE TITLE
Add icons from an icon library

### ISSUE THREAD

**Issue by Aurnytoraink** [flxzt/rnote#912]
**Is your feature request related to a problem? Please describe.** 
Adwaita provides a lot of icons that can be usefull for note-taking. However, the process to import an icon is complex and requires an external app. Currently, this is the method to import an icon to the document : 

1. Open the "Icon library app"
2. Select the icon
3. Copy as SVG
4. Go back to Rnote & Paste

**Describe the solution you'd like**  
The solution would be to integrate the icon library into the toolbar, like emojis

**Comment by flxzt** [comment]
It sounds that this is pretty specific to your use case. Why not create a folder that holds the exported icons, add this folder as a workspace and have them accessible that way?

**Comment by Aurnytoraink** [comment]
Sorry, I totally forgot to answer our last comment.

> Why not create a folder that holds the exported icons, add this folder as a workspace and have them accessible that way?

I felt this solution is even more complicated than having a second app open and doing copy-paste back and forth. Also, what if you have multiple workspace, the user will have to travel between different files.

That's why I thought having a section in the toolbar, would make it more simple and efficient to add an icon to a document.

Indeed, Apple has already adopted this approach in their [Freeform app](https://www.apple.com/newsroom/2022/12/apple-launches-freeform-a-powerful-new-app-designed-for-creative-collaboration/), like you can see on this picture
![image](https://github.com/flxzt/rnote/assets/28545669/3d63f3fc-9267-4b13-9ac9-6f0bacd410f8)

With this approach, users can have a huge bank of icons without leaving the app. That's why I would to see something similar for this app !
