### ISSUE TITLE
Make Zoom tool zoom in the direction of the pointer

### ISSUE THREAD

**Issue by dmaioli** [flxzt/rnote#914]
**Is your feature request related to a problem? Please describe.**  
Currently the Zoom tool zooms in the direction of the center of the page. This makes hard for a drawing tablet user to zoom on a specific object, because it is necessary either to zoom with the touchpad with the other hand, or to very carefully move the page such that the object of interest is in the center and then zoom. 

**Describe the solution you'd like**  
Make the Zoom tool zoom in the direction of the pointer, as suggested in #695 and #580 (marked as complete by mistake?). This allows to move the pointer on the object of interest and zoom in a very simple movement, and to be consistent with the touchpad zoom gesture, which follows the pointer.

**Describe alternatives you've considered**  
I have considered all the other zoom mechanism described in #539, but even with them a drawing tablet user that wants to zoom on a specific area is forced either to use the touchpad with the other hand or to carefully position the object of interest and the zoom.

**Comment by flxzt** [comment]
The mentioned closed issue were referring to the zoom behaviour when holding <ctrl> + Scrolling with the mouse scroll-wheel.

But the zoom-tool could also be improved in the same way, I agree.

**Comment by flxzt** [comment]
implemented with #1080
