### ISSUE TITLE
Readme mentions PDF and XOPP export options but they are nowhere to be found

### ISSUE THREAD

**Issue by TimestaticYT** [flxzt/rnote#916]
**Describe the bug**  

**To Reproduce**  
1. Go to the 'burger menu'
2. Click on 'export'
3. Click on 'export document pages'
4. Click on 'export format'

**Expected behavior**  
I would expect an option to export to PDF or XOPP as mentioned in the readme file: "Document, document pages and selection export to many formats including Svg, Pdf, Xopp"

**Console Output**  
 2023-12-05T19:28:31.839Z DEBUG rnote > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 20:28:31.967: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed

(rnote:2): Gtk-CRITICAL **: 20:28:38.331: The layout manager of type GtkBoxLayout 0x55c5b6cd7340 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 20:28:38.331: The layout manager of type GtkBoxLayout 0x55c5b6dba6e0 does not create GtkLayoutChild instances

(rnote:2): Gtk-CRITICAL **: 20:28:38.331: The layout manager of type GtkBoxLayout 0x55c5b6ea1fd0 does not create GtkLayoutChild instances

**Screenshots**  
![grafik](https://github.com/flxzt/rnote/assets/58912623/a01546f3-df21-4bda-974b-c15bb4b99e90)

**Desktop**  
 - OS: Arch  Linux
 - App Version: [e.g. Rnote v0.9.2]
 - Installation Source: Flatpak, I also tried Arch Linux native
 - Desktop Environment: 45.1
 - Display Server: Wayland

**Comment by lorhof1** [comment]
For me, I've found that I can export the whole document as PDF or XOPP, but not pages or a selection. The citation from the readme seems to state that pages and selections can also be exported as PDF or XOPP, so either the readme or the application should be adjusted.

**Comment by flxzt** [comment]
I see, I adjusted the text in the Readme to make it more clear which export option supports which format
