### ISSUE TITLE
touch drawing unexpectedly draws lines

### ISSUE THREAD

**Issue by CvWild** [flxzt/rnote#925]
**Describe the bug**  
lines form between the mouse cursor and the touch input

**To Reproduce**  
1. use some version of Kde plasma
2. enable touch drawing
3. set line style to "simple" as "modeled" sometimes  suppresses the bug
4. put the mouse cursor somewhere on the drawing canvas
5. quickly tap on the screen with two fingers (alternately)

**Expected behavior**  
lines will appear between the mouse cursor and the touch input

**Console Output**  
```

 2023-12-10T15:24:36.108Z DEBUG rnote > ... env_logger initialized

(rnote:21354): Gtk-WARNING **: 16:24:36.146: Unknown key gtk-modules in /home/constantinvw/.config/gtk-4.0/settings.ini

(rnote:21354): Adwaita-WARNING **: 16:24:36.247: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(rnote:21354): Gtk-CRITICAL **: 16:24:36.461: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed

(rnote:21354): Gtk-CRITICAL **: 16:24:45.620: The layout manager of type GtkBoxLayout 0x556320622120 does not create GtkLayoutChild instances

```

**Screenshots**  
[Screencast_20231210_163945.webm](https://github.com/flxzt/rnote/assets/106761009/d7185bd3-b872-4197-aa32-52429e8491bd)
the blue ripply points are the touchscreen, the weird round grey / white circle is the mouse cursor, idk why it shows up to the top right of its original position on the screencap

**Desktop (please complete the following information):**  
 - OS: Arch Linux 
 - App Version: v0.9.3
 - Installation Source: AUR
 - Desktop Environment: KDE Plasma 6.0 Beta 1 (happened on latest stable version too)
 - Display Server: Wayland
 - Input Source: Mouse / Trackpad and Touchscreen 

**Additional context**  
i found this out on a Lenovo Yoga Tab 2 with anypen digitizer, which is recognised as touchscreen by the kernel,
but could reproduce on surface book 2 aswell
i tried to reproduce on gnome, that doesnt work. i guess it has to do with kde plasma having a different position for mouse and touchscreen each, which gnome doesnt do

**Comment by flxzt** [comment]
This is likely the same issue as in #665, I'd like to keep this in a single topic
