### ISSUE TITLE
Add two more color slots

### ISSUE THREAD

**Issue by silvasch** [flxzt/rnote#927]
**Is your feature request related to a problem? Please describe.**  
There is an inconvinient number of color slots in rnote. The color picker contains nine rows of colors, but rnote only allows eight of them in the slots. Additionally, because of how filling shapes in rnote works, it's very convenient to have a transparent color as well.

**Describe the solution you'd like**  
Increase the number of color slots by two, for: blue, green, yellow, orange, red, purple, brown, white, black and transparent.

**Comment by silvasch** [comment]
I'm not sure if I understand correctly, it's okay to add one?

Btw, this is not my first issue :), I'm the guy that added features in the last three updates. I just changed my profile pic.

**Comment by flxzt** [comment]
I know :) Yeah I think adding a single one is fine, but more than that would make the minimum width too large. Alternatively we could look into using a FlowBox that splits the color buttons into two rows, but when I tried that I couldn't get it work properly in combination with the overlay container

**Comment by silvasch** [comment]
> I know
I thought you didn't recognize me because you added the `good first issue` label.

> Yeah I think adding a single one is fine
Perfect, I actually use purple and brown daily, that's why I would like to. But I understand your concerns about the minimum width, and adding one slot already improves it for me a lot.

I'll try to implement it in tomorrow, but I might not have time.

**Comment by silvasch** [comment]
I just thought of another solution; we could add a setting to define how many color slots you want. It could be a limited range (4-10?) to make sure that every setting works nicely.

**Comment by flxzt** [comment]
Not a huge fan of that, feature creep like that can make the app too complicated in the long-term

**Comment by silvasch** [comment]
Yeah that's true... I think it's better if we just leave it at what it's at now.

**Comment by flxzt** [comment]
No single additional color? A grey or white would be useful for most, and that would be fine with me. :)

**Comment by silvasch** [comment]
Ok, it just seemed to me that you're not sure about adding a slot at all.

**Comment by silvasch** [comment]
I've added one color slot in the PR #936.
However, I'm not sure how I should set it's default color to white (because the `default_color` function does some magic calculations).

I could just leave it at the color calculated by this function, which is a blue between the two other blue tones, or I could rewrite the function to hardcode the default colors.

Personally I would hardcode the colors and choose the colors from the default gnome color palette:
![image](https://github.com/flxzt/rnote/assets/128063006/aae52021-6a7a-4064-a186-64ca98255a84)

My proposal would be

1 - Black
2 - Blue
3 - Green
4 - Yellow
5 - Orange
6 - Red
7 - Purple/Pink
8 - White
9 - Transparent

**Comment by flxzt** [comment]
The default color function is only a fallback when the initial palette colors could not be loaded from the settings. I agree that we could change to match them. When adding an additional color a settings key-value pair should also be added and synced.
But why dropping light blue? That's a commonly used color when writing to documents with dark background and I think is a good choice as default color.  
What's the reason that you want to reorder white and transparent as the last colors? Personally I'd place them right next to black, but if there is a good reason for it I am open to change it

**Comment by silvasch** [comment]
> But why dropping light blue? That's a commonly used color when writing to documents with dark background and I think is a good choice as default color.

I dropped light blue because I never use it, but I just asked some colleagues and they all use two different blue tones for writing, so it's probably better to keep it. I'd remove yellow or orange, but if you think it's better to replace purple that's fine.

I reordered white and transparent at the end because I think they are the least used.
- Black and blue are used for writing
- Green, yellow, orange red and purple are colors for drawing and things that should stand out
- White will probably be used the least because most people draw on a light background
- Transparent is at the end because it serves an entirely different purpose compared to the other colors, as it's only used for the fill color

**Comment by flxzt** [comment]
Hm, just from an aesthetic POV it would probably be best to drop purple. I mean you can still change it on your personal setup, I just think it doesn't look very nice as the default when a new user starts the app for the first time.

> I reordered white and transparent at the end because I think they are the least used.

I see. My ordering/thinking was more how it looks the most pleasant by grouping "non" colors like black, white, and transparent together followed by "real" colors, not by ordering them by how often they are used. Is that a factor in the position? I believe in practice is it roughly equally easy to reach all of them (and also is different depending if you're a left-handed or right-handed writer).

**Comment by silvasch** [comment]
> Is that a factor in the position?

I mostly just ordered them that way because that's how the order they appear in the color picker, put black at the front because it is used as a primary pen for writing, and moved transparent to the end because it's only used as a fill color and should probably be separated from the rest.

But in the end everyone has different preferences and someone just has to decide, so I think we should just use what you would use, since it's your project.

I'm still not sure what your preferred order is, where would you put white?

**Comment by flxzt** [comment]
ok. my preference would be: black - white - transparent - the other colors
