### ISSUE TITLE
Collapsed mode suggestions

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#93]
Hi, 

Using rnote in collapsed mode - to save some space for minimal width - I would like to suggest

* reduce the minimal button size in the forms panel (pen, eraser,shapes etc)
* reduce the minimal distance of the `undo + redo` buttons to the secondary menu
* if you add a symbolic safe button to the header bar https://github.com/flxzt/rnote/issues/90, move it to the top left in collapsed mode for a more equilibrated appearance
* hide the `redo` button, if space starts to lack

---

Related to https://github.com/flxzt/rnote/issues/54

**Comment by maymage** [comment]
As a plan B you could move the button panel consisting of

* `add page`
* `adjust to frame`
* `undo`
* `redo`

to a separate action bar on the bottom (containing the secondary menu button, I would suggest). 

---

I remember seeing this somewhere.. when collapsing geary from 3 to 2 pane mode. But also somewhere else. I'll investigate..

**Comment by maymage** [comment]
Elaborating further you could also merge pen and brush buttons, as 

* switching between these modes, when one of them is already selected, should be rather rare. 
* taking notes, I actually want to stick with one type of pen. Choosing the wrong button in the vertical selection is then rather disturbing the appearance of the notes.  
  
---

So something like, as shown below in the state, when the `Pen` is selected.  

```
Close      = X

Save       = S

Pen Symbol = P

Solid Curved Line Symbol       = A  

Brushed Curved Line Symbol     = B

Dashed & Brushed Line Symbol   = C

Option Wheel        = W

------------------------------------------
| S |          Headerbar            |  x |
------------------------------------------
| P |  P  |  Shapes | Eraser | ..........|
------------------------------------------
| A |                                    |  
-----                                    -
| B |                                    |
-----                                    -
| C |                                    |
-----                                    -
| W |           Your Content             |
-----                                    -
|   |                                    |
|   |                                    |
|   |                                    |
|   |-------------------------------------
|   |||      Secondary Action Bar      |||
------------------------------------------
```

**Comment by flxzt** [comment]
I took some of your suggestions in consideration and implemented them, for other things I went a bit of a different route, but I think this should resolve this in any case.

![Bildschirmfoto vom 2022-05-01 15-33-10](https://user-images.githubusercontent.com/19841886/166148240-a0fa9396-95dd-4595-b75d-b77db110a4ee.png)
