### ISSUE TITLE
In top panel color are not visible

### ISSUE THREAD

**Issue by NischalDawadi** [flxzt/rnote#931]
**Describe the bug**  
![Screenshot from 2023-12-12 20-14-21](https://github.com/flxzt/rnote/assets/97089847/df8a65a6-ccca-4101-adc1-9c6e453cef2e)
Top panel colors are not shown

**Console Output**  
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote`
and post the output.
flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote
 2023-12-12T14:33:47.511Z DEBUG rnote > ... env_logger initialized

(rnote:2): Gtk-CRITICAL **: 20:18:47.769: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed

(rnote:2): Gtk-WARNING **: 20:18:48.041: GtkImage 0x55b0b3253f20 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.041: GtkImage 0x55b0b3254550 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.045: GtkImage 0x55b0b327ff00 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.045: GtkImage 0x55b0b32805c0 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.048: GtkImage 0x55b0b328a480 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.048: GtkImage 0x55b0b328ab40 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.050: GtkImage 0x55b0b32a1f50 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

(rnote:2): Gtk-WARNING **: 20:18:48.050: GtkImage 0x55b0b32a2610 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

**Desktop (please complete the following information):**  
 - OS: Fedora 39
 - App Version: . Rnote v0.9.3
 - Installation Source: Flatpak
 - Desktop Environment:  Gnome 45.2
 - Display Server: Wayland
 - Input Source: [Mouse and Keyboard, On-Screen-Tablet]

**Comment by flxzt** [comment]
It looks like you have applied a custom theme. Unfortunately custom themes are not supported, so try using the default style to fix it.

**Comment by NischalDawadi** [comment]
Thank you.. It solved the issue

**Comment by arunoruto** [comment]
Sorry for commenting on an issue that is already closed.
I wanted to know if it's possible to just exclude rnote from the custom GTK theming. I haven't found much on excluding Gnome apps from themes, and I am using Nixos, so it makes it even a bit more tricky.

**Comment by flxzt** [comment]
Afaik it is only possible to set a custom theme with the `GTK_THEME` variable. I suppose you could set it to `Adwaita` only for Rnote
