### ISSUE TITLE
Better appdata screenshots

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#933]
The current appdata screenshots are not quite in line with the new Flathub [metadata quality guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), in particular:

- They're too tall (should be 1000x700 pixels or smaller)
- Window controls are non-standard (should be close-only)

This is becoming more important since we want to use app screenshots in featured banners and the like in the future :)

**Comment by flxzt** [comment]
Thank you for the reminder :) We should definitely do this before the next release
