### ISSUE TITLE
Zoom level in document settings menu not updated when switching tabs

### ISSUE THREAD

**Issue by davidhi7** [flxzt/rnote#935]
**Describe the bug**  
When working in a tab with a zoom level != 100% and switching to a newly created tab, the zoom level in the "document settings" menu (opened by clicking the button showing a document with a wrench) is still set to the zoom level in the previous tab.

**To Reproduce**  
1. In the current tab, zoom in or out to set the zoom level to something else than 100%
2. Create a new tab with the button in the top left
3. Click the button on the top right with the document and the wrench 
5. The zoom level indicator in the top of the opened menu still shows the zoom level of the tab used in Step 1 

**Expected behavior**  
Zoom level for new tabs should always display 100%

**Console Output**
```
2023-12-14T20:38:21.494Z DEBUG rnote > ... env_logger initialized

(rnote:47483): Gtk-CRITICAL **: 21:38:21.819: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed
```
This output is logged right after starting rnote and should be unrelated to the bug.

**Desktop (please complete the following information):**  
 - OS: Arch Linux with up to date packages
 - App Version: Rnote v0.9.4
  - Installation Source: Archlinux Community Repo
 - Desktop Environment: Gnome 45.2
 - Display Server: Wayland
 - Input Source: trackpad and wacom drawing tablet

**Additional context**  
Just wanted to say thank you for your amazing work with this program. I use it daily for lectures and it is a joy to use.

**Comment by flxzt** [comment]
Thanks for the detailed bug report. It should now be fixed
