### ISSUE TITLE
untranslated strings

### ISSUE THREAD

**Issue by detiam** [flxzt/rnote#939]
**Describe the bug**  
I didn't find any strings of these two button on top of sidebar on weblate, do they translatable?

**Screenshots**  
![图片](https://github.com/flxzt/rnote/assets/44510779/f1374df3-57cf-46b2-a14b-d8e5a435916f)

**Comment by flxzt** [comment]
huh, what an oversight for such a long time. The strings are marked as translatable, but the file containing them was not added to the files list in POTFILES.

**Comment by flxzt** [comment]
thanks for reporting!
