### ISSUE TITLE
Location and Naming Improvement

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#95]
When saving a sheet to e.g. `Documents`, rnote in the headerbar shows 

* some wizzardy location in gray, see screenshot

![location_name](https://user-images.githubusercontent.com/36572014/152633801-8ff414e5-871e-40a6-8732-3e91f556f0a5.png)

* the ending .rnote, which could be removed

**Comment by flxzt** [comment]
The dir should be correct if you grant rnote permissions (in flatseal) to the saved location:
![Bildschirmfoto vom 2022-02-05 13-50-36](https://user-images.githubusercontent.com/19841886/152642851-a0cfb079-e2ed-4e73-a541-69eaff0ee6ad.png)

I agree that the file extension could be dropped, it only ever shows .rnote anyways.

**Comment by maymage** [comment]
I see.. so by default rnote should have access to maybe

* xdg-documents
* xdg-pictures
* xdg-downloads

That's also super legitimate..

**Comment by flxzt** [comment]
I agree
