### ISSUE TITLE
Handwriting to Text

### ISSUE THREAD

**Issue by MiskolcziRichard** [flxzt/rnote#951]
It would be really nice to have a _handwriting to text_ feature, like the one seen in Samsung Notes or Apple Notes.

**Describe the solution you'd like**  
It would probably be the most intuitive to make this a toggle option in the _Typewriter_ menu, and then the user's handwriting would be converted to written text. It would make for a comfortable writing experience, retaining the aspect of handwriting which boosts memorization, while also resulting in clean, good-looking notes.

Additionally, the location of the handwritten text could also be taken into consideration. What I mean is that the starting point of the handwriting could be translated into the starting position of the textbox which will contain the converted text. If I start writing with a pencil in the upper right corner, the converted text could appear in a new textbox exactly where I wrote it on the page.

**Comment by flxzt** [comment]
I agree that this would be nice, but please first search existing issue - it is already requested in #327
