### ISSUE TITLE
QOL: Exit select tool by tapping pen on canvas

### ISSUE THREAD

**Issue by PJansky** [flxzt/rnote#953]
In order to exit the selection tool I instinctively tap my pen on the canvas. Instead of just exiting the selection mode, it also starts drawing a new stroke, which I then have to erase. I feel like just exiting the selection tool would be the expected behavior and Xournalpp also handles it this way. Drawing when something is selected also doesn't seem very intuitive to me. It's minor thing but I think it would improve the usability of the App, at least for me.

**Comment by flxzt** [comment]
actually there is already an issue for this #414 - I'll close as duplicate
