### ISSUE TITLE
Use the initial aspect ratio when resizing images and pressing CTRL

### ISSUE THREAD

**Issue by s12wu** [flxzt/rnote#959]
I often find myself in this situation when resizing images (or any other shape):
1. select an image
2. drag a corner to resize it
3. "Oh, the image gets stretched! I need to press `ctrl` to maintain its aspect ratio!"
4. Press CTRL while still dragging the corner - the image stays stretched and locks to the new aspect ratio.

When this happens, I often need to stop dragging, press `ctrl+z` to undo it, and then resize again while holding `ctrl` right from the beginning.

**Describe the solution you'd like**  
Use the original aspect ratio when pressing down `ctrl`

**Describe alternatives you've considered**  
Maybe it would be even possible to add some kind of snapping function - If you drag the image very close to the original aspect ratio, it will automatically snap to the exact original ratio.

**Additional context**  
rnote 0.9.4 installed from Manjaro repositories

I found it implemented like this in Inkscape

https://github.com/flxzt/rnote/assets/90598549/21057bc3-b0d4-487a-b11f-daec1357b44e

**Comment by flxzt** [comment]
Agreed, that would make more sense.

**Comment by flxzt** [comment]
is fixed with aa0cd4ccc93ddbba0ff2f2312d834f479ad8454b
