### ISSUE TITLE
Change keyboard shortcuts for `new document`

### ISSUE THREAD

**Issue by silvasch** [flxzt/rnote#961]
**Is your feature request related to a problem? Please describe.**  
The current shortcuts for window and tab-management are very different to how official gnome apps work. The current shortcuts are:
- `Ctrl-n`: Create new document, replaces currently open document
- No shortcuts for creating a new window
- No shortcuts for creating a new tab

**Describe the solution you'd like**  
Change them to how they are in other apps:
- `Ctrl-n`: Create a new rnote window
- `Ctrl-t`: Create a new document *in a new tab*

**Comment by flxzt** [comment]
Agreed! The old one is from before tabs were implemented. The [Gnome HIG](https://developer.gnome.org/hig/reference/keyboard.html#basic-shortcuts) doesn't mention ctrl+t for new tab, but it seems to be convention among other apps so sounds good to me.
