### ISSUE TITLE
A way to paste without a keyboard

### ISSUE THREAD

**Issue by Sporknife** [flxzt/rnote#962]
**Is your feature request related to a problem? Please describe.**  
When I want to paste an image or text into the text field, I have to use my keyboard, which means I have to switch from my stylus to the keyboard or paste everything I need to the canvas/view beforehand.

**Describe the solution you'd like**  
I suggest implementing double-finger press for 1 sec to paste whatever it is in the clipboard.

**Describe alternatives you've considered**  
Other than using the keyboard, there isn't much. Pasting images into the view before using the stylus.

**Comment by flxzt** [comment]
It is possible, check the clipboard submenu in the app-menu:
![grafik](https://github.com/flxzt/rnote/assets/19841886/2afc34c5-d80b-4ae4-83d1-ed3246d29d68)

Hopefully it will also be possible to do that in the context-menu that gets added in #861

**Comment by Sporknife** [comment]
Bruh.
