### ISSUE TITLE
Geometric Figure Recognition 

### ISSUE THREAD

**Issue by bestlinuxgamers** [flxzt/rnote#965]
The ability to have rnote automatically recognize and enhance geometric shapes would be immensely valuable.
It improves the user experience as it removes the need to switch to the geometry tool (and back) for drawing simple shapes as e.g. straight lines.

This would be my proposal on how to implement this feature:
- Introduce a toggle within the drawing tool settings to enable geometric figure recognition.
- Focus on recognizing the most important shapes, including straight lines, squares, and triangles.
- Activate the geometric figure recognition only if the pen has not been released from the display for a certain amount of time after drawing a shape. This prevents false corrections and ensures intentional use of the feature.
- Provide the option to manually discard the corrected shape and restore the original line if needed.

**Comment by weisbrja** [comment]
I find circles to be pretty important too.

**Comment by flxzt** [comment]
This is already requested in #120 - I'll close as duplicate
