### ISSUE TITLE
Deleting selections by the eraser tool

### ISSUE THREAD

**Issue by bestlinuxgamers** [flxzt/rnote#967]
Currently it is only possible to delete a selection by pressing the delete key.
It would be intuitive to be able to delete a whole selection by using the eraser tool with the "delete lines" option enabled.

For this to be possible a selection would need to stay selected after switching back from the selection tool.

**Comment by flxzt** [comment]
You can also delete selections with the delete button in the side-toolbar.

**Comment by bestlinuxgamers** [comment]
Ah, that's right. That makes the workflow a lot better. Nevertheless, it would be nice to be able to delete selections in this way, as you can delete selections more directly with a stylus. But I understand that this function is not really the highest priority.

**Comment by flxzt** [comment]
I don't think this can be easily implemented, since the tools are always currently completely separate from each other. But I think your issue should already be covered by this button
