### ISSUE TITLE
Make indivitual tools from the tools tab available as shortcuts

### ISSUE THREAD

**Issue by bestlinuxgamers** [flxzt/rnote#968]
Currently it is not possible to switch to specific tools from the "Tools" tab like the "Move View" or "Insert Vertical Space" tool by a shortcut. It is only possible to move to the whole tab and use whatever tool was used last. Especially the lack of quickly switching to the "Move View" tool makes the process of moving around the page cumbersome as it necessitates the use of a mouse (instead of moving with a stylus).

This would greatly improve the efficiency of navigating and manipulating content within the app, offering users a more intuitive experience.

**Comment by flxzt** [comment]
The behaviour that the shortcuts are more "coarse" and only switch to the general was an intentional decision - this way the last used tool can be accessed through a shortcut, is remembered and can be changed without changing the actual shortcut in the settings.
