### ISSUE TITLE
Images imported from Xournal++ all appear on the first page

### ISSUE THREAD

**Issue by Danacus** [flxzt/rnote#97]
**Describe the bug**
When importing a file from Xournal++ with different images on different pages, they will all appear on the first page in rnote.

**To Reproduce**
1. Create a new file in Xournal++
2. Add an image to the second page
3. Open the .xopp file in rnote
4. The image appears on the first page

**Expected behavior**
I expected the image to appear on the second page instead.

**Screenshots**

![image](https://user-images.githubusercontent.com/7491613/152641428-2c2b1151-266b-45af-8287-776b968cdde4.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.3.3 (flathub)

**Additional context**
I'll try to figure out why this is happening.

**Comment by maymage** [comment]
See https://github.com/flxzt/rnote/issues/15

You may wish to report there and close this issue.

**Comment by flxzt** [comment]
@maymage its a new bug, so its fine. :)

**Comment by Danacus** [comment]
I think I might have found the issue. Shouldn't `y_offset` be added here, similar to the strokes?

https://github.com/flxzt/rnote/blob/861baa0efd8bdf450e4a2f5a75aad41f92e31da9/src/sheet/mod.rs#L212-L217

I'm currently trying to build rnote.

**Comment by flxzt** [comment]
Yes, I already fixed it :smile:

**Comment by flxzt** [comment]
But if you have any other questions regarding the code / building / contributing, please ping me so maybe I can help out
