### ISSUE TITLE
Resize image content to fit page-width while pasting from clipboard

### ISSUE THREAD

**Issue by claws99** [flxzt/rnote#974]
I'm a teacher, I use lot of images from Internet (which are obviously of different resolutions). Copy-Pasting them is really cumbersome,  as the image goes out of boundaries of the page.

Solution would be to scale the image to say 30-40% of the page in visibility without compromising on resolution or aspect ratio.

**Comment by flxzt** [comment]
That should be easy to implement, and a nice QoL improvement. But I'd say the original size should be used as long as it is smaller than the current viewport, and capped to the viewport when it is larger?

**Comment by MisterE123** [comment]
> That should be easy to implement, and a nice QoL improvement. But I'd say the original size should be used as long as it is smaller than the current viewport, and capped to the viewport when it is larger?

That sounds reasonable

**Comment by claws99** [comment]
> But I'd say the original size should be used as long as it is smaller than the current viewport, and capped to the viewport when it is larger?

agreed!
