### ISSUE TITLE
Don't move hamburger menu with sidebar on the left

### ISSUE THREAD

**Issue by MariusAlbrecht** [flxzt/rnote#984]
**Is your feature request related to a problem? Please describe.**  
Currently the hamburger menu is on the right if the sidebar is closed. If the sidebar is opened it will be in the top right of the sidebar. If the sidebar is set to be on the right then that -visually- makes sense. However, if the sidebar is set to be on the left then the hamburger menu also moves to the left along with it.
I do not think this intuitive at all and makes the menu hard to find at times.

**Describe the solution you'd like**  
Keep the menu position static (on the right) by default and maybe allow an opt-in for the current behaviour in case it makes sense for people.

**Comment by flxzt** [comment]
Thanks for the suggestion, but I think it's more beneficial to follow the convention of the ecosystem here, what other libadwaita based apps with a sidebar also do (nautilus, foliate, ..)

**Comment by MariusAlbrecht** [comment]
Can you expand on this, I'm not sure I understand.

And just to be sure I'm clear with the issue I'm talking about:
![Screenshot from 2024-01-23 19-33-24](https://github.com/flxzt/rnote/assets/64852250/4e6fdb20-ab3c-415c-8d78-40c5e21cefcc)
![Screenshot from 2024-01-23 19-34-10](https://github.com/flxzt/rnote/assets/64852250/4a1c881e-8b59-4859-9e4d-119f418d97ef)
The hamburger menu moves for no intuitive reason from right to left.

**Comment by flxzt** [comment]
Other apps with the same hamburger-menu position:

![Bildschirmfoto vom 2024-01-23 19-49-57](https://github.com/flxzt/rnote/assets/19841886/79f68579-90ae-4da7-b8e9-06fb237bd5ee)

![Bildschirmfoto vom 2024-01-23 19-51-15](https://github.com/flxzt/rnote/assets/19841886/44de7cbe-47c2-42e1-bc97-aa7f13d67cfb)

**Comment by johnfactotum** [comment]
The primary menu should be either always on the sidebar or always on the main pane. Changing the button's position when the sidebar is toggled feels odd and a bit disruptive. IMO the menu should be always on the sidebar, and items that are specific to the current document, e.g. <i>Print</i>, <i>Save As</i>, <i>Clipboard</i>, and <i>Export</i>, should be moved to the main pane.
