### ISSUE TITLE
Export selection: Margin setting has no effect

### ISSUE THREAD

**Issue by davidhi7** [flxzt/rnote#986]
**Describe the bug**  
When exporting an section, specifying the margin around the selection has no effect on the exported file, while being correctly displayed in the export preview. This behaviour is the same for all image formats (svg, png, jpeg).

**To Reproduce**  
1. Create a canvas, draw something, select it
2. Go to 'Export' > 'Export section'
3. Change the 'Margin' option to something greater than zero
4. Open the exported image, observe the lack of margins

**Expected behavior**  
Margins should be applied if configured.

**Console Output**  
```
david > ~ $ RUST_LOG=rnote=debug RUST_BACKTRACE=1 rnote
 2024-01-26T22:04:35.099Z DEBUG rnote > ... env_logger initialized

(rnote:20831): Gtk-CRITICAL **: 23:04:35.489: gtk_widget_class_set_accessible_role: assertion '!gtk_accessible_role_is_abstract (accessible_role)' failed
 2024-01-26T22:04:35.507Z DEBUG rnote_engine::store > state has not changed, no need to record

(rnote:20831): Gtk-CRITICAL **: 23:05:39.682: The layout manager of type GtkBoxLayout 0x5f5ddf5f4850 does not create GtkLayoutChild instances

(rnote:20831): Gtk-CRITICAL **: 23:05:39.682: The layout manager of type GtkBoxLayout 0x5f5ddf6bcfb0 does not create GtkLayoutChild instances

(rnote:20831): Gtk-CRITICAL **: 23:05:39.682: The layout manager of type GtkBoxLayout 0x5f5ddf7a4a00 does not create GtkLayoutChild instances
```

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 - App Version: Rnote v0.9.4
 - Installation Source: Archlinux Community Repo
 - Desktop Environment: Gnome 45.3
 - Display Server: Wayland
 - Input Source: Mouse, Keyboard, Drawing tablet

**Comment by flxzt** [comment]
Thanks for the report. This is already fixed (#969), it'll be included in the next release.
