### ISSUE TITLE
Images pasted from clipboard are scaled too large

### ISSUE THREAD

**Issue by MisterE123** [flxzt/rnote#991]
**Describe the bug**  
Say I want to insert the following screenshot to rnote:

![image](https://github.com/flxzt/rnote/assets/61124264/3d7184ec-9a7e-4edb-9355-bd89ab1eca0a)

I go to a blank space and press ctrl-V

... and its waay too large, much bigger than the page.

![image](https://github.com/flxzt/rnote/assets/61124264/6b8efc54-7529-47f4-88b5-5140963e2d64)

**To Reproduce**  
1. insert an image from the clipboard

**Expected behavior**  
The inserted image should be inserted with a width of 90% the current view size

**Desktop (please complete the following information):**  
 - OS: windows 11
 - App Version: Rnote v0.9.4
 - Installation Source: windows installer
 - Input Source: any

**Additional context**

**Comment by silvasch** [comment]
There already exists an issue for this: #974

**Comment by MisterE123** [comment]
Closing as duplicate
