### ISSUE TITLE
Autosave to temporary file

### ISSUE THREAD

**Issue by MisterE123** [flxzt/rnote#994]
I keep losing my work because I forget to save the file at first and then the computer shuts down.

Solution: if Autosave is enabled, then autosave to a temporary file if the file has not been saved yet. 

This would work hand-in-hand with #993, so you could retrieve files from the temporary file storage from "recently opened files"

**Comment by flxzt** [comment]
There is already a feature request for this open #545 - I'll close as duplicate.
